### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [ ]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "SMOTE" / "base_predictors" / "XGBoost_thres0.9_2026-05-07" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.98,,,,,
1,0,cf_1,,,6,,,,18.8058,,,0.8811,2,False,0.0274,0.0452
2,0,cf_2,,,,,,,15.2637,,,1.0,1,True,0.0274,0.0124
3,0,cf_3,3,,,,,,17.9877,,,0.9085,2,False,0.0274,0.0196
4,0,cf_4,,,,,,,17.2957,5,,0.9318,2,True,0.0274,0.0021
5,0,cf_5,1,1,,,,,18.9745,,,0.8754,3,False,0.0274,0.031
6,0,cf_6,,,,7,,,18.9745,7,,0.8754,3,False,0.0274,0.0698
7,0,cf_7,1,,,,1,,18.9745,,,0.8754,3,False,0.0274,0.0263
8,0,cf_8,,,5,,,,18.9619,2,,0.8758,3,False,0.0274,0.0244
9,1,xin,3,4,1,2,3,0,22.3757,0,0.95,,,,,
10,1,cf_1,2,,,,1,,22.3757,,,0.8796,3,True,0.6924,0.1514
11,1,cf_2,,,,,1,,22.3757,1,,0.8796,3,True,0.6924,0.2375
12,1,cf_3,,3,5,,,,22.3757,5,,0.8796,4,True,0.6924,0.2339
13,1,cf_4,,,,3,2,,22.3757,2,,0.8796,4,True,0.6924,0.1566
14,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
15,2,cf_1,,,5,5,,,22.68,,,0.8756,3,False,0.0454,0.108
16,2,cf_2,,2,,7,,,22.6757,,,0.8758,3,False,0.0454,0.0486
17,2,cf_3,,,6,,2,,20.1703,,,0.9848,3,False,0.0454,0.044
18,2,cf_4,,,6,,1,,19.82,,,1.0,3,False,0.0454,0.0248
19,2,cf_5,,,2,6,1,,22.68,,,0.8756,4,False,0.0454,0.1155
20,2,cf_6,4,,,4,2,,22.68,,,0.8756,4,False,0.0454,0.2425
21,3,xin,3,3,6,6,2,0,24.3418,1,1.11,,,,,
22,3,cf_1,,,,,,,21.2424,,,1.0,1,True,0.4508,0.1134
23,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
24,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0149,0.0149
25,4,cf_2,,,6,,,,21.2585,,,0.9868,2,False,0.0149,0.015
26,4,cf_3,,,5,,,,21.2585,,,0.9868,2,False,0.0149,0.0365
27,4,cf_4,,3,,,,,21.2585,,,0.9868,2,False,0.0149,0.0726
28,4,cf_5,4,,,,,,21.2585,,,0.9868,2,False,0.0149,0.0245
29,4,cf_6,3,,,,,,21.2585,,,0.9868,2,False,0.0149,0.0275
30,4,cf_7,1,2,,,,,21.2585,,,0.9868,3,False,0.0149,0.0839
31,4,cf_8,1,,,,,,21.2585,4,,0.9868,3,False,0.0149,0.2176
32,4,cf_9,2,3,,,,,21.2585,,,0.9868,3,False,0.0149,0.1791
33,4,cf_10,2,2,,,,,21.2585,,,0.9868,3,False,0.0149,0.0594
34,5,xin,2,2,1,2,4,0,27.9904,0,1.25,,,,,
35,5,cf_1,,,2,7,,,27.9904,,,1.0857,3,True,0.5796,0.1296
36,5,cf_2,1,,,,,,27.9904,7,,1.0857,3,True,0.5796,0.2151
37,5,cf_3,,,2,5,,,27.9904,,,1.0857,3,True,0.5796,0.1278
38,5,cf_4,1,,3,,,,27.9904,2,,1.0857,4,True,0.5796,0.2114
39,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
40,6,cf_1,,,,,,,27.1664,,,0.8987,1,True,0.1718,0.0652
41,6,cf_2,,,,,,,26.8128,,,0.9149,1,False,0.1718,0.2073
42,6,cf_3,,,,,,,26.4521,,,0.9315,1,False,0.1718,0.1832
43,6,cf_4,,,,,,,25.7762,,,0.9625,1,False,0.1718,0.179
44,6,cf_5,,,,,,,25.2637,,,0.9861,1,False,0.1718,0.1577
45,6,cf_6,,,,,,,24.9606,,,1.0,1,False,0.1718,0.224
46,6,cf_7,,,,7,,,27.5956,,,0.879,2,False,0.1718,0.2013
47,6,cf_8,,,,,,,27.1539,7,,0.8992,2,False,0.1718,0.0996
48,7,xin,2,3,6,3,1,0,20.4382,2,0.95,,,,,
49,7,cf_1,,,,,,,20.1425,,,0.8873,1,False,0.4019,0.2056
50,7,cf_2,,,,,,,19.5904,,,0.9103,1,True,0.4019,0.0417
51,7,cf_3,,,,,,,19.4579,,,0.9158,1,True,0.4019,0.0262
52,7,cf_4,,,,,,,19.3731,,,0.9194,1,True,0.4019,0.0292
53,7,cf_5,,,,,,,19.349,,,0.9204,1,True,0.4019,0.0292
54,7,cf_6,,,,,,,17.4368,,,1.0,1,True,0.4019,0.0004
55,7,cf_7,,,,7,,,20.4294,,,0.8754,2,True,0.4019,0.1777
56,8,xin,6,4,1,1,1,0,26.0146,0,1.02,,,,,
57,8,cf_1,,,,6,,,24.9336,1,,1.0,3,True,0.7228,0.0643
58,8,cf_2,3,,,5,,,26.0044,3,,0.8762,4,True,0.7228,0.1508
59,8,cf_3,,3,,4,,,25.2615,4,,0.9621,4,True,0.7228,0.0355
60,8,cf_4,3,,,7,,,24.9336,5,,1.0,4,True,0.7228,0.1417

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.98,,,,,
9,0,cf_2,,,,,,,15.2637,,,1.0,1,True,0.0274,0.0124
10,0,cf_4,,,,,,,17.2957,5,,0.9318,2,True,0.0274,0.0021
1,1,xin,3,4,1,2,3,0,22.3757,0,0.95,,,,,
11,1,cf_1,2,,,,1,,22.3757,,,0.8796,3,True,0.6924,0.1514
12,1,cf_2,,,,,1,,22.3757,1,,0.8796,3,True,0.6924,0.2375
13,1,cf_3,,3,5,,,,22.3757,5,,0.8796,4,True,0.6924,0.2339
14,1,cf_4,,,,3,2,,22.3757,2,,0.8796,4,True,0.6924,0.1566
2,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
31,2,cf_1,,,5,5,,,22.68,,,0.8756,3,False,0.0454,0.108
3,3,xin,3,3,6,6,2,0,24.3418,1,1.11,,,,,
15,3,cf_1,,,,,,,21.2424,,,1.0,1,True,0.4508,0.1134
4,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
32,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0149,0.0149
5,5,xin,2,2,1,2,4,0,27.9904,0,1.25,,,,,
16,5,cf_1,,,2,7,,,27.9904,,,1.0857,3,True,0.5796,0.1296
17,5,cf_2,1,,,,,,27.9904,7,,1.0857,3,True,0.5796,0.2151
18,5,cf_3,,,2,5,,,27.9904,,,1.0857,3,True,0.5796,0.1278
19,5,cf_4,1,,3,,,,27.9904,2,,1.0857,4,True,0.5796,0.2114
6,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
20,6,cf_1,,,,,,,27.1664,,,0.8987,1,True,0.1718,0.0652
7,7,xin,2,3,6,3,1,0,20.4382,2,0.95,,,,,
21,7,cf_2,,,,,,,19.5904,,,0.9103,1,True,0.4019,0.0417
22,7,cf_3,,,,,,,19.4579,,,0.9158,1,True,0.4019,0.0262
23,7,cf_4,,,,,,,19.3731,,,0.9194,1,True,0.4019,0.0292
24,7,cf_5,,,,,,,19.349,,,0.9204,1,True,0.4019,0.0292
25,7,cf_6,,,,,,,17.4368,,,1.0,1,True,0.4019,0.0004
26,7,cf_7,,,,7,,,20.4294,,,0.8754,2,True,0.4019,0.1777
8,8,xin,6,4,1,1,1,0,26.0146,0,1.02,,,,,
27,8,cf_1,,,,6,,,24.9336,1,,1.0,3,True,0.7228,0.0643
28,8,cf_2,3,,,5,,,26.0044,3,,0.8762,4,True,0.7228,0.1508
29,8,cf_3,,3,,4,,,25.2615,4,,0.9621,4,True,0.7228,0.0355
30,8,cf_4,3,,,7,,,24.9336,5,,1.0,4,True,0.7228,0.1417

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.98,,,,,
9,0,cf_4,,,,,,,17.2957,5,,0.9318,2,True,0.0274,0.0021
1,1,xin,3,4,1,2,3,0,22.3757,0,0.95,,,,,
10,1,cf_2,,,,,1,,22.3757,1,,0.8796,3,True,0.6924,0.2375
2,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
11,2,cf_1,,,5,5,,,22.68,,,0.8756,3,False,0.0454,0.108
3,3,xin,3,3,6,6,2,0,24.3418,1,1.11,,,,,
12,3,cf_1,,,,,,,21.2424,,,1.0,1,True,0.4508,0.1134
4,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
13,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0149,0.0149
5,5,xin,2,2,1,2,4,0,27.9904,0,1.25,,,,,
14,5,cf_2,1,,,,,,27.9904,7,,1.0857,3,True,0.5796,0.2151
6,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
15,6,cf_1,,,,,,,27.1664,,,0.8987,1,True,0.1718,0.0652
7,7,xin,2,3,6,3,1,0,20.4382,2,0.95,,,,,
16,7,cf_2,,,,,,,19.5904,,,0.9103,1,True,0.4019,0.0417
8,8,xin,6,4,1,1,1,0,26.0146,0,1.02,,,,,
17,8,cf_2,3,,,5,,,26.0044,3,,0.8762,4,True,0.7228,0.1508

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0124
Valid: True
Changes:
  bmi: 18.9866 → 15.2637

--- cf_4 ---
Predicted risk: 0.0021
Valid: True
Changes:
  bmi: 18.9866 → 17.2957
  dosprt: 0 → 5


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1514
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_2 ---
Predicted risk: 0.2375
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1

--- cf_3 ---
Predicted risk: 0.2339
Valid: True
Changes:
  eatveg: 4 → 3
  cgtsmok: 1 → 5
  dosprt: 0 → 5

--- cf_4 ---
Predicted risk: 0.1566
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 2
  dosprt: 0 → 2


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.108
Valid: False
Changes:
  cgtsmok: 1 → 5
  alcfreq: 1 → 5
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1134
Valid: True
Changes:
  bmi: 24.3418 → 21.2424


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0149
Valid: False
No feature changes.


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1296
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 2 → 7

--- cf_2 ---
Predicted risk: 0.2151
Valid: True
Changes:
  etfruit: 2 → 1
  dosprt: 0 → 7

--- cf_3 ---
Predicted risk: 0.1278
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 2 → 5

--- cf_4 ---
Predicted risk: 0.2114
Valid: True
Changes:
  etfruit: 2 → 1
  cgtsmok: 1 → 3
  dosprt: 0 → 2


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0652
Valid: True
Changes:
  bmi: 27.6817 → 27.1664


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0417
Valid: True
Changes:
  bmi: 20.4382 → 19.5904

--- cf_3 ---
Predicted risk: 0.0262
Valid: True
Changes:
  bmi: 20.4382 → 19.4579

--- cf_4 ---
Predicted risk: 0.0292
Valid: True
Changes:
  bmi: 20.4382 → 19.3731

--- cf_5 ---
Predicted risk: 0.0292
Valid: True
Changes:
  bmi: 20.4382 → 19.349

--- cf_6 ---
Predicted risk: 0.0004
Valid: True
Changes:
  bmi: 20.4382 → 17.4368

--- cf_7 ---
Predicted risk: 0.1777
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0643
Valid: True
Changes:
  alcfreq: 1 → 6
  bmi: 26.0146 → 24.9336
  dosprt: 0 → 1

--- cf_2 ---
Predicted risk: 0.1508
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_3 ---
Predicted risk: 0.0355
Valid: True
Changes:
  eatveg: 4 → 3
  alcfreq: 1 → 4
  bmi: 26.0146 → 25.2615
  dosprt: 0 → 4

--- cf_4 ---
Predicted risk: 0.1417
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 7
  bmi: 26.0146 → 24.9336
  dosprt: 0 → 5


=== Query index '9' ===
No recommendations available.