### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "baseline" / "RandomForest_thres0.1_2026-05-11" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Define columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]

# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.52,,,,,
1,0,cf_1,,,,,,,17.3186,,,0.1249,1,False,0.0633,0.0467
2,0,cf_2,,,,7,,,18.9745,,,0.1259,2,False,0.0633,0.07
3,0,cf_3,,,,,,,18.9619,2,,0.0376,2,True,0.0633,0.0133
4,0,cf_4,,,,,,,17.3169,5,,0.2143,2,False,0.0633,0.09
5,0,cf_5,,,,7,,,18.9745,7,,0.2509,3,True,0.0633,0.03
6,0,cf_6,,,6,7,,,18.9745,,,0.2509,3,False,0.0633,0.0933
7,1,xin,3,4,1,2,3,0,22.3757,0,2.57,,,,,
8,1,cf_1,1,,,,1,,22.3757,,,0.2546,3,False,0.1467,0.09
9,1,cf_2,2,,,,1,,22.3757,,,0.1921,3,True,0.1467,0.01
10,1,cf_3,2,,,4,,,22.3757,,,0.1296,3,False,0.1467,0.0867
11,1,cf_4,2,,,6,,,22.3757,,,0.1921,3,True,0.1467,0.0567
12,1,cf_5,,,,3,1,,22.3757,,,0.1609,3,True,0.1467,0.0
13,1,cf_6,,,,,2,,22.3757,7,,0.1921,3,False,0.1467,0.09
14,1,cf_7,,,,,1,,22.3757,1,,0.1475,3,True,0.1467,0.05
15,2,xin,5,3,1,1,4,0,22.694,7,2.72,,,,,
16,2,cf_1,1,,,,,,22.6757,,,0.25,2,False,0.1567,0.0833
17,2,cf_2,3,,,,2,,22.68,,,0.242,3,True,0.1567,0.0133
18,2,cf_3,,,,4,2,,22.6757,,,0.2833,3,True,0.1567,0.0633
19,2,cf_4,,,,3,2,,22.6757,,,0.2583,3,False,0.1567,0.0867
20,2,cf_5,,,,6,1,,22.6757,,,0.375,3,True,0.1567,0.0633
21,2,cf_6,,,2,6,1,,22.68,,,0.4712,4,True,0.1567,0.01
22,2,cf_7,4,,,4,2,,22.68,,,0.2858,4,True,0.1567,0.0067
23,3,xin,3,3,6,6,2,0,24.3418,1,3.02,,,,,
24,3,cf_1,,,,,,,24.3375,,,0.0005,1,True,0.02,0.01
25,3,cf_2,,,,,,,23.1884,,,0.125,1,False,0.02,0.0933
26,3,cf_3,,,,7,,,24.3375,,,0.1255,2,False,0.02,0.0333
27,3,cf_4,,,,,,,24.3375,4,,0.1255,2,False,0.02,0.02
28,3,cf_5,,,,,,,24.3375,3,,0.0838,2,True,0.02,0.0
29,4,xin,5,4,2,7,1,0,21.2585,3,3.18,,,,,
30,4,cf_1,,,,,,,21.2585,,,0.0,1,False,0.0267,0.0267
31,4,cf_2,,,6,,,,21.2585,,,0.125,2,True,0.0267,0.0033
32,4,cf_3,,,5,,,,21.2585,,,0.0938,2,True,0.0267,0.0067
33,4,cf_4,3,,,,,,21.2585,,,0.0625,2,False,0.0267,0.0533
34,4,cf_5,,3,,,,,21.2585,,,0.0417,2,True,0.0267,0.0133
35,4,cf_6,4,,,,,,21.2585,,,0.0313,2,False,0.0267,0.03
36,4,cf_7,,,3,,,,21.2585,,,0.0313,2,True,0.0267,0.01
37,4,cf_8,,,,,,,19.0,,,0.125,1,False,0.0267,0.04
38,4,cf_9,1,1,,,,,21.2585,,,0.25,3,False,0.0267,0.0333
39,5,xin,2,2,1,2,4,0,27.9904,0,2.88,,,,,
40,5,cf_1,,,,,3,,27.9904,,,0.2523,2,True,0.3267,0.0967
41,5,cf_2,,,,,1,,27.9904,,,0.3357,2,True,0.3267,0.0833
42,5,cf_3,,,4,,1,,27.9904,,,0.4607,3,True,0.3267,0.0867
43,6,xin,2,3,5,4,1,0,27.6817,4,2.41,,,,,
44,6,cf_1,,,,,,,25.1797,,,0.064,1,True,0.1467,0.06
45,6,cf_2,,,,,,,26.4292,7,,0.157,2,True,0.1467,0.0067
46,6,cf_3,,,6,,,,26.2538,,,0.1615,2,True,0.1467,0.0567
47,6,cf_4,,,,6,,,26.101,,,0.1654,2,True,0.1467,0.04
48,6,cf_5,,,,,,,22.9247,,,0.1216,1,True,0.1467,0.0033
49,6,cf_6,,,,,,,22.905,,,0.1221,1,True,0.1467,0.0067
50,6,cf_7,,,,,,,22.793,,,0.125,1,True,0.1467,0.0
51,6,cf_8,,,,,,,25.7387,5,,0.0913,2,True,0.1467,0.0167
52,7,xin,2,3,6,3,1,0,20.4382,2,2.43,,,,,
53,7,cf_1,,,,,,,20.4294,,,0.0004,1,False,0.0133,0.0167
54,7,cf_2,,,,,,,20.4284,,,0.0004,1,False,0.0133,0.02
55,7,cf_3,,,,,,,19.9215,,,0.0217,1,False,0.0133,0.01
56,7,cf_4,,,,,,,19.3578,,,0.0454,1,True,0.0133,0.0033
57,7,cf_5,,,,,,,18.996,,,0.0607,1,True,0.0133,0.0033
58,7,cf_6,,,,,,,18.6898,,,0.0736,1,True,0.0133,0.0033
59,7,cf_7,,,,,,,17.4669,,,0.125,1,True,0.0133,0.0033
60,7,cf_8,,,,7,,,20.4294,,,0.1254,2,False,0.0133,0.01
61,7,cf_9,,,,,,,20.4294,7,,0.1254,2,True,0.0133,0.0033
62,8,xin,6,4,1,1,1,0,26.0146,0,2.58,,,,,
63,8,cf_1,3,,,5,,,26.0044,,,0.1591,3,True,0.09,0.0367
64,8,cf_2,,,,2,,,26.0044,3,,0.0752,3,True,0.09,0.0167
65,8,cf_3,1,1,,,,,24.4017,,,0.375,3,True,0.09,0.0433
66,8,cf_4,1,3,,,,,24.4017,,,0.2917,3,True,0.09,0.0433
67,8,cf_5,5,2,,,,,24.4017,,,0.2333,3,True,0.09,0.0347
68,8,cf_6,1,,,4,,,26.0044,7,,0.3133,4,False,0.09,0.0967
69,8,cf_7,,2,,6,,,26.0044,7,,0.3133,4,True,0.09,0.0333
70,8,cf_8,4,,,2,,,26.0044,3,,0.1252,4,True,0.09,0.0333
71,8,cf_9,2,,,7,,,26.0044,3,,0.2794,4,True,0.09,0.0067

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.52,,,,,
9,0,cf_3,,,,,,,18.9619,2,,0.0376,2,True,0.0633,0.0133
10,0,cf_5,,,,7,,,18.9745,7,,0.2509,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.57,,,,,
11,1,cf_2,2,,,,1,,22.3757,,,0.1921,3,True,0.1467,0.01
12,1,cf_4,2,,,6,,,22.3757,,,0.1921,3,True,0.1467,0.0567
13,1,cf_5,,,,3,1,,22.3757,,,0.1609,3,True,0.1467,0.0
14,1,cf_7,,,,,1,,22.3757,1,,0.1475,3,True,0.1467,0.05
2,2,xin,5,3,1,1,4,0,22.694,7,2.72,,,,,
15,2,cf_2,3,,,,2,,22.68,,,0.242,3,True,0.1567,0.0133
16,2,cf_3,,,,4,2,,22.6757,,,0.2833,3,True,0.1567,0.0633
17,2,cf_5,,,,6,1,,22.6757,,,0.375,3,True,0.1567,0.0633
18,2,cf_6,,,2,6,1,,22.68,,,0.4712,4,True,0.1567,0.01
19,2,cf_7,4,,,4,2,,22.68,,,0.2858,4,True,0.1567,0.0067
3,3,xin,3,3,6,6,2,0,24.3418,1,3.02,,,,,
20,3,cf_1,,,,,,,24.3375,,,0.0005,1,True,0.02,0.01
21,3,cf_5,,,,,,,24.3375,3,,0.0838,2,True,0.02,0.0
4,4,xin,5,4,2,7,1,0,21.2585,3,3.18,,,,,
22,4,cf_2,,,6,,,,21.2585,,,0.125,2,True,0.0267,0.0033
23,4,cf_3,,,5,,,,21.2585,,,0.0938,2,True,0.0267,0.0067
24,4,cf_5,,3,,,,,21.2585,,,0.0417,2,True,0.0267,0.0133
25,4,cf_7,,,3,,,,21.2585,,,0.0313,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,2.88,,,,,
26,5,cf_1,,,,,3,,27.9904,,,0.2523,2,True,0.3267,0.0967
27,5,cf_2,,,,,1,,27.9904,,,0.3357,2,True,0.3267,0.0833
28,5,cf_3,,,4,,1,,27.9904,,,0.4607,3,True,0.3267,0.0867
6,6,xin,2,3,5,4,1,0,27.6817,4,2.41,,,,,
29,6,cf_1,,,,,,,25.1797,,,0.064,1,True,0.1467,0.06
30,6,cf_2,,,,,,,26.4292,7,,0.157,2,True,0.1467,0.0067
31,6,cf_3,,,6,,,,26.2538,,,0.1615,2,True,0.1467,0.0567
32,6,cf_4,,,,6,,,26.101,,,0.1654,2,True,0.1467,0.04
33,6,cf_5,,,,,,,22.9247,,,0.1216,1,True,0.1467,0.0033
34,6,cf_6,,,,,,,22.905,,,0.1221,1,True,0.1467,0.0067
35,6,cf_7,,,,,,,22.793,,,0.125,1,True,0.1467,0.0
36,6,cf_8,,,,,,,25.7387,5,,0.0913,2,True,0.1467,0.0167
7,7,xin,2,3,6,3,1,0,20.4382,2,2.43,,,,,
37,7,cf_4,,,,,,,19.3578,,,0.0454,1,True,0.0133,0.0033
38,7,cf_5,,,,,,,18.996,,,0.0607,1,True,0.0133,0.0033
39,7,cf_6,,,,,,,18.6898,,,0.0736,1,True,0.0133,0.0033
40,7,cf_7,,,,,,,17.4669,,,0.125,1,True,0.0133,0.0033
41,7,cf_9,,,,,,,20.4294,7,,0.1254,2,True,0.0133,0.0033
8,8,xin,6,4,1,1,1,0,26.0146,0,2.58,,,,,
42,8,cf_1,3,,,5,,,26.0044,,,0.1591,3,True,0.09,0.0367
43,8,cf_2,,,,2,,,26.0044,3,,0.0752,3,True,0.09,0.0167
44,8,cf_3,1,1,,,,,24.4017,,,0.375,3,True,0.09,0.0433
45,8,cf_4,1,3,,,,,24.4017,,,0.2917,3,True,0.09,0.0433
46,8,cf_5,5,2,,,,,24.4017,,,0.2333,3,True,0.09,0.0347
47,8,cf_7,,2,,6,,,26.0044,7,,0.3133,4,True,0.09,0.0333
48,8,cf_8,4,,,2,,,26.0044,3,,0.1252,4,True,0.09,0.0333
49,8,cf_9,2,,,7,,,26.0044,3,,0.2794,4,True,0.09,0.0067

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.52,,,,,
9,0,cf_5,,,,7,,,18.9745,7,,0.2509,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.57,,,,,
10,1,cf_4,2,,,6,,,22.3757,,,0.1921,3,True,0.1467,0.0567
2,2,xin,5,3,1,1,4,0,22.694,7,2.72,,,,,
11,2,cf_3,,,,4,2,,22.6757,,,0.2833,3,True,0.1567,0.0633
3,3,xin,3,3,6,6,2,0,24.3418,1,3.02,,,,,
12,3,cf_5,,,,,,,24.3375,3,,0.0838,2,True,0.02,0.0
4,4,xin,5,4,2,7,1,0,21.2585,3,3.18,,,,,
13,4,cf_3,,,5,,,,21.2585,,,0.0938,2,True,0.0267,0.0067
5,5,xin,2,2,1,2,4,0,27.9904,0,2.88,,,,,
14,5,cf_1,,,,,3,,27.9904,,,0.2523,2,True,0.3267,0.0967
6,6,xin,2,3,5,4,1,0,27.6817,4,2.41,,,,,
15,6,cf_2,,,,,,,26.4292,7,,0.157,2,True,0.1467,0.0067
7,7,xin,2,3,6,3,1,0,20.4382,2,2.43,,,,,
16,7,cf_5,,,,,,,18.996,,,0.0607,1,True,0.0133,0.0033
8,8,xin,6,4,1,1,1,0,26.0146,0,2.58,,,,,
17,8,cf_2,,,,2,,,26.0044,3,,0.0752,3,True,0.09,0.0167

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0133
Valid: True
Changes:
  bmi: 18.9866 → 18.9619
  dosprt: 0 → 2

--- cf_5 ---
Predicted risk: 0.03
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.01
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_4 ---
Predicted risk: 0.0567
Valid: True
Changes:
  etfruit: 3 → 2
  alcfreq: 2 → 6

--- cf_5 ---
Predicted risk: 0.0
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 1

--- cf_7 ---
Predicted risk: 0.05
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0133
Valid: True
Changes:
  etfruit: 5 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_3 ---
Predicted risk: 0.0633
Valid: True
Changes:
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.0633
Valid: True
Changes:
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_6 ---
Predicted risk: 0.01
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.68

--- cf_7 ---
Predicted risk: 0.0067
Valid: True
Changes:
  etfruit: 5 → 4
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.01
Valid: True
Changes:
  bmi: 24.3418 → 24.3375

--- cf_5 ---
Predicted risk: 0.0
Valid: True
Changes:
  bmi: 24.3418 → 24.3375
  dosprt: 1 → 3


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0033
Valid: True
Changes:
  cgtsmok: 2 → 6

--- cf_3 ---
Predicted risk: 0.0067
Valid: True
Changes:
  cgtsmok: 2 → 5

--- cf_5 ---
Predicted risk: 0.0133
Valid: True
Changes:
  eatveg: 4 → 3

--- cf_7 ---
Predicted risk: 0.01
Valid: True
Changes:
  cgtsmok: 2 → 3


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0967
Valid: True
Changes:
  slprl: 4 → 3

--- cf_2 ---
Predicted risk: 0.0833
Valid: True
Changes:
  slprl: 4 → 1

--- cf_3 ---
Predicted risk: 0.0867
Valid: True
Changes:
  cgtsmok: 1 → 4
  slprl: 4 → 1


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.06
Valid: True
Changes:
  bmi: 27.6817 → 25.1797

--- cf_2 ---
Predicted risk: 0.0067
Valid: True
Changes:
  bmi: 27.6817 → 26.4292
  dosprt: 4 → 7

--- cf_3 ---
Predicted risk: 0.0567
Valid: True
Changes:
  cgtsmok: 5 → 6
  bmi: 27.6817 → 26.2538

--- cf_4 ---
Predicted risk: 0.04
Valid: True
Changes:
  alcfreq: 4 → 6
  bmi: 27.6817 → 26.101

--- cf_5 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 27.6817 → 22.9247

--- cf_6 ---
Predicted risk: 0.0067
Valid: True
Changes:
  bmi: 27.6817 → 22.905

--- cf_7 ---
Predicted risk: 0.0
Valid: True
Changes:
  bmi: 27.6817 → 22.793

--- cf_8 ---
Predicted risk: 0.0167
Valid: True
Changes:
  bmi: 27.6817 → 25.7387
  dosprt: 4 → 5


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 19.3578

--- cf_5 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 18.996

--- cf_6 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 18.6898

--- cf_7 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 17.4669

--- cf_9 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 20.4294
  dosprt: 2 → 7


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0367
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044

--- cf_2 ---
Predicted risk: 0.0167
Valid: True
Changes:
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_3 ---
Predicted risk: 0.0433
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 24.4017

--- cf_4 ---
Predicted risk: 0.0433
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 3
  bmi: 26.0146 → 24.4017

--- cf_5 ---
Predicted risk: 0.0347
Valid: True
Changes:
  etfruit: 6 → 5
  eatveg: 4 → 2
  bmi: 26.0146 → 24.4017

--- cf_7 ---
Predicted risk: 0.0333
Valid: True
Changes:
  eatveg: 4 → 2
  alcfreq: 1 → 6
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 7

--- cf_8 ---
Predicted risk: 0.0333
Valid: True
Changes:
  etfruit: 6 → 4
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_9 ---
Predicted risk: 0.0067
Valid: True
Changes:
  etfruit: 6 → 2
  alcfreq: 1 → 7
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3


=== Query index '9' ===
No recommendations available.