### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [6]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "baseline" / "XGBoost_thres0.9_2026-05-11" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [7]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [8]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [9]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [10]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.29,,,,,
1,0,cf_1,,,,,,,17.1658,,,0.1118,1,True,0.026,0.004
2,0,cf_2,,,,7,,,18.9745,,,0.1257,2,False,0.026,0.0707
3,0,cf_3,3,,,,,,18.0887,,,0.1801,2,True,0.026,0.0064
4,0,cf_4,,,,,,,18.0858,3,,0.1089,2,True,0.026,0.0005
5,0,cf_5,,,,,,,18.0569,5,,0.1464,2,True,0.026,0.001
6,0,cf_6,,,,7,,,17.8165,,,0.1969,2,False,0.026,0.0424
7,0,cf_7,,,,6,,,17.5744,,,0.1701,2,True,0.026,0.0055
8,0,cf_8,,,6,,,,16.9514,,,0.25,2,True,0.026,0.005
9,0,cf_9,,,6,7,,,18.9745,,,0.2507,3,False,0.026,0.1428
10,0,cf_10,,,,7,,,18.9745,7,,0.2507,3,True,0.026,0.0038
11,1,xin,3,4,1,2,3,0,22.3757,0,1.1,,,,,
12,1,cf_1,,,,,,,22.3757,,,0.0046,1,False,0.2497,0.2497
13,1,cf_2,2,,,,1,,22.3757,,,0.2546,3,True,0.2497,0.0361
14,1,cf_3,,3,,,,,22.3757,6,,0.2368,3,True,0.2497,0.1213
15,1,cf_4,,,,,1,,22.3757,1,,0.1475,3,True,0.2497,0.0691
16,1,cf_5,,,,7,,,22.3757,7,,0.2546,3,False,0.2497,0.1783
17,1,cf_6,,,2,,1,,22.3757,,,0.1921,3,True,0.2497,0.0851
18,1,cf_7,,,,3,1,,22.3757,,,0.1546,3,True,0.2497,0.0534
19,1,cf_8,,,3,,2,,22.3757,2,,0.2278,4,False,0.2497,0.1589
20,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
21,2,cf_1,3,,,,2,,22.68,,,0.242,3,False,0.218,0.1394
22,2,cf_2,,,2,7,,,22.6757,,,0.375,3,False,0.218,0.1943
23,2,cf_3,,,,7,1,,22.6757,,,0.375,3,True,0.218,0.0267
24,2,cf_4,,,,3,2,,22.6757,,,0.25,3,True,0.218,0.0426
25,2,cf_5,1,,,3,,,22.6757,,,0.2917,3,True,0.218,0.0375
26,2,cf_6,,,,6,1,,22.6757,,,0.3542,3,True,0.218,0.1018
27,2,cf_7,,,,4,2,,22.6757,,,0.2708,3,True,0.218,0.0241
28,2,cf_8,,2,,2,3,,22.68,,,0.2837,4,False,0.218,0.1193
29,3,xin,3,3,6,6,2,0,24.3418,1,1.16,,,,,
30,3,cf_1,,,,,,,24.3375,,,0.0036,1,False,0.0653,0.0653
31,3,cf_2,,,,7,,,24.3375,,,0.1286,2,False,0.0653,0.0802
32,3,cf_3,1,,,,,,24.3375,,,0.1286,2,False,0.0653,0.0514
33,3,cf_4,,1,,,,,24.3375,,,0.1286,2,True,0.0653,0.0042
34,3,cf_5,,,,,1,,24.3375,,,0.1286,2,False,0.0653,0.055
35,3,cf_6,,,,,,,24.3375,3,,0.087,2,False,0.0653,0.0462
36,3,cf_7,,,,,,,24.3375,4,,0.1286,2,False,0.0653,0.0824
37,3,cf_8,,,,,,,24.194,4,,0.25,2,False,0.0653,0.0443
38,4,xin,5,4,2,7,1,0,21.2585,3,1.25,,,,,
39,4,cf_1,,,,,,,21.2585,,,0.1118,1,True,0.0811,0.0141
40,4,cf_2,,,6,,,,21.2585,,,0.2368,2,True,0.0811,0.0327
41,4,cf_3,,,3,,,,21.2585,,,0.1431,2,True,0.0811,0.0143
42,4,cf_4,,3,,,,,21.2585,,,0.2368,2,True,0.0811,0.016
43,4,cf_5,,,5,,,,21.2585,,,0.2056,2,True,0.0811,0.005
44,4,cf_6,4,,,,,,21.2585,,,0.1431,2,True,0.0811,0.0081
45,4,cf_7,3,,,,,,21.2585,,,0.1743,2,True,0.0811,0.0113
46,4,cf_8,1,,5,,,,21.2585,,,0.3306,3,True,0.0811,0.0386
47,4,cf_9,2,,,,,,21.2585,4,,0.2473,3,False,0.0811,0.0458
48,4,cf_10,3,,,,,,21.2585,6,,0.2993,3,False,0.0811,0.0491
49,5,xin,2,2,1,2,4,0,27.9904,0,1.17,,,,,
50,5,cf_1,,,,,,,27.9904,,,0.2107,1,False,0.0484,0.0484
51,5,cf_2,,,4,,,,27.9904,,,0.3357,2,False,0.0484,0.2138
52,5,cf_3,1,,,,,,27.9904,,,0.3357,2,False,0.0484,0.0258
53,5,cf_4,,,,,1,,27.9904,,,0.3357,2,False,0.0484,0.0401
54,5,cf_5,,,,7,,,27.9904,,,0.3357,2,False,0.0484,0.0848
55,5,cf_6,,,,4,,,27.9904,6,,0.3857,3,True,0.0484,0.0222
56,5,cf_7,,,,7,2,,27.9904,,,0.419,3,False,0.0484,0.0507
57,5,cf_8,,,,7,3,,27.9904,,,0.3773,3,False,0.0484,0.0572
58,5,cf_9,,,4,,1,,27.9904,,,0.4607,3,False,0.0484,0.1501
59,5,cf_10,,,2,5,,,27.9904,,,0.3273,3,False,0.0484,0.0858
60,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
61,6,cf_1,,,,,,,27.0584,,,0.021,1,False,0.0539,0.0298
62,6,cf_2,,,,,,,26.4758,,,0.0407,1,True,0.0539,0.0211
63,6,cf_3,,,,,,,25.0922,,,0.0874,1,False,0.0539,0.0405
64,6,cf_4,,,,6,,,27.5786,,,0.0868,2,False,0.0539,0.0329
65,6,cf_5,,,,,,,24.3029,,,0.114,1,True,0.0539,0.0268
66,6,cf_6,,,,6,,,27.2439,,,0.0981,2,True,0.0539,0.0262
67,6,cf_7,,,,7,,,27.2155,,,0.1407,2,True,0.0539,0.0208
68,6,cf_8,,,6,,,,27.1557,,,0.1427,2,False,0.0539,0.0336
69,6,cf_9,,,,,,,23.9761,,,0.125,1,False,0.0539,0.0964
70,6,cf_10,1,,,,,,26.8821,,,0.152,2,True,0.0539,0.0208
71,7,xin,2,3,6,3,1,0,20.4382,2,1.06,,,,,
72,7,cf_1,,,,,,,20.4294,,,0.0008,1,False,0.0565,0.0853
73,7,cf_2,,,,,,,20.4284,,,0.0009,1,False,0.0565,0.0853
74,7,cf_3,,,,,,,20.38,,,0.0054,1,False,0.0565,0.0853
75,7,cf_4,,,,,,,19.0925,,,0.125,1,True,0.0565,0.0067
76,7,cf_5,,,,7,,,20.4294,,,0.1258,2,False,0.0565,0.0532
77,7,cf_6,,,,,,,20.4284,4,,0.0842,2,False,0.0565,0.0553
78,7,cf_7,,2,,,,,20.4284,,,0.1259,2,False,0.0565,0.0342
79,7,cf_8,,,,6,,,20.4284,,,0.0947,2,False,0.0565,0.1535
80,7,cf_9,,,,,,,20.4284,5,,0.1259,2,False,0.0565,0.0389
81,7,cf_10,,,,4,,,20.4284,,,0.0322,2,False,0.0565,0.2106
82,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
83,8,cf_1,,,,,,,23.5854,,,0.125,1,True,0.1216,0.0426
84,8,cf_2,3,,,5,,,26.0044,,,0.2005,3,True,0.1216,0.0529
85,8,cf_3,1,1,,,,,25.888,,,0.2565,3,True,0.1216,0.0126
86,8,cf_4,2,1,,,,,25.888,,,0.2315,3,True,0.1216,0.004
87,8,cf_5,1,,,,,,24.0962,4,,0.3487,3,True,0.1216,0.0045
88,8,cf_6,5,1,,5,,,26.0044,,,0.2755,4,True,0.1216,0.0012
89,8,cf_7,4,,,2,,,26.0044,3,,0.1755,4,True,0.1216,0.0088
90,8,cf_8,3,,,3,,,26.0044,3,,0.2318,4,True,0.1216,0.0145
91,8,cf_9,2,2,,,,,26.0044,1,,0.2151,4,True,0.1216,0.0239

### Filtering Valid CFs

In [11]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.29,,,,,
9,0,cf_1,,,,,,,17.1658,,,0.1118,1,True,0.026,0.004
10,0,cf_3,3,,,,,,18.0887,,,0.1801,2,True,0.026,0.0064
11,0,cf_4,,,,,,,18.0858,3,,0.1089,2,True,0.026,0.0005
12,0,cf_5,,,,,,,18.0569,5,,0.1464,2,True,0.026,0.001
13,0,cf_7,,,,6,,,17.5744,,,0.1701,2,True,0.026,0.0055
14,0,cf_8,,,6,,,,16.9514,,,0.25,2,True,0.026,0.005
15,0,cf_10,,,,7,,,18.9745,7,,0.2507,3,True,0.026,0.0038
1,1,xin,3,4,1,2,3,0,22.3757,0,1.1,,,,,
16,1,cf_2,2,,,,1,,22.3757,,,0.2546,3,True,0.2497,0.0361
17,1,cf_3,,3,,,,,22.3757,6,,0.2368,3,True,0.2497,0.1213
18,1,cf_4,,,,,1,,22.3757,1,,0.1475,3,True,0.2497,0.0691
19,1,cf_6,,,2,,1,,22.3757,,,0.1921,3,True,0.2497,0.0851
20,1,cf_7,,,,3,1,,22.3757,,,0.1546,3,True,0.2497,0.0534
2,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
21,2,cf_3,,,,7,1,,22.6757,,,0.375,3,True,0.218,0.0267
22,2,cf_4,,,,3,2,,22.6757,,,0.25,3,True,0.218,0.0426
23,2,cf_5,1,,,3,,,22.6757,,,0.2917,3,True,0.218,0.0375
24,2,cf_6,,,,6,1,,22.6757,,,0.3542,3,True,0.218,0.1018
25,2,cf_7,,,,4,2,,22.6757,,,0.2708,3,True,0.218,0.0241
3,3,xin,3,3,6,6,2,0,24.3418,1,1.16,,,,,
26,3,cf_4,,1,,,,,24.3375,,,0.1286,2,True,0.0653,0.0042
4,4,xin,5,4,2,7,1,0,21.2585,3,1.25,,,,,
27,4,cf_1,,,,,,,21.2585,,,0.1118,1,True,0.0811,0.0141
28,4,cf_2,,,6,,,,21.2585,,,0.2368,2,True,0.0811,0.0327
29,4,cf_3,,,3,,,,21.2585,,,0.1431,2,True,0.0811,0.0143
30,4,cf_4,,3,,,,,21.2585,,,0.2368,2,True,0.0811,0.016
31,4,cf_5,,,5,,,,21.2585,,,0.2056,2,True,0.0811,0.005
32,4,cf_6,4,,,,,,21.2585,,,0.1431,2,True,0.0811,0.0081
33,4,cf_7,3,,,,,,21.2585,,,0.1743,2,True,0.0811,0.0113
34,4,cf_8,1,,5,,,,21.2585,,,0.3306,3,True,0.0811,0.0386
5,5,xin,2,2,1,2,4,0,27.9904,0,1.17,,,,,
35,5,cf_6,,,,4,,,27.9904,6,,0.3857,3,True,0.0484,0.0222
6,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
36,6,cf_2,,,,,,,26.4758,,,0.0407,1,True,0.0539,0.0211
37,6,cf_5,,,,,,,24.3029,,,0.114,1,True,0.0539,0.0268
38,6,cf_6,,,,6,,,27.2439,,,0.0981,2,True,0.0539,0.0262
39,6,cf_7,,,,7,,,27.2155,,,0.1407,2,True,0.0539,0.0208
40,6,cf_10,1,,,,,,26.8821,,,0.152,2,True,0.0539,0.0208
7,7,xin,2,3,6,3,1,0,20.4382,2,1.06,,,,,
41,7,cf_4,,,,,,,19.0925,,,0.125,1,True,0.0565,0.0067
8,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
42,8,cf_1,,,,,,,23.5854,,,0.125,1,True,0.1216,0.0426
43,8,cf_2,3,,,5,,,26.0044,,,0.2005,3,True,0.1216,0.0529
44,8,cf_3,1,1,,,,,25.888,,,0.2565,3,True,0.1216,0.0126
45,8,cf_4,2,1,,,,,25.888,,,0.2315,3,True,0.1216,0.004
46,8,cf_5,1,,,,,,24.0962,4,,0.3487,3,True,0.1216,0.0045
47,8,cf_6,5,1,,5,,,26.0044,,,0.2755,4,True,0.1216,0.0012
48,8,cf_7,4,,,2,,,26.0044,3,,0.1755,4,True,0.1216,0.0088
49,8,cf_8,3,,,3,,,26.0044,3,,0.2318,4,True,0.1216,0.0145
50,8,cf_9,2,2,,,,,26.0044,1,,0.2151,4,True,0.1216,0.0239

### select one CF

In [12]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.29,,,,,
9,0,cf_1,,,,,,,17.1658,,,0.1118,1,True,0.026,0.004
1,1,xin,3,4,1,2,3,0,22.3757,0,1.1,,,,,
10,1,cf_3,,3,,,,,22.3757,6,,0.2368,3,True,0.2497,0.1213
2,2,xin,5,3,1,1,4,0,22.694,7,1.16,,,,,
11,2,cf_4,,,,3,2,,22.6757,,,0.25,3,True,0.218,0.0426
3,3,xin,3,3,6,6,2,0,24.3418,1,1.16,,,,,
12,3,cf_4,,1,,,,,24.3375,,,0.1286,2,True,0.0653,0.0042
4,4,xin,5,4,2,7,1,0,21.2585,3,1.25,,,,,
13,4,cf_2,,,6,,,,21.2585,,,0.2368,2,True,0.0811,0.0327
5,5,xin,2,2,1,2,4,0,27.9904,0,1.17,,,,,
14,5,cf_6,,,,4,,,27.9904,6,,0.3857,3,True,0.0484,0.0222
6,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
15,6,cf_5,,,,,,,24.3029,,,0.114,1,True,0.0539,0.0268
7,7,xin,2,3,6,3,1,0,20.4382,2,1.06,,,,,
16,7,cf_4,,,,,,,19.0925,,,0.125,1,True,0.0565,0.0067
8,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
17,8,cf_8,3,,,3,,,26.0044,3,,0.2318,4,True,0.1216,0.0145

In [13]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.004
Valid: True
Changes:
  bmi: 18.9866 → 17.1658

--- cf_3 ---
Predicted risk: 0.0064
Valid: True
Changes:
  etfruit: 4 → 3
  bmi: 18.9866 → 18.0887

--- cf_4 ---
Predicted risk: 0.0005
Valid: True
Changes:
  bmi: 18.9866 → 18.0858
  dosprt: 0 → 3

--- cf_5 ---
Predicted risk: 0.001
Valid: True
Changes:
  bmi: 18.9866 → 18.0569
  dosprt: 0 → 5

--- cf_7 ---
Predicted risk: 0.0055
Valid: True
Changes:
  alcfreq: 4 → 6
  bmi: 18.9866 → 17.5744

--- cf_8 ---
Predicted risk: 0.005
Valid: True
Changes:
  cgtsmok: 3 → 6
  bmi: 18.9866 → 16.9514

--- cf_10 ---
Predicted risk: 0.0038
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0361
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_3 ---
Predicted risk: 0.1213
Valid: True
Changes:
  eatveg: 4 → 3
  dosprt: 0 → 6

--- cf_4 ---
Predicted risk: 0.0691
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1

--- cf_6 ---
Predicted risk: 0.0851
Valid: True
Changes:
  cgtsmok: 1 → 2
  slprl: 3 → 1

--- cf_7 ---
Predicted risk: 0.0534
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 1


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0267
Valid: True
Changes:
  alcfreq: 1 → 7
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_4 ---
Predicted risk: 0.0426
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.0375
Valid: True
Changes:
  etfruit: 5 → 1
  alcfreq: 1 → 3
  bmi: 22.694 → 22.6757

--- cf_6 ---
Predicted risk: 0.1018
Valid: True
Changes:
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_7 ---
Predicted risk: 0.0241
Valid: True
Changes:
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.6757


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0042
Valid: True
Changes:
  eatveg: 3 → 1
  bmi: 24.3418 → 24.3375


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0141
Valid: True
No feature changes.

--- cf_2 ---
Predicted risk: 0.0327
Valid: True
Changes:
  cgtsmok: 2 → 6

--- cf_3 ---
Predicted risk: 0.0143
Valid: True
Changes:
  cgtsmok: 2 → 3

--- cf_4 ---
Predicted risk: 0.016
Valid: True
Changes:
  eatveg: 4 → 3

--- cf_5 ---
Predicted risk: 0.005
Valid: True
Changes:
  cgtsmok: 2 → 5

--- cf_6 ---
Predicted risk: 0.0081
Valid: True
Changes:
  etfruit: 5 → 4

--- cf_7 ---
Predicted risk: 0.0113
Valid: True
Changes:
  etfruit: 5 → 3

--- cf_8 ---
Predicted risk: 0.0386
Valid: True
Changes:
  etfruit: 5 → 1
  cgtsmok: 2 → 5


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.0222
Valid: True
Changes:
  alcfreq: 2 → 4
  dosprt: 0 → 6


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0211
Valid: True
Changes:
  bmi: 27.6817 → 26.4758

--- cf_5 ---
Predicted risk: 0.0268
Valid: True
Changes:
  bmi: 27.6817 → 24.3029

--- cf_6 ---
Predicted risk: 0.0262
Valid: True
Changes:
  alcfreq: 4 → 6
  bmi: 27.6817 → 27.2439

--- cf_7 ---
Predicted risk: 0.0208
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 27.6817 → 27.2155

--- cf_10 ---
Predicted risk: 0.0208
Valid: True
Changes:
  etfruit: 2 → 1
  bmi: 27.6817 → 26.8821


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0067
Valid: True
Changes:
  bmi: 20.4382 → 19.0925


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0426
Valid: True
Changes:
  bmi: 26.0146 → 23.5854

--- cf_2 ---
Predicted risk: 0.0529
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044

--- cf_3 ---
Predicted risk: 0.0126
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 25.888

--- cf_4 ---
Predicted risk: 0.004
Valid: True
Changes:
  etfruit: 6 → 2
  eatveg: 4 → 1
  bmi: 26.0146 → 25.888

--- cf_5 ---
Predicted risk: 0.0045
Valid: True
Changes:
  etfruit: 6 → 1
  bmi: 26.0146 → 24.0962
  dosprt: 0 → 4

--- cf_6 ---
Predicted risk: 0.0012
Valid: True
Changes:
  etfruit: 6 → 5
  eatveg: 4 → 1
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044

--- cf_7 ---
Predicted risk: 0.0088
Valid: True
Changes:
  etfruit: 6 → 4
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_8 ---
Predicted risk: 0.0145
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 3
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_9 ---
Predicted risk: 0.0239
Valid: True
Changes:
  etfruit: 6 → 2
  eatveg: 4 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 1


=== Query index '9' ===
No recommendations available.