### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "SMOTE" / "base_predictors" / "XGBoost_thres0.9_2026-05-11" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.1,,,,,
1,0,cf_1,1,,,,,,18.9388,,,0.1268,2,False,0.0274,0.0324
2,0,cf_2,3,,,,,,18.7707,,,0.0497,2,False,0.0274,0.2389
3,0,cf_3,,,,,,,15.6339,,,0.125,1,True,0.0274,0.0124
4,0,cf_4,,,6,,,,17.5641,,,0.178,2,False,0.0274,0.0284
5,0,cf_5,,,,,,,17.2158,5,,0.1553,2,True,0.0274,0.0021
6,0,cf_6,,,,6,,,17.1306,,,0.1525,2,False,0.0274,0.1427
7,0,cf_7,3,,,,,,18.9745,7,,0.1671,3,False,0.0274,0.2063
8,0,cf_8,,,,7,,,18.9745,7,,0.2504,3,False,0.0274,0.0698
9,0,cf_9,,,5,,,,18.9619,2,,0.12,3,False,0.0274,0.0244
10,1,xin,3,4,1,2,3,0,22.3757,0,0.99,,,,,
11,1,cf_1,,,,,1,,22.3757,1,,0.1609,3,True,0.6924,0.2375
12,1,cf_2,2,,,,1,,22.3757,,,0.2546,3,True,0.6924,0.1514
13,1,cf_3,,3,,,1,,22.3757,4,,0.3796,4,True,0.6924,0.182
14,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
15,2,cf_1,,,,,,,19.1764,,,0.125,1,False,0.0454,0.0471
16,2,cf_2,,,2,6,1,,22.68,,,0.3755,4,False,0.0454,0.1155
17,2,cf_3,,2,,4,1,,22.68,,,0.3255,4,False,0.0454,0.124
18,2,cf_4,1,,,4,1,,22.68,,,0.3255,4,True,0.0454,0.0127
19,2,cf_5,1,,,4,3,,22.68,,,0.2422,4,False,0.0454,0.0386
20,2,cf_6,1,,,5,1,,22.68,,,0.3505,4,False,0.0454,0.0372
21,3,xin,3,3,6,6,2,0,24.3418,1,1.05,,,,,
22,3,cf_1,,,,,,,23.4429,,,0.125,1,False,0.4508,0.2489
23,4,xin,5,4,2,7,1,0,21.2585,3,1.18,,,,,
24,4,cf_1,,,,,,,21.2585,,,0.1118,1,False,0.0149,0.0149
25,4,cf_2,,,6,,,,21.2585,,,0.2368,2,False,0.0149,0.015
26,4,cf_3,,,5,,,,21.2585,,,0.2056,2,False,0.0149,0.0365
27,4,cf_4,,3,,,,,21.2585,,,0.1535,2,False,0.0149,0.0726
28,4,cf_5,4,,,,,,21.2585,,,0.1431,2,False,0.0149,0.0245
29,4,cf_6,3,,,,,,21.2585,,,0.1743,2,False,0.0149,0.0275
30,4,cf_7,1,1,,,,,21.2585,,,0.3618,3,False,0.0149,0.0787
31,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
32,5,cf_1,,,2,7,,,27.9904,,,0.15,3,True,0.5796,0.1296
33,5,cf_2,,,2,5,,,27.9904,,,0.1,3,True,0.5796,0.1278
34,5,cf_3,,,,7,,,27.9904,2,,0.1667,3,True,0.5796,0.101
35,5,cf_4,,1,,,,,27.9904,6,,0.25,3,True,0.5796,0.0051
36,5,cf_5,,,,,,,27.0,2,,0.1667,2,True,0.5796,0.0942
37,5,cf_6,,,6,3,,,27.9904,1,,0.1708,4,True,0.5796,0.2438
38,5,cf_7,,1,,7,,,27.9904,3,,0.3125,4,True,0.5796,0.0361
39,6,xin,2,3,5,4,1,0,27.6817,4,0.93,,,,,
40,6,cf_1,,,,,,,26.2612,,,0.0579,1,False,0.1718,0.1799
41,6,cf_2,,,,,,,25.9898,,,0.069,1,False,0.1718,0.238
42,6,cf_3,,,,,,,25.7557,,,0.0786,1,False,0.1718,0.179
43,6,cf_4,,,,,,,24.9078,,,0.1131,1,False,0.1718,0.1983
44,6,cf_5,,,,,,,24.8886,,,0.1139,1,False,0.1718,0.2206
45,6,cf_6,,,,,,,24.6171,,,0.125,1,False,0.1718,0.2469
46,6,cf_7,,,,7,,,27.5488,,,0.1304,2,False,0.1718,0.2013
47,7,xin,2,3,6,3,1,0,20.4382,2,0.93,,,,,
48,7,cf_1,,,,,,,20.07,,,0.125,1,True,0.4019,0.1377
49,7,cf_2,,,,7,,,20.4294,,,0.128,2,True,0.4019,0.1777
50,7,cf_3,,1,,,,,20.4284,,,0.1283,2,False,0.4019,0.2162
51,7,cf_4,,,,7,,,20.4152,,,0.1328,2,True,0.4019,0.1777
52,7,cf_5,,1,,,,,20.4152,,,0.1328,2,False,0.4019,0.2162
53,8,xin,6,4,1,1,1,0,26.0146,0,1.06,,,,,
54,8,cf_1,1,1,,,,,23.3574,,,0.3602,3,True,0.7228,0.0914
55,8,cf_2,5,1,,,,,23.3574,,,0.2602,3,True,0.7228,0.0914
56,8,cf_3,,3,,7,,,23.1675,,,0.2847,3,True,0.7228,0.0107
57,8,cf_4,5,,,3,,,26.0044,6,,0.1921,4,True,0.7228,0.1626
58,8,cf_5,,,,5,,,23.0,5,,0.3125,3,True,0.7228,0.0083

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.1,,,,,
9,0,cf_3,,,,,,,15.6339,,,0.125,1,True,0.0274,0.0124
10,0,cf_5,,,,,,,17.2158,5,,0.1553,2,True,0.0274,0.0021
1,1,xin,3,4,1,2,3,0,22.3757,0,0.99,,,,,
11,1,cf_1,,,,,1,,22.3757,1,,0.1609,3,True,0.6924,0.2375
12,1,cf_2,2,,,,1,,22.3757,,,0.2546,3,True,0.6924,0.1514
13,1,cf_3,,3,,,1,,22.3757,4,,0.3796,4,True,0.6924,0.182
2,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
14,2,cf_4,1,,,4,1,,22.68,,,0.3255,4,True,0.0454,0.0127
3,3,xin,3,3,6,6,2,0,24.3418,1,1.05,,,,,
30,3,cf_1,,,,,,,23.4429,,,0.125,1,False,0.4508,0.2489
4,4,xin,5,4,2,7,1,0,21.2585,3,1.18,,,,,
31,4,cf_1,,,,,,,21.2585,,,0.1118,1,False,0.0149,0.0149
5,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
15,5,cf_1,,,2,7,,,27.9904,,,0.15,3,True,0.5796,0.1296
16,5,cf_2,,,2,5,,,27.9904,,,0.1,3,True,0.5796,0.1278
17,5,cf_3,,,,7,,,27.9904,2,,0.1667,3,True,0.5796,0.101
18,5,cf_4,,1,,,,,27.9904,6,,0.25,3,True,0.5796,0.0051
19,5,cf_5,,,,,,,27.0,2,,0.1667,2,True,0.5796,0.0942
20,5,cf_6,,,6,3,,,27.9904,1,,0.1708,4,True,0.5796,0.2438
21,5,cf_7,,1,,7,,,27.9904,3,,0.3125,4,True,0.5796,0.0361
6,6,xin,2,3,5,4,1,0,27.6817,4,0.93,,,,,
32,6,cf_1,,,,,,,26.2612,,,0.0579,1,False,0.1718,0.1799
7,7,xin,2,3,6,3,1,0,20.4382,2,0.93,,,,,
22,7,cf_1,,,,,,,20.07,,,0.125,1,True,0.4019,0.1377
23,7,cf_2,,,,7,,,20.4294,,,0.128,2,True,0.4019,0.1777
24,7,cf_4,,,,7,,,20.4152,,,0.1328,2,True,0.4019,0.1777
8,8,xin,6,4,1,1,1,0,26.0146,0,1.06,,,,,
25,8,cf_1,1,1,,,,,23.3574,,,0.3602,3,True,0.7228,0.0914
26,8,cf_2,5,1,,,,,23.3574,,,0.2602,3,True,0.7228,0.0914
27,8,cf_3,,3,,7,,,23.1675,,,0.2847,3,True,0.7228,0.0107
28,8,cf_4,5,,,3,,,26.0044,6,,0.1921,4,True,0.7228,0.1626
29,8,cf_5,,,,5,,,23.0,5,,0.3125,3,True,0.7228,0.0083

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.1,,,,,
9,0,cf_5,,,,,,,17.2158,5,,0.1553,2,True,0.0274,0.0021
1,1,xin,3,4,1,2,3,0,22.3757,0,0.99,,,,,
10,1,cf_1,,,,,1,,22.3757,1,,0.1609,3,True,0.6924,0.2375
2,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
11,2,cf_4,1,,,4,1,,22.68,,,0.3255,4,True,0.0454,0.0127
3,3,xin,3,3,6,6,2,0,24.3418,1,1.05,,,,,
12,3,cf_1,,,,,,,23.4429,,,0.125,1,False,0.4508,0.2489
4,4,xin,5,4,2,7,1,0,21.2585,3,1.18,,,,,
13,4,cf_1,,,,,,,21.2585,,,0.1118,1,False,0.0149,0.0149
5,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
14,5,cf_1,,,2,7,,,27.9904,,,0.15,3,True,0.5796,0.1296
6,6,xin,2,3,5,4,1,0,27.6817,4,0.93,,,,,
15,6,cf_1,,,,,,,26.2612,,,0.0579,1,False,0.1718,0.1799
7,7,xin,2,3,6,3,1,0,20.4382,2,0.93,,,,,
16,7,cf_1,,,,,,,20.07,,,0.125,1,True,0.4019,0.1377
8,8,xin,6,4,1,1,1,0,26.0146,0,1.06,,,,,
17,8,cf_2,5,1,,,,,23.3574,,,0.2602,3,True,0.7228,0.0914

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0124
Valid: True
Changes:
  bmi: 18.9866 → 15.6339

--- cf_5 ---
Predicted risk: 0.0021
Valid: True
Changes:
  bmi: 18.9866 → 17.2158
  dosprt: 0 → 5


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.2375
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1

--- cf_2 ---
Predicted risk: 0.1514
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_3 ---
Predicted risk: 0.182
Valid: True
Changes:
  eatveg: 4 → 3
  slprl: 3 → 1
  dosprt: 0 → 4


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0127
Valid: True
Changes:
  etfruit: 5 → 1
  alcfreq: 1 → 4
  slprl: 4 → 1
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.2489
Valid: False
Changes:
  bmi: 24.3418 → 23.4429


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0149
Valid: False
No feature changes.


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1296
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 2 → 7

--- cf_2 ---
Predicted risk: 0.1278
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 2 → 5

--- cf_3 ---
Predicted risk: 0.101
Valid: True
Changes:
  alcfreq: 2 → 7
  dosprt: 0 → 2

--- cf_4 ---
Predicted risk: 0.0051
Valid: True
Changes:
  eatveg: 2 → 1
  dosprt: 0 → 6

--- cf_5 ---
Predicted risk: 0.0942
Valid: True
Changes:
  bmi: 27.9904 → 27.0
  dosprt: 0 → 2

--- cf_6 ---
Predicted risk: 0.2438
Valid: True
Changes:
  cgtsmok: 1 → 6
  alcfreq: 2 → 3
  dosprt: 0 → 1

--- cf_7 ---
Predicted risk: 0.0361
Valid: True
Changes:
  eatveg: 2 → 1
  alcfreq: 2 → 7
  dosprt: 0 → 3


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1799
Valid: False
Changes:
  bmi: 27.6817 → 26.2612


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1377
Valid: True
Changes:
  bmi: 20.4382 → 20.07

--- cf_2 ---
Predicted risk: 0.1777
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294

--- cf_4 ---
Predicted risk: 0.1777
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4152


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0914
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 23.3574

--- cf_2 ---
Predicted risk: 0.0914
Valid: True
Changes:
  etfruit: 6 → 5
  eatveg: 4 → 1
  bmi: 26.0146 → 23.3574

--- cf_3 ---
Predicted risk: 0.0107
Valid: True
Changes:
  eatveg: 4 → 3
  alcfreq: 1 → 7
  bmi: 26.0146 → 23.1675

--- cf_4 ---
Predicted risk: 0.1626
Valid: True
Changes:
  etfruit: 6 → 5
  alcfreq: 1 → 3
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 6

--- cf_5 ---
Predicted risk: 0.0083
Valid: True
Changes:
  alcfreq: 1 → 5
  bmi: 26.0146 → 23.0
  dosprt: 0 → 5


=== Query index '9' ===
No recommendations available.