In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
batch_cfcheck_data = CF_OUTPUTS / "weighted_predictors_mid_thres" / "xgb_2026-05-04" / "annotated.csv"
batch_cfcheck_df = pd.read_csv(batch_cfcheck_data)

In [3]:
pd.set_option("display.max_rows", None)

In [4]:
batch_cfcheck_df = batch_cfcheck_df.drop(columns=["hltprhc", "target_risk"])

In [5]:

batch_cfcheck_df["cf_id"] = batch_cfcheck_df["cf_id"].replace({"original": "xin"})

batch_cfcheck_df = batch_cfcheck_df.rename(columns={
    "original_risk": "risk_before",
    "predicted_risk" : "predicted_risk_after",
    "meets_target_risk" : "valid",
})

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,NaN,0.328773,NaN,1.54
1,0,cf_1,NaN,NaN,NaN,NaN,1.0,NaN,18.938780,NaN,False,0.328773,0.225610,NaN
2,0,cf_1,3.0,NaN,NaN,NaN,NaN,NaN,18.938780,NaN,False,0.328773,0.382019,NaN
3,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.929150,5.0,False,0.328773,0.246635,NaN

In [6]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

batch_cfcheck_df = fix_cf_id(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,NaN,0.328773,NaN,1.54
1,0,cf_1,NaN,NaN,NaN,NaN,1.0,NaN,18.938780,NaN,False,0.328773,0.225610,NaN
2,0,cf_2,3.0,NaN,NaN,NaN,NaN,NaN,18.938780,NaN,False,0.328773,0.382019,NaN
3,0,cf_3,NaN,NaN,NaN,NaN,NaN,NaN,18.929150,5.0,False,0.328773,0.246635,NaN
4,0,cf_4,NaN,NaN,NaN,NaN,NaN,NaN,15.926480,NaN,False,0.328773,0.240946,NaN
5,0,cf_5,2.0,NaN,NaN,NaN,NaN,NaN,18.521280,NaN,False,0.328773,0.380326,NaN
6,0,cf_6,NaN,NaN,NaN,NaN,NaN,NaN,18.185300,7.0,False,0.328773,0.387230,NaN
7,0,cf_7,NaN,NaN,NaN,NaN,NaN,NaN,17.612480,7.0,False,0.328773,0.358983,NaN
8,0,cf_8,NaN,NaN,6.0,NaN,NaN,NaN,17.451750,NaN,False,0.328773,0.267553,NaN
9,0,cf_9,NaN,NaN,NaN,NaN,NaN,NaN,17.191620,1.0,False,0.328773,0.180798,NaN
10,0,cf_10,NaN,1.0,NaN,NaN,1.0,NaN,18.961930,NaN,True,0.328773,0.143596,NaN
11,0,cf_11,1.0,NaN,NaN,NaN,NaN,NaN,18.961930,4.0,False,0.328773,0.383901,NaN
12,0,cf_12,3.0,NaN,NaN,NaN,NaN,NaN,18.961930,3.0,False,0.328773,0.224362,NaN
13,0,cf_13,NaN,NaN,5.0,NaN,NaN,NaN,18.961930,2.0,False,0.328773,0.209051,NaN
14,0,cf_14,NaN,NaN,5.0,NaN,NaN,NaN,18.961930,3.0,True,0.328773,0.139440,NaN
15,0,cf_15,NaN,NaN,6.0,NaN,NaN,NaN,18.956540,2.0,False,0.328773,0.281253,NaN
16,0,cf_16,2.0,NaN,NaN,NaN,NaN,NaN,18.938780,1.0,False,0.328773,0.299550,NaN
17,0,cf_17,NaN,NaN,NaN,7.0,NaN,NaN,18.937000,3.0,False,0.328773,0.230141,NaN
18,0,cf_18,NaN,NaN,NaN,NaN,1.0,NaN,18.937000,5.0,True,0.328773,0.137406,NaN
19,0,cf_19,NaN,NaN,4.0,NaN,NaN,NaN,18.937000,1.0,False,0.328773,0.330315,NaN
20,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.375680,0.0,NaN,0.678838,NaN,1.92
21,1,cf_1,2.0,NaN,NaN,NaN,1.0,NaN,22.375680,NaN,False,0.678838,0.360062,NaN
22,1,cf_2,NaN,NaN,NaN,NaN,1.0,NaN,22.375680,1.0,True,0.678838,0.303095,NaN
23,1,cf_3,NaN,NaN,NaN,3.0,1.0,NaN,22.375680,NaN,False,0.678838,0.364620,NaN
24,1,cf_4,NaN,NaN,5.0,NaN,1.0,NaN,22.375680,7.0,False,0.678838,0.353878,NaN
25,1,cf_5,NaN,2.0,NaN,NaN,1.0,NaN,22.375680,7.0,True,0.678838,0.335123,NaN
26,1,cf_6,NaN,2.0,NaN,NaN,2.0,NaN,22.375680,2.0,False,0.678838,0.391543,NaN
27,1,cf_7,NaN,3.0,NaN,NaN,1.0,NaN,22.375680,2.0,True,0.678838,0.247741,NaN
28,1,cf_8,NaN,3.0,NaN,NaN,1.0,NaN,22.375680,4.0,True,0.678838,0.216270,NaN
29,1,cf_9,NaN,NaN,NaN,3.0,1.0,NaN,22.375680,7.0,True,0.678838,0.335498,NaN

In [7]:
# round BMI to 2 decimal places, and set to NaN if equal to xin after rounding
def round_and_clear_bmi(df):
    df = df.copy()

    # Round BMI to 2 decimals for all rows
    df['bmi'] = df['bmi'].round(2)

    # For each query_index, get the xin BMI and compare
    for query_idx in df['query_index'].unique():
        query_mask = df['query_index'] == query_idx
        xin_mask = query_mask & (df['cf_id'] == 'xin')
        cf_mask = query_mask & (df['cf_id'] != 'xin')

        # Get the xin BMI value for this query
        xin_bmi = df.loc[xin_mask, 'bmi'].values[0]

        # Set cf BMI to NaN where it equals xin BMI
        equal_mask = cf_mask & (df['bmi'] == xin_bmi)
        df.loc[equal_mask, 'bmi'] = np.nan

    return df

batch_cfcheck_df = round_and_clear_bmi(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.99,0.0,NaN,0.328773,NaN,1.54
1,0,cf_1,NaN,NaN,NaN,NaN,1.0,NaN,18.94,NaN,False,0.328773,0.225610,NaN
2,0,cf_2,3.0,NaN,NaN,NaN,NaN,NaN,18.94,NaN,False,0.328773,0.382019,NaN
3,0,cf_3,NaN,NaN,NaN,NaN,NaN,NaN,18.93,5.0,False,0.328773,0.246635,NaN
4,0,cf_4,NaN,NaN,NaN,NaN,NaN,NaN,15.93,NaN,False,0.328773,0.240946,NaN
5,0,cf_5,2.0,NaN,NaN,NaN,NaN,NaN,18.52,NaN,False,0.328773,0.380326,NaN
6,0,cf_6,NaN,NaN,NaN,NaN,NaN,NaN,18.19,7.0,False,0.328773,0.387230,NaN
7,0,cf_7,NaN,NaN,NaN,NaN,NaN,NaN,17.61,7.0,False,0.328773,0.358983,NaN
8,0,cf_8,NaN,NaN,6.0,NaN,NaN,NaN,17.45,NaN,False,0.328773,0.267553,NaN
9,0,cf_9,NaN,NaN,NaN,NaN,NaN,NaN,17.19,1.0,False,0.328773,0.180798,NaN
10,0,cf_10,NaN,1.0,NaN,NaN,1.0,NaN,18.96,NaN,True,0.328773,0.143596,NaN
11,0,cf_11,1.0,NaN,NaN,NaN,NaN,NaN,18.96,4.0,False,0.328773,0.383901,NaN
12,0,cf_12,3.0,NaN,NaN,NaN,NaN,NaN,18.96,3.0,False,0.328773,0.224362,NaN
13,0,cf_13,NaN,NaN,5.0,NaN,NaN,NaN,18.96,2.0,False,0.328773,0.209051,NaN
14,0,cf_14,NaN,NaN,5.0,NaN,NaN,NaN,18.96,3.0,True,0.328773,0.139440,NaN
15,0,cf_15,NaN,NaN,6.0,NaN,NaN,NaN,18.96,2.0,False,0.328773,0.281253,NaN
16,0,cf_16,2.0,NaN,NaN,NaN,NaN,NaN,18.94,1.0,False,0.328773,0.299550,NaN
17,0,cf_17,NaN,NaN,NaN,7.0,NaN,NaN,18.94,3.0,False,0.328773,0.230141,NaN
18,0,cf_18,NaN,NaN,NaN,NaN,1.0,NaN,18.94,5.0,True,0.328773,0.137406,NaN
19,0,cf_19,NaN,NaN,4.0,NaN,NaN,NaN,18.94,1.0,False,0.328773,0.330315,NaN
20,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.38,0.0,NaN,0.678838,NaN,1.92
21,1,cf_1,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,False,0.678838,0.360062,NaN
22,1,cf_2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,True,0.678838,0.303095,NaN
23,1,cf_3,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,False,0.678838,0.364620,NaN
24,1,cf_4,NaN,NaN,5.0,NaN,1.0,NaN,NaN,7.0,False,0.678838,0.353878,NaN
25,1,cf_5,NaN,2.0,NaN,NaN,1.0,NaN,NaN,7.0,True,0.678838,0.335123,NaN
26,1,cf_6,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,False,0.678838,0.391543,NaN
27,1,cf_7,NaN,3.0,NaN,NaN,1.0,NaN,NaN,2.0,True,0.678838,0.247741,NaN
28,1,cf_8,NaN,3.0,NaN,NaN,1.0,NaN,NaN,4.0,True,0.678838,0.216270,NaN
29,1,cf_9,NaN,NaN,NaN,3.0,1.0,NaN,NaN,7.0,True,0.678838,0.335498,NaN

In [8]:
int_columns = [
    "etfruit",
    "eatveg",
    "cgtsmok",
    "alcfreq",
    "slprl",
    "paccnois",
    "dosprt",
]

float_columns = [
    "bmi",
    "risk_before",
    "predicted_risk_after",
]

In [9]:
batch_cfcheck_df[int_columns] = batch_cfcheck_df[int_columns].astype("Int64")

In [10]:
batch_cfcheck_df[float_columns] = batch_cfcheck_df[float_columns].round(2)

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,NaN,0.33,NaN,1.54
1,0,cf_1,<NA>,<NA>,<NA>,<NA>,1,<NA>,18.94,<NA>,False,0.33,0.23,NaN
2,0,cf_2,3,<NA>,<NA>,<NA>,<NA>,<NA>,18.94,<NA>,False,0.33,0.38,NaN
3,0,cf_3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18.93,5,False,0.33,0.25,NaN

In [11]:
batch_cfcheck_df[int_columns] = (
    batch_cfcheck_df[int_columns]
    .astype("string")
    .fillna("")
)

In [12]:
batch_cfcheck_df = batch_cfcheck_df.replace({np.nan : ""})
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,,0.33,,1.54
1,0,cf_1,,,,,1,,18.94,,False,0.33,0.23,
2,0,cf_2,3,,,,,,18.94,,False,0.33,0.38,
3,0,cf_3,,,,,,,18.93,5,False,0.33,0.25,

In [13]:
mask = batch_cfcheck_df["cf_id"] == "xin"
batch_cfcheck_df.loc[mask, "risk_before"] = ""
batch_cfcheck_df.head(4)

/tmp/ipykernel_113210/1160248817.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_cfcheck_df.loc[mask, "risk_before"] = ""

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,,,,1.54
1,0,cf_1,,,,,1,,18.94,,False,0.33,0.23,
2,0,cf_2,3,,,,,,18.94,,False,0.33,0.38,
3,0,cf_3,,,,,,,18.93,5,False,0.33,0.25,

In [14]:
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# 1. Beräkna Nchanged endast för CF-rader
mask_cf = batch_cfcheck_df["cf_id"] != "xin"

batch_cfcheck_df.loc[mask_cf, "Nchanged"] = (
    batch_cfcheck_df.loc[mask_cf, feature_cols] != ""
).sum(axis=1)

# 2. Konvertera kolumnen till ren string
batch_cfcheck_df["Nchanged"] = batch_cfcheck_df["Nchanged"].astype("string")

# 3. Baseline ska vara tom
batch_cfcheck_df.loc[batch_cfcheck_df["cf_id"] == "xin", "Nchanged"] = ""

In [15]:
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,Nchanged
0,0,xin,4,3,3,4,2,0,18.99,0,,,,1.54,
1,0,cf_1,,,,,1,,18.94,,False,0.33,0.23,,2
2,0,cf_2,3,,,,,,18.94,,False,0.33,0.38,,2
3,0,cf_3,,,,,,,18.93,5,False,0.33,0.25,,2

In [16]:
batch_cfcheck_df["Gower"] = ""
batch_cfcheck_df["Expected"] = ""

In [17]:
order = ["query_index", "cf_id"] + feature_cols + ["cf_gen_time_sec", "Gower", "Nchanged", "valid", "risk_before", "predicted_risk_after", "Expected"]

batch_cfcheck_df = batch_cfcheck_df[order]
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.54,,,,,,
1,0,cf_1,,,,,1,,18.94,,,,2,False,0.33,0.23,
2,0,cf_2,3,,,,,,18.94,,,,2,False,0.33,0.38,
3,0,cf_3,,,,,,,18.93,5,,,2,False,0.33,0.25,
4,0,cf_4,,,,,,,15.93,,,,1,False,0.33,0.24,
5,0,cf_5,2,,,,,,18.52,,,,2,False,0.33,0.38,
6,0,cf_6,,,,,,,18.19,7,,,2,False,0.33,0.39,
7,0,cf_7,,,,,,,17.61,7,,,2,False,0.33,0.36,
8,0,cf_8,,,6,,,,17.45,,,,2,False,0.33,0.27,
9,0,cf_9,,,,,,,17.19,1,,,2,False,0.33,0.18,
10,0,cf_10,,1,,,1,,18.96,,,,3,True,0.33,0.14,
11,0,cf_11,1,,,,,,18.96,4,,,3,False,0.33,0.38,
12,0,cf_12,3,,,,,,18.96,3,,,3,False,0.33,0.22,
13,0,cf_13,,,5,,,,18.96,2,,,3,False,0.33,0.21,
14,0,cf_14,,,5,,,,18.96,3,,,3,True,0.33,0.14,
15,0,cf_15,,,6,,,,18.96,2,,,3,False,0.33,0.28,
16,0,cf_16,2,,,,,,18.94,1,,,3,False,0.33,0.3,
17,0,cf_17,,,,7,,,18.94,3,,,3,False,0.33,0.23,
18,0,cf_18,,,,,1,,18.94,5,,,3,True,0.33,0.14,
19,0,cf_19,,,4,,,,18.94,1,,,3,False,0.33,0.33,
20,1,xin,3,4,1,2,3,0,22.38,0,1.92,,,,,,
21,1,cf_1,2,,,,1,,,,,,2,False,0.68,0.36,
22,1,cf_2,,,,,1,,,1,,,2,True,0.68,0.3,
23,1,cf_3,,,,3,1,,,,,,2,False,0.68,0.36,
24,1,cf_4,,,5,,1,,,7,,,3,False,0.68,0.35,
25,1,cf_5,,2,,,1,,,7,,,3,True,0.68,0.34,
26,1,cf_6,,2,,,2,,,2,,,3,False,0.68,0.39,
27,1,cf_7,,3,,,1,,,2,,,3,True,0.68,0.25,
28,1,cf_8,,3,,,1,,,4,,,3,True,0.68,0.22,
29,1,cf_9,,,,3,1,,,7,,,3,True,0.68,0.34,
30,1,cf_10,,,,3,2,,,2,,,3,True,0.68,0.33,
31,1,cf_11,,,,4,1,,,6,,,3,True,0.68,0.27,
32,1,cf_12,,,,3,1,,,3,,,3,True,0.68,0.17,
33,1,cf_13,1,1,,,1,,,,,,3,False,0.68,0.39,
34,2,xin,5,3,1,1,4,0,22.69,7,6.86,,,,,,
35,2,cf_1,1,,,,1,,22.68,,,,3,True,0.76,0.36,
36,2,cf_2,,,,4,2,,22.68,,,,3,False,0.76,0.39,
37,2,cf_3,,,,7,1,,22.66,,,,3,True,0.76,0.35,
38,2,cf_4,,,,6,1,,22.51,,,,3,True,0.76,0.33,
39,2,cf_5,,1,,,2,,22.35,,,,3,True,0.76,0.35,
40,2,cf_6,,1,,,3,,20.48,,,,3,False,0.76,0.38,
41,3,xin,3,3,6,6,2,0,24.34,1,1.59,,,,,,
42,3,cf_1,,,,,,,21.38,3,,,2,False,0.57,0.29,
43,3,cf_2,,1,,,,,,3,,,2,False,0.57,0.35,
44,4,xin,5,4,2,7,1,0,21.26,3,1.75,,,,,,
45,4,cf_1,,,,,,,,,,,0,False,0.14,0.13,
46,4,cf_2,,,6,,,,,,,,1,False,0.14,0.15,
47,4,cf_3,,,5,,,,,,,,1,False,0.14,0.13,
48,4,cf_4,,,4,,,,,,,,1,False,0.14,0.27,
49,4,cf_5,,,,,,,,7,,,1,False,0.14,0.28,
50,4,cf_6,,3,,,,,,,,,1,False,0.14,0.15,
51,4,cf_7,4,,,,,,,,,,1,False,0.14,0.13,
52,4,cf_8,3,,,,,,,,,,1,False,0.14,0.15,
53,4,cf_9,2,,,,,,,,,,1,False,0.14,0.17,
54,4,cf_10,1,3,,,,,,,,,2,False,0.14,0.21,
55,4,cf_11,,,5,,,,,6,,,2,False,0.14,0.24,
56,4,cf_12,1,,,,,,,4,,,2,False,0.14,0.24,
57,4,cf_13,1,,5,,,,,,,,2,False,0.14,0.23,
58,4,cf_14,2,3,,,,,,,,,2,False,0.14,0.18,
59,4,cf_15,2,,,,,,,7,,,2,False,0.14,0.35,
60,4,cf_16,2,,3,,,,,,,,2,False,0.14,0.23,
61,4,cf_17,3,2,,,,,,,,,2,False,0.14,0.12,
62,4,cf_18,3,,,,,,,4,,,2,False,0.14,0.15,
63,5,xin,2,2,1,2,4,0,27.99,0,2.09,,,,,,
64,5,cf_1,,,,,1,,,,,,1,False,0.59,0.4,
65,5,cf_2,,,,3,1,,,,,,2,False,0.59,0.39,
66,5,cf_3,,,,,2,,,1,,,2,False,0.59,0.38,
67,5,cf_4,,,,4,1,,,,,,2,False,0.59,0.33,
68,5,cf_5,,,,,1,,,4,,,2,True,0.59,0.23,
69,5,cf_6,,,,,2,,,4,,,2,False,0.59,0.34,
70,5,cf_7,,,,5,1,,,,,,2,False,0.59,0.35,
71,5,cf_8,,,,,1,,,1,,,2,False,0.59,0.32,
72,5,cf_9,,,,,1,,,3,,,2,True,0.59,0.22,
73,5,cf_10,,,,,2,,,2,,,2,False,0.59,0.39,
74,5,cf_11,,,2,5,1,,,,,,3,False,0.59,0.34,
75,5,cf_12,,,,3,2,,,5,,,3,False,0.59,0.35,
76,5,cf_13,,,,3,2,,,2,,,3,False,0.59,0.39,
77,6,xin,2,3,5,4,1,0,27.68,4,1.44,,,,,,
78,6,cf_1,,,,,,,27.52,,,,1,False,0.39,0.36,
79,6,cf_2,,,,,,,27.14,,,,1,False,0.39,0.33,
80,6,cf_3,,,,,,,26.67,,,,1,False,0.39,0.32,
81,6,cf_4,,,,,,,26.37,,,,1,False,0.39,0.3,
82,6,cf_5,,,,,,,26.23,,,,1,False,0.39,0.3,
83,6,cf_6,,,,,,,25.5,,,,1,False,0.39,0.3,
84,6,cf_7,,,,,,,24.73,,,,1,False,0.39,0.32,
85,6,cf_8,,,,,,,27.67,5,,,2,False,0.39,0.39,
86,6,cf_9,,2,,,,,27.66,,,,2,False,0.39,0.35,
87,6,cf_10,,1,,,,,27.66,,,,2,False,0.39,0.32,
88,6,cf_11,,2,,,,,27.64,,,,2,False,0.39,0.35,
89,7,xin,2,3,6,3,1,0,20.44,2,1.52,,,,,,
90,7,cf_1,,,,,,,20.43,,,,1,False,0.26,0.3,
91,7,cf_2,,,,,,,20.43,,,,1,False,0.26,0.3,
92,7,cf_3,,,,,,,20.4,,,,1,False,0.26,0.3,
93,7,cf_4,,,,,,,20.38,,,,1,False,0.26,0.3,
94,7,cf_5,,,,,,,20.38,,,,1,False,0.26,0.3,
95,7,cf_6,,,,,,,20.37,,,,1,False,0.26,0.3,
96,7,cf_7,,,,,,,20.21,,,,1,False,0.26,0.24,
97,7,cf_8,,,,,,,19.75,,,,1,False,0.26,0.27,
98,7,cf_9,,,,,,,17.45,,,,1,True,0.26,0.11,
99,7,cf_10,,,,7,,,20.43,,,,2,False,0.26,0.32,
100,7,cf_11,,,,,,,20.43,4,,,2,False,0.26,0.28,
101,7,cf_12,,,,,,,20.43,5,,,2,False,0.26,0.26,
102,7,cf_13,,,,6,,,20.43,,,,2,False,0.26,0.36,
103,7,cf_14,,,,,,,20.43,3,,,2,False,0.26,0.22,
104,7,cf_15,,,,,,,20.42,3,,,2,False,0.26,0.22,
105,7,cf_16,,,,,,,20.42,5,,,2,False,0.26,0.26,
106,7,cf_17,,,,,,,20.42,6,,,2,False,0.26,0.33,
107,7,cf_18,,2,,,,,20.42,,,,2,False,0.26,0.2,
108,8,xin,6,4,1,1,1,0,26.01,0,1.56,,,,,,
109,8,cf_1,3,,,5,,,26.0,,,,3,False,0.57,0.31,
110,8,cf_2,4,,,4,,,25.99,,,,3,True,0.57,0.25,
111,8,cf_3,,,,3,,,25.99,5,,,3,True,0.57,0.22,
112,8,cf_4,4,,,6,,,25.64,,,,3,False,0.57,0.38,
113,8,cf_5,,,,7,,,24.38,4,,,3,True,0.57,0.2,
114,8,cf_6,,,,3,,,23.62,4,,,3,True,0.57,0.13,
115,8,cf_7,3,,,7,,,23.06,,,,3,False,0.57,0.36,
116,8,cf_8,2,,,7,,,26.0,3,,,4,True,0.57,0.24,
117,8,cf_9,3,,,3,,,26.0,3,,,4,True,0.57,0.18,
118,8,cf_10,4,,,2,,,26.0,3,,,4,True,0.57,0.18,
119,8,cf_11,2,,,4,,,25.99,3,,,4,True,0.57,0.18,
120,8,cf_12,3,2,,3,,,25.99,,,,4,True,0.57,0.27,
121,8,cf_13,5,3,,4,,,25.99,,,,4,True,0.57,0.24,
122,8,cf_14,3,2,,2,,,25.99,,,,4,False,0.57,0.34,
123,8,cf_15,5,3,,,,,25.99,2,,,4,False,0.57,0.31,
124,8,cf_16,1,2,,3,,,25.91,,,,4,False,0.57,0.37,
125,8,cf_17,1,,,4,,,25.91,2,,,4,True,0.57,0.26,
126,8,cf_18,,2,5,2,,,25.7,,,,4,True,0.57,0.23,
127,8,cf_19,4,,5,5,,,25.68,,,,4,False,0.57,0.37,
128,8,cf_20,,,,4,,,22.23,1,,,3,True,0.57,0.19,

# picking correct CF

### expected

In [18]:
# Check directional constraints directly
# These features should only improve (increase) or stay the same
SHOULD_INCREASE = ["cgtsmok", "alcfreq", "dosprt"]

# These features should only improve (decrease) or stay the same
SHOULD_DECREASE = ["bmi", "etfruit", "eatveg", "slprl", "paccnois"]


print("Directional constraints:")
print(f"  Should increase (↑): {SHOULD_INCREASE}")
print(f"  Should decrease (↓): {SHOULD_DECREASE}")

Directional constraints:
  Should increase (↑): ['cgtsmok', 'alcfreq', 'dosprt']
  Should decrease (↓): ['bmi', 'etfruit', 'eatveg', 'slprl', 'paccnois']

In [19]:
# Check if CFs violate directional constraints
# First, ensure numeric columns are actually numeric for comparison
numeric_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# Create a working copy with numeric values
df_check = batch_cfcheck_df.copy()
for col in numeric_cols:
    df_check[col] = pd.to_numeric(df_check[col], errors="coerce")

# Extract baseline values per query_index
baseline_values = df_check[df_check["cf_id"] == "xin"].set_index("query_index")[numeric_cols]

# Check violations for each CF
def check_violations(row):
    if row["cf_id"] == "xin":
        return ""

    baseline = baseline_values.loc[row["query_index"]]
    violations = []

    # Check features that should increase
    for feat in SHOULD_INCREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] < baseline[feat]:
                violations.append(f"{feat}↓")

    # Check features that should decrease
    for feat in SHOULD_DECREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] > baseline[feat]:
                violations.append(f"{feat}↑")

    return "NO: " + ", ".join(violations) if violations else True

batch_cfcheck_df["Expected"] = df_check.apply(check_violations, axis=1)
batch_cfcheck_df.head(10)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.54,,,,,,
1,0,cf_1,,,,,1,,18.94,,,,2,False,0.33,0.23,True
2,0,cf_2,3,,,,,,18.94,,,,2,False,0.33,0.38,True
3,0,cf_3,,,,,,,18.93,5,,,2,False,0.33,0.25,True
4,0,cf_4,,,,,,,15.93,,,,1,False,0.33,0.24,True
5,0,cf_5,2,,,,,,18.52,,,,2,False,0.33,0.38,True
6,0,cf_6,,,,,,,18.19,7,,,2,False,0.33,0.39,True
7,0,cf_7,,,,,,,17.61,7,,,2,False,0.33,0.36,True
8,0,cf_8,,,6,,,,17.45,,,,2,False,0.33,0.27,True
9,0,cf_9,,,,,,,17.19,1,,,2,False,0.33,0.18,True

### is valid

In [20]:
# --- Select exactly one CF per query_index (random valid without violations) ---

# Split baseline and CF rows
df_xin = batch_cfcheck_df[batch_cfcheck_df["cf_id"] == "xin"]
df_cf  = batch_cfcheck_df[batch_cfcheck_df["cf_id"] != "xin"]

def select_random_cf(group):
    """Select one random CF that is valid and has no violations (Expected is empty)."""
    # First try: valid AND no violations
    good_cfs = group[(group["valid"] == True) & (group["Expected"] == "")]
    if len(good_cfs) > 0:
        return good_cfs.sample(n=1, random_state=42)

    # Fallback: any valid CF
    valid_cfs = group[group["valid"] == True]
    if len(valid_cfs) > 0:
        return valid_cfs.sample(n=1, random_state=42)

    # Last resort: first CF
    return group.iloc[[0]]

# Select one random CF per query_index
df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

# Combine baseline + selected CF
batch_cfcheck_df = pd.concat([df_xin, df_cf_selected], ignore_index=True)

# Ensure xin appears before CF for each query_index
batch_cfcheck_df["is_xin"] = (batch_cfcheck_df["cf_id"] == "xin").astype(int)
batch_cfcheck_df = (
    batch_cfcheck_df
    .sort_values(["query_index", "is_xin"], ascending=[True, False])
    .drop(columns="is_xin")
)
batch_cfcheck_df

/tmp/ipykernel_113210/2325069138.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.54,,,,,,
9,0,cf_10,,1,,,1,,18.96,,,,3,True,0.33,0.14,True
1,1,xin,3,4,1,2,3,0,22.38,0,1.92,,,,,,
10,1,cf_5,,2,,,1,,,7,,,3,True,0.68,0.34,True
2,2,xin,5,3,1,1,4,0,22.69,7,6.86,,,,,,
11,2,cf_3,,,,7,1,,22.66,,,,3,True,0.76,0.35,True
3,3,xin,3,3,6,6,2,0,24.34,1,1.59,,,,,,
12,3,cf_1,,,,,,,21.38,3,,,2,False,0.57,0.29,True
4,4,xin,5,4,2,7,1,0,21.26,3,1.75,,,,,,
13,4,cf_1,,,,,,,,,,,0,False,0.14,0.13,True
5,5,xin,2,2,1,2,4,0,27.99,0,2.09,,,,,,
14,5,cf_9,,,,,1,,,3,,,2,True,0.59,0.22,True
6,6,xin,2,3,5,4,1,0,27.68,4,1.44,,,,,,
15,6,cf_1,,,,,,,27.52,,,,1,False,0.39,0.36,True
7,7,xin,2,3,6,3,1,0,20.44,2,1.52,,,,,,
16,7,cf_9,,,,,,,17.45,,,,1,True,0.26,0.11,True
8,8,xin,6,4,1,1,1,0,26.01,0,1.56,,,,,,
17,8,cf_18,,2,5,2,,,25.7,,,,4,True,0.57,0.23,True

In [21]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_cfcheck_df, query_index=idx))

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777889238.915568  113210 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.99
  dosprt: 0


=== Counterfactuals ===

--- cf_10 ---
Predicted risk: 0.14
Valid: True
Changes:
  eatveg: 3 → 1
  slprl: 2 → 1
  bmi: 18.99 → 18.96


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.38
  dosprt: 0


=== Counterfactuals ===

--- cf_5 ---
Predicted risk: 0.34
Valid: True
Changes:
  eatveg: 4 → 2
  slprl: 3 → 1
  dosprt: 0 → 7


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.69
  dosprt: 7


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.35
Valid: True
Changes:
  alcfreq: 1 → 7
  slprl: 4 → 1
  bmi: 22.69 → 22.66


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.34
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.29
Valid: False
Changes:
  bmi: 24.34 → 21.38
  dosprt: 1 → 3


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.26
  dosprt: 3


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.13
Valid: False
No feature changes.


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.99
  dosprt: 0


=== Counterfactuals ===

--- cf_9 ---
Predicted risk: 0.22
Valid: True
Changes:
  slprl: 4 → 1
  dosprt: 0 → 3


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.68
  dosprt: 4


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.36
Valid: False
Changes:
  bmi: 27.68 → 27.52


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.44
  dosprt: 2


=== Counterfactuals ===

--- cf_9 ---
Predicted risk: 0.11
Valid: True
Changes:
  bmi: 20.44 → 17.45


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.01
  dosprt: 0


=== Counterfactuals ===

--- cf_18 ---
Predicted risk: 0.23
Valid: True
Changes:
  eatveg: 4 → 2
  cgtsmok: 1 → 5
  alcfreq: 1 → 2
  bmi: 26.01 → 25.7


=== Query index '9' ===
No recommendations available.