### imports and pandas settings

In [2]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [4]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [ ]:
batch_data = CF_OUTPUTS / "base_vs_thresholds" / "base_rf_lowthres_2026-05-05" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [ ]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [ ]:
# Define columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]

# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [7]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.42,,,,0.0633,
1,0,cf_1,,,,,,,18.7257,,,0.8884,1,False,0.0633,0.06
2,0,cf_2,,,,7,,,18.9745,,,0.8756,2,False,0.0633,0.07
3,0,cf_3,,,,7,,,18.1477,,,0.918,2,False,0.0633,0.05
4,0,cf_4,,,6,,,,17.4944,,,0.9515,2,False,0.0633,0.04
5,0,cf_5,,,,,,,17.1748,5,,0.9678,2,False,0.0633,0.0867
6,0,cf_6,3,,,,,,16.5468,,,1.0,2,False,0.0633,0.0967
7,0,cf_7,,,6,7,,,18.9745,,,0.8756,3,False,0.0633,0.0933
8,0,cf_8,,,,7,,,18.9745,7,,0.8756,3,True,0.0633,0.03
9,1,xin,3,4,1,2,3,0,22.3757,0,2.64,,,,0.1467,
10,1,cf_1,,,,7,,,22.3757,7,,0.8796,3,False,0.1467,0.0767
11,1,cf_2,,2,,,2,,22.3757,,,0.8796,3,False,0.1467,0.0933
12,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,True,0.1467,0.0
13,1,cf_4,,,,,2,,22.3757,7,,0.8796,3,False,0.1467,0.09
14,1,cf_5,,,2,,1,,22.3757,,,0.8796,3,True,0.1467,0.0233
15,1,cf_6,2,,,,1,,22.3757,,,0.8796,3,True,0.1467,0.01
16,1,cf_7,,,,,1,,22.3757,1,,0.8796,3,True,0.1467,0.05
17,2,xin,5,3,1,1,4,0,22.694,7,2.79,,,,0.1567,
18,2,cf_1,3,,,,2,,22.68,,,0.9712,3,True,0.1567,0.0133
19,2,cf_2,,,,6,1,,22.6757,,,1.0,3,True,0.1567,0.0633
20,2,cf_3,,,,4,2,,22.6757,,,1.0,3,True,0.1567,0.0633
21,2,cf_4,,,,3,2,,22.6757,,,1.0,3,False,0.1567,0.0867
22,2,cf_5,,,2,6,1,,22.68,,,0.9712,4,True,0.1567,0.01
23,3,xin,3,3,6,6,2,0,24.3418,1,2.86,,,,0.02,
24,3,cf_1,,,,,,,24.3375,,,0.8757,1,True,0.02,0.01
25,3,cf_2,,,,,,,23.5256,,,1.0,1,True,0.02,0.01
26,3,cf_3,,,,,,,24.3375,4,,0.8757,2,False,0.02,0.02
27,3,cf_4,,,,,,,24.3375,3,,0.8757,2,True,0.02,0.0
28,3,cf_5,,,,7,,,24.3375,,,0.8757,2,False,0.02,0.0333
29,4,xin,5,4,2,7,1,0,21.2585,3,3.12,,,,0.0267,
30,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0267,0.0267
31,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0267,0.0033
32,4,cf_3,3,,,,,,21.2585,,,0.9868,2,False,0.0267,0.0533
33,4,cf_4,4,,,,,,21.2585,,,0.9868,2,False,0.0267,0.03
34,4,cf_5,,3,,,,,21.2585,,,0.9868,2,True,0.0267,0.0133
35,4,cf_6,,,5,,,,21.2585,,,0.9868,2,True,0.0267,0.0067
36,4,cf_7,,,3,,,,21.2585,,,0.9868,2,True,0.0267,0.01
37,4,cf_8,,1,,,,,21.2585,4,,0.9868,3,False,0.0267,0.0367
38,4,cf_9,1,1,,,,,21.2585,,,0.9868,3,False,0.0267,0.0333
39,5,xin,2,2,1,2,4,0,27.9904,0,2.93,,,,0.3267,
40,5,cf_1,,,,,1,,27.9904,,,1.0857,2,True,0.3267,0.0833
41,5,cf_2,,,,,2,,27.9904,1,,1.0857,3,True,0.3267,0.0333
42,5,cf_3,,,,,1,,27.9904,3,,1.0857,3,True,0.3267,0.0233
43,6,xin,2,3,5,4,1,0,27.6817,4,2.35,,,,0.1467,
44,6,cf_1,,,,,,,26.8048,,,0.905,1,True,0.1467,0.0667
45,6,cf_2,,,,,,,26.2642,,,0.9235,1,True,0.1467,0.06
46,6,cf_3,,,,,,,26.0684,,,0.9302,1,True,0.1467,0.07
47,6,cf_4,,,6,,,,27.6576,,,0.8758,2,False,0.1467,0.0833
48,6,cf_5,,,,7,,,27.5607,,,0.8791,2,True,0.1467,0.0667
49,6,cf_6,,,,,,,27.3107,7,,0.8877,2,True,0.1467,0.06
50,6,cf_7,,,,,,,24.1169,,,0.9969,1,True,0.1467,0.01
51,6,cf_8,,,,,,,24.0252,,,1.0,1,True,0.1467,0.01
52,7,xin,2,3,6,3,1,0,20.4382,2,2.36,,,,0.0133,
53,7,cf_1,,,,,,,20.4284,,,0.8758,1,False,0.0133,0.02
54,7,cf_2,,,,,,,20.3656,,,0.8807,1,False,0.0133,0.0133
55,7,cf_3,,,,,,,20.0908,,,0.9025,1,False,0.0133,0.0333
56,7,cf_4,,,,,,,18.9283,,,0.9944,1,True,0.0133,0.0033
57,7,cf_5,,,,,,,18.8569,,,1.0,1,True,0.0133,0.0033
58,7,cf_6,,,,7,,,20.4294,,,0.8757,2,False,0.0133,0.01
59,7,cf_7,,,,6,,,20.4284,,,0.8758,2,False,0.0133,0.0333
60,7,cf_8,,,,,,,20.4284,4,,0.8758,2,False,0.0133,0.0367
61,7,cf_9,,,,,,,20.4284,5,,0.8758,2,False,0.0133,0.01
62,7,cf_10,,,,4,,,20.4284,,,0.8758,2,False,0.0133,0.0617
63,8,xin,6,4,1,1,1,0,26.0146,0,2.43,,,,0.09,
64,8,cf_1,3,,,5,,,26.0044,,,0.8751,3,True,0.09,0.0367
65,8,cf_2,1,1,,,,,24.8839,,,0.8909,3,False,0.09,0.0567
66,8,cf_3,,,,,,,17.1168,,,1.0,1,False,0.09,0.0833
67,8,cf_4,1,,2,,,,26.0044,4,,0.8751,4,False,0.09,0.0533
68,8,cf_5,2,,,7,,,26.0044,3,,0.8751,4,True,0.09,0.0067
69,8,cf_6,4,,,2,,,26.0044,3,,0.8751,4,True,0.09,0.0333

### Filtering Valid CFs

In [8]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.42,,,,0.0633,
9,0,cf_8,,,,7,,,18.9745,7,,0.8756,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.64,,,,0.1467,
10,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,True,0.1467,0.0
11,1,cf_5,,,2,,1,,22.3757,,,0.8796,3,True,0.1467,0.0233
12,1,cf_6,2,,,,1,,22.3757,,,0.8796,3,True,0.1467,0.01
13,1,cf_7,,,,,1,,22.3757,1,,0.8796,3,True,0.1467,0.05
2,2,xin,5,3,1,1,4,0,22.694,7,2.79,,,,0.1567,
14,2,cf_1,3,,,,2,,22.68,,,0.9712,3,True,0.1567,0.0133
15,2,cf_2,,,,6,1,,22.6757,,,1.0,3,True,0.1567,0.0633
16,2,cf_3,,,,4,2,,22.6757,,,1.0,3,True,0.1567,0.0633
17,2,cf_5,,,2,6,1,,22.68,,,0.9712,4,True,0.1567,0.01
3,3,xin,3,3,6,6,2,0,24.3418,1,2.86,,,,0.02,
18,3,cf_1,,,,,,,24.3375,,,0.8757,1,True,0.02,0.01
19,3,cf_2,,,,,,,23.5256,,,1.0,1,True,0.02,0.01
20,3,cf_4,,,,,,,24.3375,3,,0.8757,2,True,0.02,0.0
4,4,xin,5,4,2,7,1,0,21.2585,3,3.12,,,,0.0267,
21,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0267,0.0033
22,4,cf_5,,3,,,,,21.2585,,,0.9868,2,True,0.0267,0.0133
23,4,cf_6,,,5,,,,21.2585,,,0.9868,2,True,0.0267,0.0067
24,4,cf_7,,,3,,,,21.2585,,,0.9868,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,2.93,,,,0.3267,
25,5,cf_1,,,,,1,,27.9904,,,1.0857,2,True,0.3267,0.0833
26,5,cf_2,,,,,2,,27.9904,1,,1.0857,3,True,0.3267,0.0333
27,5,cf_3,,,,,1,,27.9904,3,,1.0857,3,True,0.3267,0.0233
6,6,xin,2,3,5,4,1,0,27.6817,4,2.35,,,,0.1467,
28,6,cf_1,,,,,,,26.8048,,,0.905,1,True,0.1467,0.0667
29,6,cf_2,,,,,,,26.2642,,,0.9235,1,True,0.1467,0.06
30,6,cf_3,,,,,,,26.0684,,,0.9302,1,True,0.1467,0.07
31,6,cf_5,,,,7,,,27.5607,,,0.8791,2,True,0.1467,0.0667
32,6,cf_6,,,,,,,27.3107,7,,0.8877,2,True,0.1467,0.06
33,6,cf_7,,,,,,,24.1169,,,0.9969,1,True,0.1467,0.01
34,6,cf_8,,,,,,,24.0252,,,1.0,1,True,0.1467,0.01
7,7,xin,2,3,6,3,1,0,20.4382,2,2.36,,,,0.0133,
35,7,cf_4,,,,,,,18.9283,,,0.9944,1,True,0.0133,0.0033
36,7,cf_5,,,,,,,18.8569,,,1.0,1,True,0.0133,0.0033
8,8,xin,6,4,1,1,1,0,26.0146,0,2.43,,,,0.09,
37,8,cf_1,3,,,5,,,26.0044,,,0.8751,3,True,0.09,0.0367
38,8,cf_5,2,,,7,,,26.0044,3,,0.8751,4,True,0.09,0.0067
39,8,cf_6,4,,,2,,,26.0044,3,,0.8751,4,True,0.09,0.0333

### select one CF

In [9]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.42,,,,0.0633,
9,0,cf_8,,,,7,,,18.9745,7,,0.8756,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.64,,,,0.1467,
10,1,cf_5,,,2,,1,,22.3757,,,0.8796,3,True,0.1467,0.0233
2,2,xin,5,3,1,1,4,0,22.694,7,2.79,,,,0.1567,
11,2,cf_2,,,,6,1,,22.6757,,,1.0,3,True,0.1567,0.0633
3,3,xin,3,3,6,6,2,0,24.3418,1,2.86,,,,0.02,
12,3,cf_1,,,,,,,24.3375,,,0.8757,1,True,0.02,0.01
4,4,xin,5,4,2,7,1,0,21.2585,3,3.12,,,,0.0267,
13,4,cf_5,,3,,,,,21.2585,,,0.9868,2,True,0.0267,0.0133
5,5,xin,2,2,1,2,4,0,27.9904,0,2.93,,,,0.3267,
14,5,cf_1,,,,,1,,27.9904,,,1.0857,2,True,0.3267,0.0833
6,6,xin,2,3,5,4,1,0,27.6817,4,2.35,,,,0.1467,
15,6,cf_1,,,,,,,26.8048,,,0.905,1,True,0.1467,0.0667
7,7,xin,2,3,6,3,1,0,20.4382,2,2.36,,,,0.0133,
16,7,cf_5,,,,,,,18.8569,,,1.0,1,True,0.0133,0.0033
8,8,xin,6,4,1,1,1,0,26.0146,0,2.43,,,,0.09,
17,8,cf_1,3,,,5,,,26.0044,,,0.8751,3,True,0.09,0.0367

In [10]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0

Original predicted risk: 0.0633

=== Counterfactuals ===

--- cf_8 ---
Predicted risk: 0.03
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0

Original predicted risk: 0.1467

=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 1

--- cf_5 ---
Predicted risk: 0.0233
Valid: True
Changes:
  cgtsmok: 1 → 2
  slprl: 3 → 1

--- cf_6 ---
Predicted risk: 0.01
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_7 ---
Predicted risk: 0.05
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7

Original predicted risk: 0.1567

=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0133
Valid: True
Changes:
  etfruit: 5 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_2 ---
Predicted risk: 0.0633
Valid: True
Changes:
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_3 ---
Predicted risk: 0.0633
Valid: True
Changes:
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.01
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1

Original predicted risk: 0.02

=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.01
Valid: True
Changes:
  bmi: 24.3418 → 24.3375

--- cf_2 ---
Predicted risk: 0.01
Valid: True
Changes:
  bmi: 24.3418 → 23.5256

--- cf_4 ---
Predicted risk: 0.0
Valid: True
Changes:
  bmi: 24.3418 → 24.3375
  dosprt: 1 → 3


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3

Original predicted risk: 0.0267

=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0033
Valid: True
Changes:
  cgtsmok: 2 → 6

--- cf_5 ---
Predicted risk: 0.0133
Valid: True
Changes:
  eatveg: 4 → 3

--- cf_6 ---
Predicted risk: 0.0067
Valid: True
Changes:
  cgtsmok: 2 → 5

--- cf_7 ---
Predicted risk: 0.01
Valid: True
Changes:
  cgtsmok: 2 → 3


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0

Original predicted risk: 0.3267

=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0833
Valid: True
Changes:
  slprl: 4 → 1

--- cf_2 ---
Predicted risk: 0.0333
Valid: True
Changes:
  slprl: 4 → 2
  dosprt: 0 → 1

--- cf_3 ---
Predicted risk: 0.0233
Valid: True
Changes:
  slprl: 4 → 1
  dosprt: 0 → 3


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4

Original predicted risk: 0.1467

=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0667
Valid: True
Changes:
  bmi: 27.6817 → 26.8048

--- cf_2 ---
Predicted risk: 0.06
Valid: True
Changes:
  bmi: 27.6817 → 26.2642

--- cf_3 ---
Predicted risk: 0.07
Valid: True
Changes:
  bmi: 27.6817 → 26.0684

--- cf_5 ---
Predicted risk: 0.0667
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 27.6817 → 27.5607

--- cf_6 ---
Predicted risk: 0.06
Valid: True
Changes:
  bmi: 27.6817 → 27.3107
  dosprt: 4 → 7

--- cf_7 ---
Predicted risk: 0.01
Valid: True
Changes:
  bmi: 27.6817 → 24.1169

--- cf_8 ---
Predicted risk: 0.01
Valid: True
Changes:
  bmi: 27.6817 → 24.0252


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2

Original predicted risk: 0.0133

=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 18.9283

--- cf_5 ---
Predicted risk: 0.0033
Valid: True
Changes:
  bmi: 20.4382 → 18.8569


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0

Original predicted risk: 0.09

=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0367
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044

--- cf_5 ---
Predicted risk: 0.0067
Valid: True
Changes:
  etfruit: 6 → 2
  alcfreq: 1 → 7
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_6 ---
Predicted risk: 0.0333
Valid: True
Changes:
  etfruit: 6 → 4
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3


=== Query index '9' ===
No recommendations available.