### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "base_vs_thresholds" / "base_xgb_highthres_2026-05-06" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.95,,,,,
1,0,cf_1,,,,,,,16.7643,,,0.9687,1,True,0.026,0.004
2,0,cf_2,,,,7,,,18.9745,,,0.8755,2,False,0.026,0.0707
3,0,cf_3,,,,6,,,18.4449,,,0.8979,2,False,0.026,0.0737
4,0,cf_4,,,6,,,,17.913,,,0.9203,2,True,0.026,0.0045
5,0,cf_5,,,,7,,,17.6252,,,0.9324,2,False,0.026,0.0424
6,0,cf_6,3,,,,,,16.4122,,,0.9836,2,True,0.026,0.0095
7,0,cf_7,,,,,,,16.0235,5,,1.0,2,True,0.026,0.0007
8,0,cf_8,,,6,7,,,18.9745,,,0.8755,3,False,0.026,0.1428
9,0,cf_9,,,,7,,,18.9745,7,,0.8755,3,True,0.026,0.0038
10,0,cf_10,3,,,,,,18.9619,3,,0.876,3,True,0.026,0.0117
11,1,xin,3,4,1,2,3,0,22.3757,0,1.06,,,,,
12,1,cf_1,,,,,,,22.3757,,,0.8796,1,False,0.2497,0.2497
13,1,cf_2,,,,7,,,22.3757,7,,0.8796,3,False,0.2497,0.1783
14,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,True,0.2497,0.0534
15,1,cf_4,,,2,,1,,22.3757,,,0.8796,3,True,0.2497,0.0851
16,1,cf_5,,,,,1,,22.3757,1,,0.8796,3,True,0.2497,0.0691
17,1,cf_6,,3,,,,,22.3757,6,,0.8796,3,True,0.2497,0.1213
18,1,cf_7,2,,,,1,,22.3757,,,0.8796,3,True,0.2497,0.0361
19,1,cf_8,1,2,,6,,,22.3757,,,0.8796,4,True,0.2497,0.036
20,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
21,2,cf_1,3,,,,2,,22.68,,,0.8753,3,False,0.218,0.1394
22,2,cf_2,,,,4,1,,22.68,,,0.8753,3,True,0.218,0.0217
23,2,cf_3,,,,4,2,,22.6757,,,0.8754,3,True,0.218,0.0241
24,2,cf_4,,,,6,1,,22.6757,,,0.8754,3,True,0.218,0.1018
25,2,cf_5,,,,3,2,,22.6757,,,0.8754,3,True,0.218,0.0426
26,2,cf_6,,,,,,,16.5946,,,1.0,1,True,0.218,0.0108
27,2,cf_7,,,2,6,1,,22.68,,,0.8753,4,True,0.218,0.0471
28,2,cf_8,3,,,2,2,,22.68,,,0.8753,4,True,0.218,0.0719
29,2,cf_9,2,,,7,2,,22.68,,,0.8753,4,True,0.218,0.079
30,3,xin,3,3,6,6,2,0,24.3418,1,1.02,,,,,
31,3,cf_1,,,,,,,24.3375,,,0.8753,1,False,0.0653,0.0653
32,3,cf_2,,,,,,,24.0,,,0.9023,1,False,0.0653,0.0755
33,3,cf_3,,,,,,,22.7746,,,1.0,1,False,0.0653,0.0806
34,3,cf_4,,,,7,,,24.3375,,,0.8753,2,False,0.0653,0.0802
35,3,cf_5,,,,,,,24.3375,4,,0.8753,2,False,0.0653,0.0824
36,3,cf_6,,,,,,,24.3375,3,,0.8753,2,False,0.0653,0.0462
37,3,cf_7,1,,,,,,24.3375,,,0.8753,2,False,0.0653,0.0514
38,3,cf_8,,,,,1,,24.3375,,,0.8753,2,False,0.0653,0.055
39,4,xin,5,4,2,7,1,0,21.2585,3,1.15,,,,,
40,4,cf_1,,,,,,,21.2585,,,0.9868,1,True,0.0811,0.0141
41,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0811,0.0327
42,4,cf_3,,,3,,,,21.2585,,,0.9868,2,True,0.0811,0.0143
43,4,cf_4,,,5,,,,21.2585,,,0.9868,2,True,0.0811,0.005
44,4,cf_5,3,,,,,,21.2585,,,0.9868,2,True,0.0811,0.0113
45,4,cf_6,,3,,,,,21.2585,,,0.9868,2,True,0.0811,0.016
46,4,cf_7,4,,,,,,21.2585,,,0.9868,2,True,0.0811,0.0081
47,4,cf_8,,1,,,,,21.2585,,,0.9868,2,True,0.0811,0.0133
48,4,cf_9,,2,4,,,,21.2585,,,0.9868,3,True,0.0811,0.0199
49,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
50,5,cf_1,,,,,,,27.9904,,,1.0857,1,False,0.0484,0.0484
51,5,cf_2,,,,,1,,27.9904,,,1.0857,2,False,0.0484,0.0401
52,5,cf_3,,,4,,,,27.9904,,,1.0857,2,False,0.0484,0.2138
53,5,cf_4,,,,7,,,27.9904,,,1.0857,2,False,0.0484,0.0848
54,5,cf_5,,,,,1,,27.9904,3,,1.0857,3,False,0.0484,0.0286
55,5,cf_6,,,,,3,,27.9904,5,,1.0857,3,False,0.0484,0.0448
56,5,cf_7,,,6,,1,,27.9904,,,1.0857,3,False,0.0484,0.0852
57,5,cf_8,1,,,5,,,27.9904,,,1.0857,3,False,0.0484,0.0791
58,5,cf_9,,,4,,,,27.9904,2,,1.0857,3,False,0.0484,0.0997
59,5,cf_10,,,2,5,,,27.9904,,,1.0857,3,False,0.0484,0.0858
60,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
61,6,cf_1,,,,,,,27.6398,,,0.8768,1,False,0.0539,0.1166
62,6,cf_2,,,,,,,27.1147,,,0.8992,1,True,0.0539,0.0141
63,6,cf_3,,,,,,,27.0581,,,0.9016,1,False,0.0539,0.0298
64,6,cf_4,,,,,,,26.5459,,,0.9234,1,True,0.0539,0.0224
65,6,cf_5,,,,,,,25.8718,,,0.9521,1,False,0.0539,0.0466
66,6,cf_6,,,,,,,24.7492,,,1.0,1,False,0.0539,0.0544
67,6,cf_7,,2,,,,,26.9549,,,0.906,2,True,0.0539,0.0193
68,6,cf_8,,,,7,,,26.9015,,,0.9083,2,False,0.0539,0.0443
69,6,cf_9,,,6,,,,26.8471,,,0.9106,2,False,0.0539,0.0289
70,6,cf_10,,,,,,,26.8145,7,,0.912,2,True,0.0539,0.0188
71,7,xin,2,3,6,3,1,0,20.4382,2,0.92,,,,,
72,7,cf_1,,,,,,,20.4294,,,0.8754,1,False,0.0565,0.0853
73,7,cf_2,,,,,,,20.4284,,,0.8754,1,False,0.0565,0.0853
74,7,cf_3,,,,,,,19.7788,,,0.9026,1,True,0.0565,0.0083
75,7,cf_4,,,,,,,19.5254,,,0.9132,1,True,0.0565,0.0023
76,7,cf_5,,,,,,,19.463,,,0.9158,1,True,0.0565,0.0029
77,7,cf_6,,,,,,,18.0,,,0.977,1,True,0.0565,0.0007
78,7,cf_7,,,,,,,17.856,,,0.9831,1,True,0.0565,0.0003
79,7,cf_8,,,,,,,17.626,,,0.9927,1,True,0.0565,0.0003
80,7,cf_9,,,,,,,17.451,,,1.0,1,True,0.0565,0.0003
81,7,cf_10,,,,,,,20.4353,3,,0.8751,2,True,0.0565,0.0263
82,8,xin,6,4,1,1,1,0,26.0146,0,1.03,,,,,
83,8,cf_1,3,,,5,,,26.0044,,,0.8755,3,True,0.1216,0.0529
84,8,cf_2,1,,,,,,26.0044,6,,0.8755,3,True,0.1216,0.0413
85,8,cf_3,3,,6,,,,25.7169,,,0.8887,3,False,0.1216,0.0661
86,8,cf_4,4,,,6,,,25.1346,,,0.9155,3,True,0.1216,0.0491
87,8,cf_5,1,,6,,,,24.811,,,0.9304,3,True,0.1216,0.0231
88,8,cf_6,,,,5,,,23.2979,1,,1.0,3,True,0.1216,0.0532
89,8,cf_7,1,3,3,,,,26.0044,,,0.8755,4,False,0.1216,0.0668
90,8,cf_8,2,,3,,,,26.0044,6,,0.8755,4,True,0.1216,0.0579

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.95,,,,,
9,0,cf_1,,,,,,,16.7643,,,0.9687,1,True,0.026,0.004
10,0,cf_4,,,6,,,,17.913,,,0.9203,2,True,0.026,0.0045
11,0,cf_6,3,,,,,,16.4122,,,0.9836,2,True,0.026,0.0095
12,0,cf_7,,,,,,,16.0235,5,,1.0,2,True,0.026,0.0007
13,0,cf_9,,,,7,,,18.9745,7,,0.8755,3,True,0.026,0.0038
14,0,cf_10,3,,,,,,18.9619,3,,0.876,3,True,0.026,0.0117
1,1,xin,3,4,1,2,3,0,22.3757,0,1.06,,,,,
15,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,True,0.2497,0.0534
16,1,cf_4,,,2,,1,,22.3757,,,0.8796,3,True,0.2497,0.0851
17,1,cf_5,,,,,1,,22.3757,1,,0.8796,3,True,0.2497,0.0691
18,1,cf_6,,3,,,,,22.3757,6,,0.8796,3,True,0.2497,0.1213
19,1,cf_7,2,,,,1,,22.3757,,,0.8796,3,True,0.2497,0.0361
20,1,cf_8,1,2,,6,,,22.3757,,,0.8796,4,True,0.2497,0.036
2,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
21,2,cf_2,,,,4,1,,22.68,,,0.8753,3,True,0.218,0.0217
22,2,cf_3,,,,4,2,,22.6757,,,0.8754,3,True,0.218,0.0241
23,2,cf_4,,,,6,1,,22.6757,,,0.8754,3,True,0.218,0.1018
24,2,cf_5,,,,3,2,,22.6757,,,0.8754,3,True,0.218,0.0426
25,2,cf_6,,,,,,,16.5946,,,1.0,1,True,0.218,0.0108
26,2,cf_7,,,2,6,1,,22.68,,,0.8753,4,True,0.218,0.0471
27,2,cf_8,3,,,2,2,,22.68,,,0.8753,4,True,0.218,0.0719
28,2,cf_9,2,,,7,2,,22.68,,,0.8753,4,True,0.218,0.079
3,3,xin,3,3,6,6,2,0,24.3418,1,1.02,,,,,
4,4,xin,5,4,2,7,1,0,21.2585,3,1.15,,,,,
29,4,cf_1,,,,,,,21.2585,,,0.9868,1,True,0.0811,0.0141
30,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0811,0.0327
31,4,cf_3,,,3,,,,21.2585,,,0.9868,2,True,0.0811,0.0143
32,4,cf_4,,,5,,,,21.2585,,,0.9868,2,True,0.0811,0.005
33,4,cf_5,3,,,,,,21.2585,,,0.9868,2,True,0.0811,0.0113
34,4,cf_6,,3,,,,,21.2585,,,0.9868,2,True,0.0811,0.016
35,4,cf_7,4,,,,,,21.2585,,,0.9868,2,True,0.0811,0.0081
36,4,cf_8,,1,,,,,21.2585,,,0.9868,2,True,0.0811,0.0133
37,4,cf_9,,2,4,,,,21.2585,,,0.9868,3,True,0.0811,0.0199
5,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
6,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
38,6,cf_2,,,,,,,27.1147,,,0.8992,1,True,0.0539,0.0141
39,6,cf_4,,,,,,,26.5459,,,0.9234,1,True,0.0539,0.0224
40,6,cf_7,,2,,,,,26.9549,,,0.906,2,True,0.0539,0.0193
41,6,cf_10,,,,,,,26.8145,7,,0.912,2,True,0.0539,0.0188
7,7,xin,2,3,6,3,1,0,20.4382,2,0.92,,,,,
42,7,cf_3,,,,,,,19.7788,,,0.9026,1,True,0.0565,0.0083
43,7,cf_4,,,,,,,19.5254,,,0.9132,1,True,0.0565,0.0023
44,7,cf_5,,,,,,,19.463,,,0.9158,1,True,0.0565,0.0029
45,7,cf_6,,,,,,,18.0,,,0.977,1,True,0.0565,0.0007
46,7,cf_7,,,,,,,17.856,,,0.9831,1,True,0.0565,0.0003
47,7,cf_8,,,,,,,17.626,,,0.9927,1,True,0.0565,0.0003
48,7,cf_9,,,,,,,17.451,,,1.0,1,True,0.0565,0.0003
49,7,cf_10,,,,,,,20.4353,3,,0.8751,2,True,0.0565,0.0263
8,8,xin,6,4,1,1,1,0,26.0146,0,1.03,,,,,
50,8,cf_1,3,,,5,,,26.0044,,,0.8755,3,True,0.1216,0.0529
51,8,cf_2,1,,,,,,26.0044,6,,0.8755,3,True,0.1216,0.0413
52,8,cf_4,4,,,6,,,25.1346,,,0.9155,3,True,0.1216,0.0491
53,8,cf_5,1,,6,,,,24.811,,,0.9304,3,True,0.1216,0.0231
54,8,cf_6,,,,5,,,23.2979,1,,1.0,3,True,0.1216,0.0532
55,8,cf_8,2,,3,,,,26.0044,6,,0.8755,4,True,0.1216,0.0579

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.95,,,,,
9,0,cf_1,,,,,,,16.7643,,,0.9687,1,True,0.026,0.004
1,1,xin,3,4,1,2,3,0,22.3757,0,1.06,,,,,
10,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,True,0.2497,0.0534
2,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
11,2,cf_3,,,,4,2,,22.6757,,,0.8754,3,True,0.218,0.0241
3,3,xin,3,3,6,6,2,0,24.3418,1,1.02,,,,,
4,4,xin,5,4,2,7,1,0,21.2585,3,1.15,,,,,
12,4,cf_8,,1,,,,,21.2585,,,0.9868,2,True,0.0811,0.0133
5,5,xin,2,2,1,2,4,0,27.9904,0,1.11,,,,,
6,6,xin,2,3,5,4,1,0,27.6817,4,0.91,,,,,
13,6,cf_4,,,,,,,26.5459,,,0.9234,1,True,0.0539,0.0224
7,7,xin,2,3,6,3,1,0,20.4382,2,0.92,,,,,
14,7,cf_4,,,,,,,19.5254,,,0.9132,1,True,0.0565,0.0023
8,8,xin,6,4,1,1,1,0,26.0146,0,1.03,,,,,
15,8,cf_1,3,,,5,,,26.0044,,,0.8755,3,True,0.1216,0.0529

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.004
Valid: True
Changes:
  bmi: 18.9866 → 16.7643

--- cf_4 ---
Predicted risk: 0.0045
Valid: True
Changes:
  cgtsmok: 3 → 6
  bmi: 18.9866 → 17.913

--- cf_6 ---
Predicted risk: 0.0095
Valid: True
Changes:
  etfruit: 4 → 3
  bmi: 18.9866 → 16.4122

--- cf_7 ---
Predicted risk: 0.0007
Valid: True
Changes:
  bmi: 18.9866 → 16.0235
  dosprt: 0 → 5

--- cf_9 ---
Predicted risk: 0.0038
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7

--- cf_10 ---
Predicted risk: 0.0117
Valid: True
Changes:
  etfruit: 4 → 3
  bmi: 18.9866 → 18.9619
  dosprt: 0 → 3


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0534
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 1

--- cf_4 ---
Predicted risk: 0.0851
Valid: True
Changes:
  cgtsmok: 1 → 2
  slprl: 3 → 1

--- cf_5 ---
Predicted risk: 0.0691
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1

--- cf_6 ---
Predicted risk: 0.1213
Valid: True
Changes:
  eatveg: 4 → 3
  dosprt: 0 → 6

--- cf_7 ---
Predicted risk: 0.0361
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_8 ---
Predicted risk: 0.036
Valid: True
Changes:
  etfruit: 3 → 1
  eatveg: 4 → 2
  alcfreq: 2 → 6


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0217
Valid: True
Changes:
  alcfreq: 1 → 4
  slprl: 4 → 1
  bmi: 22.694 → 22.68

--- cf_3 ---
Predicted risk: 0.0241
Valid: True
Changes:
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_4 ---
Predicted risk: 0.1018
Valid: True
Changes:
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.0426
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_6 ---
Predicted risk: 0.0108
Valid: True
Changes:
  bmi: 22.694 → 16.5946

--- cf_7 ---
Predicted risk: 0.0471
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.68

--- cf_8 ---
Predicted risk: 0.0719
Valid: True
Changes:
  etfruit: 5 → 3
  alcfreq: 1 → 2
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_9 ---
Predicted risk: 0.079
Valid: True
Changes:
  etfruit: 5 → 2
  alcfreq: 1 → 7
  slprl: 4 → 2
  bmi: 22.694 → 22.68


=== Query index '3' ===
No recommendations available.

=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0141
Valid: True
No feature changes.

--- cf_2 ---
Predicted risk: 0.0327
Valid: True
Changes:
  cgtsmok: 2 → 6

--- cf_3 ---
Predicted risk: 0.0143
Valid: True
Changes:
  cgtsmok: 2 → 3

--- cf_4 ---
Predicted risk: 0.005
Valid: True
Changes:
  cgtsmok: 2 → 5

--- cf_5 ---
Predicted risk: 0.0113
Valid: True
Changes:
  etfruit: 5 → 3

--- cf_6 ---
Predicted risk: 0.016
Valid: True
Changes:
  eatveg: 4 → 3

--- cf_7 ---
Predicted risk: 0.0081
Valid: True
Changes:
  etfruit: 5 → 4

--- cf_8 ---
Predicted risk: 0.0133
Valid: True
Changes:
  eatveg: 4 → 1

--- cf_9 ---
Predicted risk: 0.0199
Valid: True
Changes:
  eatveg: 4 → 2
  cgtsmok: 2 → 4


=== Query index '5' ===
No recommendations available.

=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0141
Valid: True
Changes:
  bmi: 27.6817 → 27.1147

--- cf_4 ---
Predicted risk: 0.0224
Valid: True
Changes:
  bmi: 27.6817 → 26.5459

--- cf_7 ---
Predicted risk: 0.0193
Valid: True
Changes:
  eatveg: 3 → 2
  bmi: 27.6817 → 26.9549

--- cf_10 ---
Predicted risk: 0.0188
Valid: True
Changes:
  bmi: 27.6817 → 26.8145
  dosprt: 4 → 7


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0083
Valid: True
Changes:
  bmi: 20.4382 → 19.7788

--- cf_4 ---
Predicted risk: 0.0023
Valid: True
Changes:
  bmi: 20.4382 → 19.5254

--- cf_5 ---
Predicted risk: 0.0029
Valid: True
Changes:
  bmi: 20.4382 → 19.463

--- cf_6 ---
Predicted risk: 0.0007
Valid: True
Changes:
  bmi: 20.4382 → 18.0

--- cf_7 ---
Predicted risk: 0.0003
Valid: True
Changes:
  bmi: 20.4382 → 17.856

--- cf_8 ---
Predicted risk: 0.0003
Valid: True
Changes:
  bmi: 20.4382 → 17.626

--- cf_9 ---
Predicted risk: 0.0003
Valid: True
Changes:
  bmi: 20.4382 → 17.451

--- cf_10 ---
Predicted risk: 0.0263
Valid: True
Changes:
  bmi: 20.4382 → 20.4353
  dosprt: 2 → 3


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0529
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.0146 → 26.0044

--- cf_2 ---
Predicted risk: 0.0413
Valid: True
Changes:
  etfruit: 6 → 1
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 6

--- cf_4 ---
Predicted risk: 0.0491
Valid: True
Changes:
  etfruit: 6 → 4
  alcfreq: 1 → 6
  bmi: 26.0146 → 25.1346

--- cf_5 ---
Predicted risk: 0.0231
Valid: True
Changes:
  etfruit: 6 → 1
  cgtsmok: 1 → 6
  bmi: 26.0146 → 24.811

--- cf_6 ---
Predicted risk: 0.0532
Valid: True
Changes:
  alcfreq: 1 → 5
  bmi: 26.0146 → 23.2979
  dosprt: 0 → 1

--- cf_8 ---
Predicted risk: 0.0579
Valid: True
Changes:
  etfruit: 6 → 2
  cgtsmok: 1 → 3
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 6


=== Query index '9' ===
No recommendations available.