In [22]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [23]:
batch_cfcheck_data = CF_OUTPUTS / "base_vs_thresholds" / "base_rf_midthres_2026-05-05" / "annotated.csv"
batch_cfcheck_df = pd.read_csv(batch_cfcheck_data)

In [24]:
pd.set_option("display.max_rows", None)

In [25]:
batch_cfcheck_df = batch_cfcheck_df.drop(columns=["hltprhc", "target_risk"])

In [26]:

batch_cfcheck_df["cf_id"] = batch_cfcheck_df["cf_id"].replace({"original": "xin"})

batch_cfcheck_df = batch_cfcheck_df.rename(columns={
    "original_risk": "risk_before",
    "predicted_risk" : "predicted_risk_after",
    "meets_target_risk" : "valid",
})

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,NaN,0.0633,NaN,2.39,NaN
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.695790,NaN,False,0.0633,0.0600,NaN,0.8883
2,0,cf_1,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,NaN,False,0.0633,0.0700,NaN,0.8756
3,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,16.247400,5.0,False,0.0633,0.0967,NaN,1.0000

In [27]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

batch_cfcheck_df = fix_cf_id(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,NaN,0.0633,NaN,2.39,NaN
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.695790,NaN,False,0.0633,0.0600,NaN,0.8883
2,0,cf_2,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,NaN,False,0.0633,0.0700,NaN,0.8756
3,0,cf_3,NaN,NaN,NaN,NaN,NaN,NaN,16.247400,5.0,False,0.0633,0.0967,NaN,1.0000
4,0,cf_4,NaN,NaN,6.0,7.0,NaN,NaN,18.974530,NaN,False,0.0633,0.0933,NaN,0.8756
5,0,cf_5,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,7.0,True,0.0633,0.0300,NaN,0.8756
6,0,cf_6,NaN,NaN,5.0,NaN,NaN,NaN,18.961930,2.0,True,0.0633,0.0267,NaN,0.8761
7,0,cf_7,1.0,1.0,NaN,NaN,NaN,NaN,18.961930,NaN,False,0.0633,0.1200,NaN,0.8761
8,0,cf_8,NaN,2.0,NaN,NaN,NaN,NaN,18.961930,7.0,False,0.0633,0.0700,NaN,0.8761
9,0,cf_9,1.0,2.0,NaN,NaN,NaN,NaN,18.961930,NaN,False,0.0633,0.1533,NaN,0.8761
10,0,cf_10,3.0,NaN,NaN,NaN,NaN,NaN,18.961930,3.0,True,0.0633,0.0167,NaN,0.8761
11,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.375680,0.0,NaN,0.1467,NaN,2.46,NaN
12,1,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,22.375680,NaN,False,0.1467,0.1467,NaN,0.8796
13,1,cf_2,NaN,NaN,4.0,NaN,NaN,NaN,22.375680,4.0,False,0.1467,0.1300,NaN,0.8796
14,1,cf_3,NaN,NaN,NaN,7.0,NaN,NaN,22.375680,7.0,False,0.1467,0.0767,NaN,0.8796
15,1,cf_4,NaN,NaN,NaN,3.0,1.0,NaN,22.375680,NaN,True,0.1467,0.0000,NaN,0.8796
16,1,cf_5,NaN,NaN,NaN,NaN,2.0,NaN,22.375680,7.0,False,0.1467,0.0900,NaN,0.8796
17,1,cf_6,NaN,NaN,NaN,NaN,1.0,NaN,22.375680,1.0,True,0.1467,0.0500,NaN,0.8796
18,1,cf_7,NaN,3.0,NaN,NaN,NaN,NaN,22.375680,6.0,False,0.1467,0.1667,NaN,0.8796
19,1,cf_8,2.0,NaN,NaN,NaN,1.0,NaN,22.375680,NaN,True,0.1467,0.0100,NaN,0.8796
20,1,cf_9,NaN,NaN,2.0,NaN,1.0,NaN,22.375680,NaN,True,0.1467,0.0233,NaN,0.8796
21,1,cf_10,NaN,3.0,2.0,NaN,NaN,NaN,22.375680,1.0,False,0.1467,0.1200,NaN,0.8796
22,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.694019,7.0,NaN,0.1567,NaN,2.64,NaN
23,2,cf_1,NaN,NaN,NaN,NaN,2.0,NaN,22.675740,NaN,False,0.1567,0.1067,NaN,0.8754
24,2,cf_2,NaN,NaN,NaN,NaN,NaN,NaN,16.804490,NaN,False,0.1567,0.2100,NaN,1.0000
25,2,cf_3,1.0,NaN,4.0,NaN,NaN,NaN,22.679950,NaN,False,0.1567,0.2933,NaN,0.8753
26,2,cf_4,3.0,NaN,NaN,NaN,2.0,NaN,22.679950,NaN,True,0.1567,0.0133,NaN,0.8753
27,2,cf_5,NaN,NaN,NaN,3.0,2.0,NaN,22.675740,NaN,False,0.1567,0.0867,NaN,0.8754
28,2,cf_6,1.0,NaN,NaN,2.0,NaN,NaN,22.675740,NaN,False,0.1567,0.0900,NaN,0.8754
29,2,cf_7,1.0,NaN,NaN,6.0,NaN,NaN,22.675740,NaN,False,0.1567,0.1400,NaN,0.8754

In [28]:
# round BMI to 2 decimal places, and set to NaN if equal to xin after rounding
def round_and_clear_bmi(df):
    df = df.copy()

    # Round BMI to 2 decimals for all rows
    df['bmi'] = df['bmi'].round(2)

    # For each query_index, get the xin BMI and compare
    for query_idx in df['query_index'].unique():
        query_mask = df['query_index'] == query_idx
        xin_mask = query_mask & (df['cf_id'] == 'xin')
        cf_mask = query_mask & (df['cf_id'] != 'xin')

        # Get the xin BMI value for this query
        xin_bmi = df.loc[xin_mask, 'bmi'].values[0]

        # Set cf BMI to NaN where it equals xin BMI
        equal_mask = cf_mask & (df['bmi'] == xin_bmi)
        df.loc[equal_mask, 'bmi'] = np.nan

    return df

batch_cfcheck_df = round_and_clear_bmi(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.99,0.0,NaN,0.0633,NaN,2.39,NaN
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.70,NaN,False,0.0633,0.0600,NaN,0.8883
2,0,cf_2,NaN,NaN,NaN,7.0,NaN,NaN,18.97,NaN,False,0.0633,0.0700,NaN,0.8756
3,0,cf_3,NaN,NaN,NaN,NaN,NaN,NaN,16.25,5.0,False,0.0633,0.0967,NaN,1.0000
4,0,cf_4,NaN,NaN,6.0,7.0,NaN,NaN,18.97,NaN,False,0.0633,0.0933,NaN,0.8756
5,0,cf_5,NaN,NaN,NaN,7.0,NaN,NaN,18.97,7.0,True,0.0633,0.0300,NaN,0.8756
6,0,cf_6,NaN,NaN,5.0,NaN,NaN,NaN,18.96,2.0,True,0.0633,0.0267,NaN,0.8761
7,0,cf_7,1.0,1.0,NaN,NaN,NaN,NaN,18.96,NaN,False,0.0633,0.1200,NaN,0.8761
8,0,cf_8,NaN,2.0,NaN,NaN,NaN,NaN,18.96,7.0,False,0.0633,0.0700,NaN,0.8761
9,0,cf_9,1.0,2.0,NaN,NaN,NaN,NaN,18.96,NaN,False,0.0633,0.1533,NaN,0.8761
10,0,cf_10,3.0,NaN,NaN,NaN,NaN,NaN,18.96,3.0,True,0.0633,0.0167,NaN,0.8761
11,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.38,0.0,NaN,0.1467,NaN,2.46,NaN
12,1,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,0.1467,0.1467,NaN,0.8796
13,1,cf_2,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,False,0.1467,0.1300,NaN,0.8796
14,1,cf_3,NaN,NaN,NaN,7.0,NaN,NaN,NaN,7.0,False,0.1467,0.0767,NaN,0.8796
15,1,cf_4,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,True,0.1467,0.0000,NaN,0.8796
16,1,cf_5,NaN,NaN,NaN,NaN,2.0,NaN,NaN,7.0,False,0.1467,0.0900,NaN,0.8796
17,1,cf_6,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,True,0.1467,0.0500,NaN,0.8796
18,1,cf_7,NaN,3.0,NaN,NaN,NaN,NaN,NaN,6.0,False,0.1467,0.1667,NaN,0.8796
19,1,cf_8,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,True,0.1467,0.0100,NaN,0.8796
20,1,cf_9,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,True,0.1467,0.0233,NaN,0.8796
21,1,cf_10,NaN,3.0,2.0,NaN,NaN,NaN,NaN,1.0,False,0.1467,0.1200,NaN,0.8796
22,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.69,7.0,NaN,0.1567,NaN,2.64,NaN
23,2,cf_1,NaN,NaN,NaN,NaN,2.0,NaN,22.68,NaN,False,0.1567,0.1067,NaN,0.8754
24,2,cf_2,NaN,NaN,NaN,NaN,NaN,NaN,16.80,NaN,False,0.1567,0.2100,NaN,1.0000
25,2,cf_3,1.0,NaN,4.0,NaN,NaN,NaN,22.68,NaN,False,0.1567,0.2933,NaN,0.8753
26,2,cf_4,3.0,NaN,NaN,NaN,2.0,NaN,22.68,NaN,True,0.1567,0.0133,NaN,0.8753
27,2,cf_5,NaN,NaN,NaN,3.0,2.0,NaN,22.68,NaN,False,0.1567,0.0867,NaN,0.8754
28,2,cf_6,1.0,NaN,NaN,2.0,NaN,NaN,22.68,NaN,False,0.1567,0.0900,NaN,0.8754
29,2,cf_7,1.0,NaN,NaN,6.0,NaN,NaN,22.68,NaN,False,0.1567,0.1400,NaN,0.8754

In [29]:
int_columns = [
    "etfruit",
    "eatveg",
    "cgtsmok",
    "alcfreq",
    "slprl",
    "paccnois",
    "dosprt",
]

float_columns = [
    "bmi",
    "risk_before",
    "predicted_risk_after",
]

In [30]:
batch_cfcheck_df[int_columns] = batch_cfcheck_df[int_columns].astype("Int64")

In [31]:
batch_cfcheck_df[float_columns] = batch_cfcheck_df[float_columns].round(2)

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4,3,3,4,2,0,18.99,0,NaN,0.06,NaN,2.39,NaN
1,0,cf_1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18.70,<NA>,False,0.06,0.06,NaN,0.8883
2,0,cf_2,<NA>,<NA>,<NA>,7,<NA>,<NA>,18.97,<NA>,False,0.06,0.07,NaN,0.8756
3,0,cf_3,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,16.25,5,False,0.06,0.10,NaN,1.0000

In [32]:
batch_cfcheck_df[int_columns] = (
    batch_cfcheck_df[int_columns]
    .astype("string")
    .fillna("")
)

In [33]:
batch_cfcheck_df = batch_cfcheck_df.replace({np.nan : ""})
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4,3,3,4,2,0,18.99,0,,0.06,,2.39,
1,0,cf_1,,,,,,,18.7,,False,0.06,0.06,,0.8883
2,0,cf_2,,,,7,,,18.97,,False,0.06,0.07,,0.8756
3,0,cf_3,,,,,,,16.25,5,False,0.06,0.1,,1.0

In [34]:
mask = batch_cfcheck_df["cf_id"] == "xin"
batch_cfcheck_df.loc[mask, "risk_before"] = ""
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance
0,0,xin,4,3,3,4,2,0,18.99,0,,,,2.39,
1,0,cf_1,,,,,,,18.7,,False,0.06,0.06,,0.8883
2,0,cf_2,,,,7,,,18.97,,False,0.06,0.07,,0.8756
3,0,cf_3,,,,,,,16.25,5,False,0.06,0.1,,1.0

In [35]:
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# 1. Beräkna Nchanged endast för CF-rader
mask_cf = batch_cfcheck_df["cf_id"] != "xin"

batch_cfcheck_df.loc[mask_cf, "Nchanged"] = (
    batch_cfcheck_df.loc[mask_cf, feature_cols] != ""
).sum(axis=1)

# 2. Konvertera kolumnen till ren string
batch_cfcheck_df["Nchanged"] = batch_cfcheck_df["Nchanged"].astype("string")

# 3. Baseline ska vara tom
batch_cfcheck_df.loc[batch_cfcheck_df["cf_id"] == "xin", "Nchanged"] = ""

In [36]:
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,valid,risk_before,predicted_risk_after,cf_gen_time_sec,gower_distance,Nchanged
0,0,xin,4,3,3,4,2,0,18.99,0,,,,2.39,,
1,0,cf_1,,,,,,,18.7,,False,0.06,0.06,,0.8883,1
2,0,cf_2,,,,7,,,18.97,,False,0.06,0.07,,0.8756,2
3,0,cf_3,,,,,,,16.25,5,False,0.06,0.1,,1.0,2

In [37]:
batch_cfcheck_df["Expected"] = ""

In [38]:
order = ["query_index", "cf_id"] + feature_cols + ["cf_gen_time_sec", "gower_distance", "Nchanged", "valid", "risk_before", "predicted_risk_after", "Expected"]

batch_cfcheck_df = batch_cfcheck_df[order]
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.39,,,,,,
1,0,cf_1,,,,,,,18.7,,,0.8883,1,False,0.06,0.06,
2,0,cf_2,,,,7,,,18.97,,,0.8756,2,False,0.06,0.07,
3,0,cf_3,,,,,,,16.25,5,,1.0,2,False,0.06,0.1,
4,0,cf_4,,,6,7,,,18.97,,,0.8756,3,False,0.06,0.09,
5,0,cf_5,,,,7,,,18.97,7,,0.8756,3,True,0.06,0.03,
6,0,cf_6,,,5,,,,18.96,2,,0.8761,3,True,0.06,0.03,
7,0,cf_7,1,1,,,,,18.96,,,0.8761,3,False,0.06,0.12,
8,0,cf_8,,2,,,,,18.96,7,,0.8761,3,False,0.06,0.07,
9,0,cf_9,1,2,,,,,18.96,,,0.8761,3,False,0.06,0.15,
10,0,cf_10,3,,,,,,18.96,3,,0.8761,3,True,0.06,0.02,
11,1,xin,3,4,1,2,3,0,22.38,0,2.46,,,,,,
12,1,cf_1,,,,,,,,,,0.8796,0,False,0.15,0.15,
13,1,cf_2,,,4,,,,,4,,0.8796,2,False,0.15,0.13,
14,1,cf_3,,,,7,,,,7,,0.8796,2,False,0.15,0.08,
15,1,cf_4,,,,3,1,,,,,0.8796,2,True,0.15,0.0,
16,1,cf_5,,,,,2,,,7,,0.8796,2,False,0.15,0.09,
17,1,cf_6,,,,,1,,,1,,0.8796,2,True,0.15,0.05,
18,1,cf_7,,3,,,,,,6,,0.8796,2,False,0.15,0.17,
19,1,cf_8,2,,,,1,,,,,0.8796,2,True,0.15,0.01,
20,1,cf_9,,,2,,1,,,,,0.8796,2,True,0.15,0.02,
21,1,cf_10,,3,2,,,,,1,,0.8796,3,False,0.15,0.12,
22,2,xin,5,3,1,1,4,0,22.69,7,2.64,,,,,,
23,2,cf_1,,,,,2,,22.68,,,0.8754,2,False,0.16,0.11,
24,2,cf_2,,,,,,,16.8,,,1.0,1,False,0.16,0.21,
25,2,cf_3,1,,4,,,,22.68,,,0.8753,3,False,0.16,0.29,
26,2,cf_4,3,,,,2,,22.68,,,0.8753,3,True,0.16,0.01,
27,2,cf_5,,,,3,2,,22.68,,,0.8754,3,False,0.16,0.09,
28,2,cf_6,1,,,2,,,22.68,,,0.8754,3,False,0.16,0.09,
29,2,cf_7,1,,,6,,,22.68,,,0.8754,3,False,0.16,0.14,
30,2,cf_8,2,,,,3,,22.68,,,0.8754,3,False,0.16,0.16,
31,2,cf_9,2,,4,,,,22.68,,,0.8754,3,False,0.16,0.21,
32,2,cf_10,1,,,7,,,22.68,,,0.8754,3,False,0.16,0.2,
33,3,xin,3,3,6,6,2,0,24.34,1,2.74,,,,,,
34,3,cf_1,,,,,,,,,,0.8753,0,True,0.02,0.01,
35,3,cf_2,,,,,,,23.15,,,0.9494,1,False,0.02,0.1,
36,3,cf_3,,,,,,,22.34,,,1.0,1,False,0.02,0.2,
37,3,cf_4,,,,7,,,,,,0.8753,1,False,0.02,0.03,
38,3,cf_5,,,,,,,,5,,0.8753,1,False,0.02,0.23,
39,3,cf_6,,,,,,,,4,,0.8753,1,False,0.02,0.02,
40,3,cf_7,,,,,,,,3,,0.8753,1,True,0.02,0.0,
41,3,cf_8,,,,,,,,2,,0.8753,1,True,0.02,0.0,
42,3,cf_9,,,,,1,,,,,0.8753,1,False,0.02,0.29,
43,3,cf_10,,,,,,,,7,,0.8753,1,False,0.02,0.38,
44,4,xin,5,4,2,7,1,0,21.26,3,2.85,,,,,,
45,4,cf_1,,,,,,,,,,0.9868,0,False,0.03,0.03,
46,4,cf_2,,,5,,,,,,,0.9868,1,True,0.03,0.01,
47,4,cf_3,,,3,,,,,,,0.9868,1,True,0.03,0.01,
48,4,cf_4,,3,,,,,,,,0.9868,1,True,0.03,0.01,
49,4,cf_5,,,6,,,,,,,0.9868,1,True,0.03,0.0,
50,4,cf_6,4,,,,,,,,,0.9868,1,False,0.03,0.03,
51,4,cf_7,3,,,,,,,,,0.9868,1,False,0.03,0.05,
52,4,cf_8,,,6,,,,,5,,0.9868,2,True,0.03,0.0,
53,4,cf_9,2,1,,,,,,,,0.9868,2,False,0.03,0.05,
54,4,cf_10,1,2,,,,,,,,0.9868,2,False,0.03,0.03,
55,5,xin,2,2,1,2,4,0,27.99,0,2.6,,,,,,
56,5,cf_1,,,,,,,,,,1.0857,0,False,0.33,0.33,
57,5,cf_2,,,4,,,,,,,1.0857,1,False,0.33,0.45,
58,5,cf_3,,,3,,,,,,,1.0857,1,False,0.33,0.35,
59,5,cf_4,,,2,,,,,,,1.0857,1,False,0.33,0.32,
60,5,cf_5,,,,,1,,,,,1.0857,1,True,0.33,0.08,
61,5,cf_6,,,2,6,,,,,,1.0857,2,False,0.33,0.31,
62,5,cf_7,,,2,5,,,,,,1.0857,2,False,0.33,0.28,
63,5,cf_8,,,,7,,,,7,,1.0857,2,True,0.33,0.13,
64,5,cf_9,,,,6,1,,,,,1.0857,2,True,0.33,0.12,
65,5,cf_10,,,,5,1,,,,,1.0857,2,True,0.33,0.03,
66,6,xin,2,3,5,4,1,0,27.68,4,2.34,,,,,,
67,6,cf_1,,,,,,,27.61,,,0.8773,1,False,0.15,0.22,
68,6,cf_2,,,,,,,25.85,,,0.938,1,False,0.15,0.12,
69,6,cf_3,,,,,,,25.78,,,0.9402,1,False,0.15,0.08,
70,6,cf_4,,,,,,,25.7,,,0.9429,1,False,0.15,0.08,
71,6,cf_5,,,,,,,25.7,,,0.9431,1,False,0.15,0.08,
72,6,cf_6,,,,,,,25.52,,,0.9493,1,True,0.15,0.07,
73,6,cf_7,,,,,,,24.46,,,0.9854,1,False,0.15,0.12,
74,6,cf_8,,,6,,,,27.29,,,0.8885,2,False,0.15,0.12,
75,6,cf_9,,,,,,,24.07,,,0.9988,1,True,0.15,0.01,
76,6,cf_10,,,,,,,24.04,,,1.0,1,True,0.15,0.01,
77,7,xin,2,3,6,3,1,0,20.44,2,2.34,,,,,,
78,7,cf_1,,,,,,,20.43,,,0.8754,1,False,0.01,0.02,
79,7,cf_2,,,,,,,19.54,,,0.9131,1,True,0.01,0.0,
80,7,cf_3,,,,,,,18.52,,,0.9564,1,False,0.01,0.01,
81,7,cf_4,,,,,,,17.61,,,0.9952,1,True,0.01,0.0,
82,7,cf_5,,,,,,,17.5,,,0.9996,1,True,0.01,0.0,
83,7,cf_6,,,,,,,17.49,,,1.0,1,True,0.01,0.0,
84,7,cf_7,,,,7,,,20.43,,,0.8754,2,False,0.01,0.01,
85,7,cf_8,,,,4,,,20.43,,,0.8754,2,False,0.01,0.06,
86,7,cf_9,,,,,,,20.43,5,,0.8754,2,False,0.01,0.01,
87,7,cf_10,,,,6,,,20.43,,,0.8754,2,False,0.01,0.03,
88,8,xin,6,4,1,1,1,0,26.01,0,2.42,,,,,,
89,8,cf_1,,,6,7,,,26.0,,,0.8752,3,False,0.09,0.18,
90,8,cf_2,3,,,5,,,26.0,,,0.8752,3,True,0.09,0.04,
91,8,cf_3,2,,,2,,,26.0,,,0.8752,3,False,0.09,0.06,
92,8,cf_4,,,,,,,19.29,,,1.0,1,False,0.09,0.08,
93,8,cf_5,3,,,,,,25.25,7,,0.8892,3,True,0.09,0.03,
94,8,cf_6,1,3,,,,,24.76,,,0.8982,3,False,0.09,0.05,
95,8,cf_7,1,1,,,,,24.76,,,0.8982,3,False,0.09,0.05,
96,8,cf_8,1,1,6,,,,26.0,,,0.8752,4,False,0.09,0.12,
97,8,cf_9,4,,,2,,,26.0,3,,0.8752,4,True,0.09,0.03,
98,8,cf_10,1,1,3,,,,26.0,,,0.8752,4,False,0.09,0.17,

# picking correct CF

### expected

In [39]:
# Check directional constraints directly
# These features should only improve (increase) or stay the same
SHOULD_INCREASE = ["cgtsmok", "alcfreq", "dosprt"]

# These features should only improve (decrease) or stay the same
SHOULD_DECREASE = ["bmi", "etfruit", "eatveg", "slprl", "paccnois"]


print("Directional constraints:")
print(f"  Should increase (↑): {SHOULD_INCREASE}")
print(f"  Should decrease (↓): {SHOULD_DECREASE}")

Directional constraints:
  Should increase (↑): ['cgtsmok', 'alcfreq', 'dosprt']
  Should decrease (↓): ['bmi', 'etfruit', 'eatveg', 'slprl', 'paccnois']

In [40]:
# Check if CFs violate directional constraints
# First, ensure numeric columns are actually numeric for comparison
numeric_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# Create a working copy with numeric values
df_check = batch_cfcheck_df.copy()
for col in numeric_cols:
    df_check[col] = pd.to_numeric(df_check[col], errors="coerce")

# Extract baseline values per query_index
baseline_values = df_check[df_check["cf_id"] == "xin"].set_index("query_index")[numeric_cols]

# Check violations for each CF
def check_violations(row):
    if row["cf_id"] == "xin":
        return ""

    baseline = baseline_values.loc[row["query_index"]]
    violations = []

    # Check features that should increase
    for feat in SHOULD_INCREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] < baseline[feat]:
                violations.append(f"{feat}↓")

    # Check features that should decrease
    for feat in SHOULD_DECREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] > baseline[feat]:
                violations.append(f"{feat}↑")

    return "NO: " + ", ".join(violations) if violations else True

batch_cfcheck_df["Expected"] = df_check.apply(check_violations, axis=1)
batch_cfcheck_df.head(10)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.39,,,,,,
1,0,cf_1,,,,,,,18.7,,,0.8883,1,False,0.06,0.06,True
2,0,cf_2,,,,7,,,18.97,,,0.8756,2,False,0.06,0.07,True
3,0,cf_3,,,,,,,16.25,5,,1.0,2,False,0.06,0.1,True
4,0,cf_4,,,6,7,,,18.97,,,0.8756,3,False,0.06,0.09,True
5,0,cf_5,,,,7,,,18.97,7,,0.8756,3,True,0.06,0.03,True
6,0,cf_6,,,5,,,,18.96,2,,0.8761,3,True,0.06,0.03,True
7,0,cf_7,1,1,,,,,18.96,,,0.8761,3,False,0.06,0.12,True
8,0,cf_8,,2,,,,,18.96,7,,0.8761,3,False,0.06,0.07,True
9,0,cf_9,1,2,,,,,18.96,,,0.8761,3,False,0.06,0.15,True

### is valid

In [41]:
# --- Select exactly one CF per query_index (random valid without violations) ---

# Split baseline and CF rows
df_xin = batch_cfcheck_df[batch_cfcheck_df["cf_id"] == "xin"]
df_cf  = batch_cfcheck_df[batch_cfcheck_df["cf_id"] != "xin"]

def select_random_cf(group):
    """Select one random CF that is valid and has no violations (Expected is empty)."""
    # First try: valid AND no violations
    good_cfs = group[(group["valid"] == True) & (group["Expected"] == "")]
    if len(good_cfs) > 0:
        return good_cfs.sample(n=1, random_state=42)

    # Fallback: any valid CF
    valid_cfs = group[group["valid"] == True]
    if len(valid_cfs) > 0:
        return valid_cfs.sample(n=1, random_state=42)

    # Last resort: first CF
    return group.iloc[[0]]

# Select one random CF per query_index
df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

# Combine baseline + selected CF
batch_cfcheck_df = pd.concat([df_xin, df_cf_selected], ignore_index=True)

# Ensure xin appears before CF for each query_index
batch_cfcheck_df["is_xin"] = (batch_cfcheck_df["cf_id"] == "xin").astype(int)
batch_cfcheck_df = (
    batch_cfcheck_df
    .sort_values(["query_index", "is_xin"], ascending=[True, False])
    .drop(columns="is_xin")
)
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.39,,,,,,
9,0,cf_5,,,,7,,,18.97,7,,0.8756,3,True,0.06,0.03,True
1,1,xin,3,4,1,2,3,0,22.38,0,2.46,,,,,,
10,1,cf_6,,,,,1,,,1,,0.8796,2,True,0.15,0.05,True
2,2,xin,5,3,1,1,4,0,22.69,7,2.64,,,,,,
11,2,cf_4,3,,,,2,,22.68,,,0.8753,3,True,0.16,0.01,True
3,3,xin,3,3,6,6,2,0,24.34,1,2.74,,,,,,
12,3,cf_1,,,,,,,,,,0.8753,0,True,0.02,0.01,True
4,4,xin,5,4,2,7,1,0,21.26,3,2.85,,,,,,
13,4,cf_3,,,3,,,,,,,0.9868,1,True,0.03,0.01,True
5,5,xin,2,2,1,2,4,0,27.99,0,2.6,,,,,,
14,5,cf_8,,,,7,,,,7,,1.0857,2,True,0.33,0.13,True
6,6,xin,2,3,5,4,1,0,27.68,4,2.34,,,,,,
15,6,cf_6,,,,,,,25.52,,,0.9493,1,True,0.15,0.07,True
7,7,xin,2,3,6,3,1,0,20.44,2,2.34,,,,,,
16,7,cf_4,,,,,,,17.61,,,0.9952,1,True,0.01,0.0,True
8,8,xin,6,4,1,1,1,0,26.01,0,2.42,,,,,,
17,8,cf_2,3,,,5,,,26.0,,,0.8752,3,True,0.09,0.04,True

In [42]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_cfcheck_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.99
  dosprt: 0


=== Counterfactuals ===

--- cf_5 ---
Predicted risk: 0.03
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.99 → 18.97
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.38
  dosprt: 0


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.05
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.69
  dosprt: 7


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.01
Valid: True
Changes:
  etfruit: 5 → 3
  slprl: 4 → 2
  bmi: 22.69 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.34
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.01
Valid: True
No feature changes.


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.26
  dosprt: 3


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.01
Valid: True
Changes:
  cgtsmok: 2 → 3


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.99
  dosprt: 0


=== Counterfactuals ===

--- cf_8 ---
Predicted risk: 0.13
Valid: True
Changes:
  alcfreq: 2 → 7
  dosprt: 0 → 7


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.68
  dosprt: 4


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.07
Valid: True
Changes:
  bmi: 27.68 → 25.52


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.44
  dosprt: 2


=== Counterfactuals ===

--- cf_4 ---
Valid: True
Changes:
  bmi: 20.44 → 17.61


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.01
  dosprt: 0


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.04
Valid: True
Changes:
  etfruit: 6 → 3
  alcfreq: 1 → 5
  bmi: 26.01 → 26.0


=== Query index '9' ===
No recommendations available.