In [7]:
import pandas as pd
import numpy as np

In [3]:
from aiwhatif_cf.config import DATA_DIR, CF_OUTPUTS

BALANCED_DIR = CF_OUTPUTS / "balanced_04_09"
UNBALANCED_DIR = CF_OUTPUTS / "unbalanced_04_09"
print(BALANCED_DIR.is_dir())
print(UNBALANCED_DIR.is_dir())

balanced_random =  BALANCED_DIR / "random_hltprhc_2026-04-09" / "random_annotated_hltprhc.csv"
unbalanced_random = UNBALANCED_DIR / "random_hltprhc_2026-04-09" / "random_annotated_hltprhc.csv"

balanced_random_df = pd.read_csv(balanced_random)
unbalanced_random_df = pd.read_csv(unbalanced_random)

True
True

In [14]:
pd.set_option("display.max_rows", None)

In [ ]:
def clean_counterfactuals(df):
    cleaned = df.copy()


    ignore_cols = ["query_index", "cf_id", "original_risk", "target_risk",
                   "predicted_risk", "meets_target_risk"]
    feature_cols = [c for c in df.columns if c not in ignore_cols]

    # Loop per query_index
    for q in df["query_index"].unique():
        block = df[df["query_index"] == q]

        # get originalrow
        orig = block[block["cf_id"] == "original"].iloc[0]

        # compare every cf-row with original
        for idx, row in block.iterrows():
            if row["cf_id"] != "original":
                for col in feature_cols:
                    if row[col] == orig[col]:
                        cleaned.at[idx, col] = np.nan

    return cleaned

In [8]:
balanced_random_df = clean_counterfactuals(balanced_random_df)
unbalanced_random_df = clean_counterfactuals(unbalanced_random_df)

# random models

### unbalanced data, Random model

In [12]:
unbalanced_random_df.replace({np.nan : ""})

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,gndr,dosprt,hltprhc,original_risk,target_risk,predicted_risk,meets_target_risk
0,8,original,3.0,2.0,4.0,6.0,2.0,0.0,30.062102,2.0,7.0,,0.133913,0.066956,,
1,8,cf_1,,,,,,,19.827835,,,0.0,0.133913,0.066956,0.086773,False
2,8,cf_2,,,,7.0,,,,,,0.0,0.133913,0.066956,0.189111,False
3,8,cf_3,,,,2.0,,,21.532943,,,0.0,0.133913,0.066956,0.029792,True
4,14,original,1.0,1.0,4.0,3.0,3.0,0.0,26.827421,2.0,7.0,,0.180454,0.090227,,
5,14,cf_1,,,,,,,19.827835,,,0.0,0.180454,0.090227,0.079239,True
6,14,cf_2,3.0,,,7.0,,,,,,0.0,0.180454,0.090227,0.235375,False
7,14,cf_3,,,,2.0,,,21.532943,,,0.0,0.180454,0.090227,0.067447,True
8,18,original,3.0,3.0,6.0,6.0,2.0,1.0,31.229454,2.0,0.0,,0.203730,0.101865,,
9,18,cf_1,,,,,,,19.827835,,,0.0,0.203730,0.101865,0.075667,True
10,18,cf_2,,,,7.0,,,,,,0.0,0.203730,0.101865,0.228269,False
11,18,cf_3,,,,2.0,,,21.532943,,,0.0,0.203730,0.101865,0.127539,False
12,38,original,3.0,3.0,6.0,2.0,1.0,0.0,33.470508,1.0,7.0,,0.043532,0.021766,,
13,38,cf_1,,,,,,,19.827835,,,0.0,0.043532,0.021766,0.076204,False
14,38,cf_2,,,,7.0,,,,,,0.0,0.043532,0.021766,0.047052,False
15,38,cf_3,,,,,,,21.532943,,,0.0,0.043532,0.021766,0.038418,False
16,43,original,2.0,4.0,3.0,7.0,2.0,0.0,29.352355,2.0,2.0,,0.236484,0.118242,,
17,43,cf_1,,,,,,,19.827835,,,0.0,0.236484,0.118242,0.053668,True
18,43,cf_2,3.0,,,,,,,,,0.0,0.236484,0.118242,0.223752,False
19,43,cf_3,,,,2.0,,,21.532943,,,0.0,0.236484,0.118242,0.04837,True
20,52,original,3.0,3.0,6.0,7.0,1.0,0.0,19.814053,2.0,1.0,,0.065827,0.032914,,
21,52,cf_1,,,,,,,19.827835,,,0.0,0.065827,0.032914,0.067266,False
22,52,cf_2,,,,,,,,,,0.0,0.065827,0.032914,0.065827,False
23,52,cf_3,,,,2.0,,,21.532943,,,0.0,0.065827,0.032914,0.03748,False
24,67,original,4.0,5.0,1.0,7.0,3.0,1.0,39.197531,1.0,0.0,,0.228561,0.114281,,
25,67,cf_1,,7.0,,1.0,,,,,,0.0,0.228561,0.114281,0.252446,False
26,67,cf_2,,,,,,,24.632284,,,0.0,0.228561,0.114281,0.251962,False
27,67,cf_3,,,,,1.0,,,,3.0,0.0,0.228561,0.114281,0.171307,False
28,94,original,2.0,2.0,6.0,7.0,3.0,0.0,24.913495,1.0,0.0,,0.175727,0.087863,,
29,94,cf_1,,,,,,,19.827835,,,0.0,0.175727,0.087863,0.189322,False
30,94,cf_2,3.0,,,,,,,,,0.0,0.175727,0.087863,0.277141,False
31,94,cf_3,,,,2.0,,,21.532943,,,0.0,0.175727,0.087863,0.174312,False
32,97,original,2.0,7.0,1.0,6.0,2.0,0.0,23.665244,1.0,0.0,,0.156362,0.078181,,
33,97,cf_1,,,,,,,19.827835,,,0.0,0.156362,0.078181,0.183019,False
34,97,cf_2,3.0,,,7.0,,,,,,0.0,0.156362,0.078181,0.174584,False
35,97,cf_3,,,,2.0,,,21.532943,,,0.0,0.156362,0.078181,0.129603,False
36,106,original,3.0,3.0,4.0,7.0,1.0,0.0,31.644286,2.0,0.0,,0.248133,0.124066,,
37,106,cf_1,,,,,,,19.827835,,,0.0,0.248133,0.124066,0.163657,False
38,106,cf_2,,,,,,,,,,0.0,0.248133,0.124066,0.248133,False
39,106,cf_3,,,,2.0,,,21.532943,,,0.0,0.248133,0.124066,0.132712,False
40,112,original,3.0,4.0,6.0,7.0,4.0,0.0,26.77551,2.0,0.0,,0.383193,0.191597,,
41,112,cf_1,,1.0,,,,,,,,0.0,0.383193,0.191597,0.35336,False
42,112,cf_2,,,,,,,17.264523,,,0.0,0.383193,0.191597,0.439749,False
43,112,cf_3,,,,5.0,,,31.069883,,,0.0,0.383193,0.191597,0.306385,False
44,127,original,3.0,3.0,6.0,7.0,3.0,0.0,32.629352,2.0,7.0,,0.213844,0.106922,,
45,127,cf_1,,,,,,,19.827835,,,0.0,0.213844,0.106922,0.07396,True
46,127,cf_2,,,,,,,,,,0.0,0.213844,0.106922,0.213844,False
47,127,cf_3,,,,2.0,,,21.532943,,,0.0,0.213844,0.106922,0.317141,False
48,135,original,3.0,3.0,6.0,7.0,1.0,0.0,35.996327,2.0,0.0,,0.275623,0.137812,,
49,135,cf_1,,7.0,,1.0,,,,,,0.0,0.275623,0.137812,0.187867,False
50,135,cf_2,,2.0,,,2.0,,,,,0.0,0.275623,0.137812,0.405319,False
51,135,cf_3,,,,,,,,,,0.0,0.275623,0.137812,0.275623,False
52,138,original,3.0,4.0,6.0,7.0,4.0,0.0,19.591837,1.0,0.0,,0.399530,0.199765,,
53,138,cf_1,,,,,,,27.191653,,,0.0,0.399530,0.199765,0.285817,False
54,138,cf_2,,,4.0,,,,,,,0.0,0.399530,0.199765,0.453446,False
55,138,cf_3,,6.0,,,,,17.094141,,,0.0,0.399530,0.199765,0.350158,False
56,143,original,2.0,2.0,6.0,7.0,2.0,0.0,25.826446,1.0,0.0,,0.142929,0.071465,,
57,143,cf_1,,,,,,,19.827835,,,0.0,0.142929,0.071465,0.185608,False
58,143,cf_2,3.0,,,,,,,,,0.0,0.142929,0.071465,0.079253,False
59,143,cf_3,,,,2.0,,,21.532943,,,0.0,0.142929,0.071465,0.203653,False
60,146,original,4.0,3.0,4.0,2.0,2.0,0.0,30.991736,1.0,7.0,,0.085930,0.042965,,
61,146,cf_1,,,,,,,19.827835,,,0.0,0.085930,0.042965,0.143083,False
62,146,cf_2,3.0,,,7.0,,,,,,0.0,0.085930,0.042965,0.258595,False
63,146,cf_3,,,,,,,21.532943,,,0.0,0.085930,0.042965,0.118292,False
64,149,original,4.0,4.0,4.0,4.0,4.0,1.0,30.367347,1.0,2.0,,0.182266,0.091133,,
65,149,cf_1,,,,,,,19.827835,,,0.0,0.182266,0.091133,0.070928,True
66,149,cf_2,3.0,,,7.0,,,,,,0.0,0.182266,0.091133,0.249101,False
67,149,cf_3,,,,2.0,,,21.532943,,,0.0,0.182266,0.091133,0.073547,True
68,151,original,3.0,3.0,4.0,2.0,1.0,0.0,25.97868,1.0,3.0,,0.083354,0.041677,,
69,151,cf_1,,,,,,,19.827835,,,0.0,0.083354,0.041677,0.051506,False
70,151,cf_2,,,,7.0,,,,,,0.0,0.083354,0.041677,0.050821,False
71,151,cf_3,,,,,,,21.532943,,,0.0,0.083354,0.041677,0.019675,True
72,152,original,2.0,3.0,6.0,2.0,1.0,0.0,23.4375,1.0,5.0,,0.093804,0.046902,,
73,152,cf_1,,,,,,,19.827835,,,0.0,0.093804,0.046902,0.042631,True
74,152,cf_2,3.0,,,7.0,,,,,,0.0,0.093804,0.046902,0.03805,True
75,152,cf_3,,,,,,,21.532943,,,0.0,0.093804,0.046902,0.023827,True
76,153,original,3.0,3.0,5.0,7.0,1.0,0.0,27.767098,2.0,1.0,,0.095451,0.047726,,
77,153,cf_1,,,,,,,19.827835,,,0.0,0.095451,0.047726,0.058441,False
78,153,cf_2,,,,,,,,,,0.0,0.095451,0.047726,0.095451,False
79,153,cf_3,,,,2.0,,,21.532943,,,0.0,0.095451,0.047726,0.043841,True

### balanced data, Random model

In [11]:
balanced_random_df.replace({np.nan : ""})

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,gndr,dosprt,hltprhc,original_risk,target_risk,predicted_risk,meets_target_risk
0,8,original,3.0,2.0,4.0,6.0,2.0,0.0,30.062102,2.0,7.0,,0.632361,0.316180,,
1,8,cf_1,,,,,,,24.487726,,,0.0,0.632361,0.316180,0.45816,False
2,8,cf_2,,,,,,,23.862233,,,0.0,0.632361,0.316180,0.375141,False
3,8,cf_3,,,,,1.0,,17.892181,,,0.0,0.632361,0.316180,0.345739,False
4,14,original,1.0,1.0,4.0,3.0,3.0,0.0,26.827421,2.0,7.0,,0.611948,0.305974,,
5,14,cf_1,,,,,,,18.50794,,,0.0,0.611948,0.305974,0.382674,False
6,14,cf_2,,,,,,,17.932328,,,0.0,0.611948,0.305974,0.396114,False
7,14,cf_3,,,,,,1.0,23.150188,,,0.0,0.611948,0.305974,0.482554,False
8,18,original,3.0,3.0,6.0,6.0,2.0,1.0,31.229454,2.0,0.0,,0.673858,0.336929,,
9,18,cf_1,,,,3.0,1.0,,,,,0.0,0.673858,0.336929,0.485257,False
10,18,cf_2,,,,,,,21.123097,,,0.0,0.673858,0.336929,0.404406,False
11,18,cf_3,,,,,,,23.938549,,,0.0,0.673858,0.336929,0.430095,False
12,38,original,3.0,3.0,6.0,2.0,1.0,0.0,33.470508,1.0,7.0,,0.365020,0.182510,,
13,38,cf_1,,,5.0,,,,23.224254,,,0.0,0.365020,0.182510,0.321074,False
14,38,cf_2,,4.0,,,,,23.263253,,,0.0,0.365020,0.182510,0.235004,False
15,38,cf_3,,7.0,,,,,37.403272,,,0.0,0.365020,0.182510,0.393717,False
16,43,original,2.0,4.0,3.0,7.0,2.0,0.0,29.352355,2.0,2.0,,0.635827,0.317913,,
17,43,cf_1,,,,,,,17.605399,,,0.0,0.635827,0.317913,0.268127,True
18,43,cf_2,,,,3.0,,,22.480924,,,0.0,0.635827,0.317913,0.240718,True
19,43,cf_3,,,,,,,25.19121,,,0.0,0.635827,0.317913,0.448337,False
20,52,original,3.0,3.0,6.0,7.0,1.0,0.0,19.814053,2.0,1.0,,0.340431,0.170216,,
21,52,cf_1,,,,3.0,,,,,,0.0,0.340431,0.170216,0.218202,False
22,52,cf_2,,,1.0,,,,38.136131,,,0.0,0.340431,0.170216,0.481669,False
23,52,cf_3,,1.0,,,,,,,,0.0,0.340431,0.170216,0.262565,False
24,67,original,4.0,5.0,1.0,7.0,3.0,1.0,39.197531,1.0,0.0,,0.711530,0.355765,,
25,67,cf_1,,,,,1.0,,,,,0.0,0.711530,0.355765,0.48623,False
26,67,cf_2,,,,,1.0,,36.862898,,,0.0,0.711530,0.355765,0.498272,False
27,67,cf_3,,,,,1.0,,,,,0.0,0.711530,0.355765,0.48623,False
28,94,original,2.0,2.0,6.0,7.0,3.0,0.0,24.913495,1.0,0.0,,0.676812,0.338406,,
29,94,cf_1,,,,4.0,,,24.528203,,,0.0,0.676812,0.338406,0.498545,False
30,94,cf_2,,,,,1.0,,,,,0.0,0.676812,0.338406,0.480309,False
31,94,cf_3,4.0,,,,,,,,3.0,0.0,0.676812,0.338406,0.457699,False
32,97,original,2.0,7.0,1.0,6.0,2.0,0.0,23.665244,1.0,0.0,,0.522425,0.261212,,
33,97,cf_1,,,,4.0,,,,,5.0,0.0,0.522425,0.261212,0.442611,False
34,97,cf_2,,1.0,,,,,,,,0.0,0.522425,0.261212,0.451541,False
35,97,cf_3,,,6.0,,,,22.224933,,,0.0,0.522425,0.261212,0.452239,False
36,106,original,3.0,3.0,4.0,7.0,1.0,0.0,31.644286,2.0,0.0,,0.743708,0.371854,,
37,106,cf_1,,4.0,,,,,,,3.0,0.0,0.743708,0.371854,0.448842,False
38,106,cf_2,,,,6.0,,,16.524418,,,0.0,0.743708,0.371854,0.451023,False
39,106,cf_3,,,,5.0,,,19.806271,,,0.0,0.743708,0.371854,0.460551,False
40,112,original,3.0,4.0,6.0,7.0,4.0,0.0,26.77551,2.0,0.0,,0.821600,0.410800,,
41,112,cf_1,,,,,1.0,,,,3.0,0.0,0.821600,0.410800,0.332167,True
42,112,cf_2,,,,,,,24.708138,,5.0,0.0,0.821600,0.410800,0.462211,False
43,112,cf_3,,,,4.0,,,16.461342,,,0.0,0.821600,0.410800,0.453136,False
44,127,original,3.0,3.0,6.0,7.0,3.0,0.0,32.629352,2.0,7.0,,0.663411,0.331705,,
45,127,cf_1,2.0,,,,,,22.725012,,,0.0,0.663411,0.331705,0.460902,False
46,127,cf_2,4.0,,,3.0,,,,,,0.0,0.663411,0.331705,0.466877,False
47,127,cf_3,4.0,,,,,,19.349091,,,0.0,0.663411,0.331705,0.468589,False
48,135,original,3.0,3.0,6.0,7.0,1.0,0.0,35.996327,2.0,0.0,,0.779000,0.389500,,
49,135,cf_1,,,,2.0,,,19.291393,,,0.0,0.779000,0.389500,0.31892,True
50,135,cf_2,,,3.0,,,,19.572277,,,0.0,0.779000,0.389500,0.494795,False
51,135,cf_3,4.0,,,,,,17.501181,,,0.0,0.779000,0.389500,0.468411,False
52,138,original,3.0,4.0,6.0,7.0,4.0,0.0,19.591837,1.0,0.0,,0.748888,0.374444,,
53,138,cf_1,,,,,,,,,6.0,0.0,0.748888,0.374444,0.494373,False
54,138,cf_2,,,,,,,,,3.0,0.0,0.748888,0.374444,0.477835,False
55,138,cf_3,,,,,,,20.49335,,5.0,0.0,0.748888,0.374444,0.468771,False
56,143,original,2.0,2.0,6.0,7.0,2.0,0.0,25.826446,1.0,0.0,,0.672496,0.336248,,
57,143,cf_1,,,,,,,21.356187,,6.0,0.0,0.672496,0.336248,0.409089,False
58,143,cf_2,,,,5.0,,,,,4.0,0.0,0.672496,0.336248,0.400117,False
59,143,cf_3,,,,2.0,,,,,,0.0,0.672496,0.336248,0.426477,False
60,146,original,4.0,3.0,4.0,2.0,2.0,0.0,30.991736,1.0,7.0,,0.535564,0.267782,,
61,146,cf_1,,,1.0,,,,,,,0.0,0.535564,0.267782,0.497826,False
62,146,cf_2,,,,,,,25.141732,,,0.0,0.535564,0.267782,0.483101,False
63,146,cf_3,,,,,3.0,,22.830909,,,0.0,0.535564,0.267782,0.381168,False
64,149,original,4.0,4.0,4.0,4.0,4.0,1.0,30.367347,1.0,2.0,,0.680025,0.340013,,
65,149,cf_1,,,,,,,19.291393,,,0.0,0.680025,0.340013,0.445056,False
66,149,cf_2,,,,,,,16.309363,,,0.0,0.680025,0.340013,0.449534,False
67,149,cf_3,,,6.0,,,,22.224933,,,0.0,0.680025,0.340013,0.438522,False
68,151,original,3.0,3.0,4.0,2.0,1.0,0.0,25.97868,1.0,3.0,,0.402481,0.201240,,
69,151,cf_1,,,,,,,21.532943,,,0.0,0.402481,0.201240,0.278805,False
70,151,cf_2,6.0,,,,,,25.739668,,,0.0,0.402481,0.201240,0.294245,False
71,151,cf_3,,,,,,,23.22441,,,0.0,0.402481,0.201240,0.348921,False
72,152,original,2.0,3.0,6.0,2.0,1.0,0.0,23.4375,1.0,5.0,,0.265580,0.132790,,
73,152,cf_1,,,,,,,,,4.0,0.0,0.265580,0.132790,0.261373,False
74,152,cf_2,6.0,,,,,,28.317567,,,0.0,0.265580,0.132790,0.391413,False
75,152,cf_3,,,,,,,39.561723,,,0.0,0.265580,0.132790,0.417755,False
76,153,original,3.0,3.0,5.0,7.0,1.0,0.0,27.767098,2.0,1.0,,0.471948,0.235974,,
77,153,cf_1,6.0,,,,,,,,6.0,0.0,0.471948,0.235974,0.380244,False
78,153,cf_2,,,,,,,,,7.0,0.0,0.471948,0.235974,0.463686,False
79,153,cf_3,,,,,,,19.527185,,2.0,0.0,0.471948,0.235974,0.124051,True

# genetic models

In [15]:
balanced_genetic =  BALANCED_DIR / "genetic_hltprhc_2026-04-09" / "genetic_annotated_hltprhc.csv"
unbalanced_genetic = UNBALANCED_DIR / "genetic_hltprhc_2026-04-09" / "genetic_annotated_hltprhc.csv"

balanced_genetic_df = pd.read_csv(balanced_genetic)
unbalanced_genetic_df = pd.read_csv(unbalanced_genetic)

In [16]:
balanced_genetic_df = clean_counterfactuals(balanced_genetic_df)
unbalanced_genetic_df = clean_counterfactuals(unbalanced_genetic_df)

### unbalanced data, genetic model

In [19]:
unbalanced_genetic_df.replace({np.nan : ""})

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,gndr,dosprt,hltprhc,original_risk,target_risk,predicted_risk,meets_target_risk
0,8,original,3.0,2.0,4.0,6.0,2.0,0.0,30.062102,2.0,7.0,,0.133913,0.066956,,
1,8,cf_1,1.0,6.0,,5.0,,,30.42185,,,0.0,0.133913,0.066956,0.281098,False
2,8,cf_1,2.0,1.0,,,3.0,,30.961729,,,0.0,0.133913,0.066956,0.243365,False
3,8,cf_1,1.0,1.0,,,4.0,,29.860552,,2.0,0.0,0.133913,0.066956,0.184247,False
4,14,original,1.0,1.0,4.0,3.0,3.0,0.0,26.827421,2.0,7.0,,0.180454,0.090227,,
5,14,cf_1,,,,,,,26.827421,,,0.0,0.180454,0.090227,0.180454,False
6,14,cf_1,,,,4.0,4.0,,26.827421,,,0.0,0.180454,0.090227,0.251084,False
7,14,cf_1,,4.0,,4.0,,,26.827421,,,0.0,0.180454,0.090227,0.186515,False
8,18,original,3.0,3.0,6.0,6.0,2.0,1.0,31.229454,2.0,0.0,,0.203730,0.101865,,
9,18,cf_1,1.0,1.0,,,,,29.860552,,3.0,0.0,0.203730,0.101865,0.259241,False
10,18,cf_1,5.0,1.0,,,3.0,,29.860552,,,0.0,0.203730,0.101865,0.262747,False
11,18,cf_1,1.0,1.0,,4.0,,0.0,31.163435,,,0.0,0.203730,0.101865,0.230921,False
12,38,original,3.0,3.0,6.0,2.0,1.0,0.0,33.470508,1.0,7.0,,0.043532,0.021766,,
13,38,cf_1,,,,,,,33.470509,,,0.0,0.043532,0.021766,0.043532,False
14,38,cf_1,,,4.0,,3.0,,33.497684,,,0.0,0.043532,0.021766,0.118839,False
15,38,cf_1,,,4.0,7.0,,,33.425159,,,0.0,0.043532,0.021766,0.42147,False
16,43,original,2.0,4.0,3.0,7.0,2.0,0.0,29.352355,2.0,2.0,,0.236484,0.118242,,
17,43,cf_1,,1.0,6.0,,,,29.320988,,4.0,0.0,0.236484,0.118242,0.163165,False
18,43,cf_1,,1.0,1.0,5.0,,,29.320988,,,0.0,0.236484,0.118242,0.111836,True
19,43,cf_1,,1.0,6.0,,,,29.03179,,4.0,0.0,0.236484,0.118242,0.182362,False
20,52,original,3.0,3.0,6.0,7.0,1.0,0.0,19.814053,2.0,1.0,,0.065827,0.032914,,
21,52,cf_1,,1.0,,,,,19.568235,,4.0,0.0,0.065827,0.032914,0.017564,True
22,52,cf_1,5.0,1.0,,,,1.0,20.047445,,,0.0,0.065827,0.032914,0.091321,False
23,52,cf_1,1.0,1.0,5.0,,,,19.571682,,,0.0,0.065827,0.032914,0.034903,False
24,67,original,4.0,5.0,1.0,7.0,3.0,1.0,39.197531,1.0,0.0,,0.228561,0.114281,,
25,67,cf_1,,,,,,,39.197533,,,0.0,0.228561,0.114281,0.228561,False
26,67,cf_1,1.0,2.0,,6.0,2.0,,39.183674,,,0.0,0.228561,0.114281,0.26253,False
27,67,cf_1,2.0,,,6.0,,0.0,39.183674,,3.0,0.0,0.228561,0.114281,0.138921,False
28,94,original,2.0,2.0,6.0,7.0,3.0,0.0,24.913495,1.0,0.0,,0.175727,0.087863,,
29,94,cf_1,,1.0,,,1.0,,24.913494,,3.0,0.0,0.175727,0.087863,0.075741,True
30,94,cf_1,,1.0,5.0,,,,24.973986,,,0.0,0.175727,0.087863,0.23884,False
31,94,cf_1,1.0,1.0,,,,,25.153151,,,0.0,0.175727,0.087863,0.227429,False
32,97,original,2.0,7.0,1.0,6.0,2.0,0.0,23.665244,1.0,0.0,,0.156362,0.078181,,
33,97,cf_1,,1.0,,2.0,3.0,,23.671253,,2.0,0.0,0.156362,0.078181,0.066705,True
34,97,cf_1,1.0,,2.0,,1.0,,23.738663,,7.0,0.0,0.156362,0.078181,0.08005,False
35,97,cf_1,1.0,1.0,5.0,7.0,,,23.588329,,,0.0,0.156362,0.078181,0.230162,False
36,106,original,3.0,3.0,4.0,7.0,1.0,0.0,31.644286,2.0,0.0,,0.248133,0.124066,,
37,106,cf_1,,1.0,,2.0,,,31.245237,,7.0,0.0,0.248133,0.124066,0.160688,False
38,106,cf_1,,1.0,,,3.0,,32.111954,,7.0,0.0,0.248133,0.124066,0.275298,False
39,106,cf_1,1.0,,2.0,3.0,,,31.163435,,,0.0,0.248133,0.124066,0.186055,False
40,112,original,3.0,4.0,6.0,7.0,4.0,0.0,26.77551,2.0,0.0,,0.383193,0.191597,,
41,112,cf_1,,1.0,,6.0,1.0,,26.666666,,,0.0,0.383193,0.191597,0.112898,True
42,112,cf_1,1.0,1.0,,,3.0,,26.446281,,,0.0,0.383193,0.191597,0.213657,False
43,112,cf_1,5.0,1.0,,,,,26.423571,,1.0,0.0,0.383193,0.191597,0.281929,False
44,127,original,3.0,3.0,6.0,7.0,3.0,0.0,32.629352,2.0,7.0,,0.213844,0.106922,,
45,127,cf_1,,,,,,,32.629353,,,0.0,0.213844,0.106922,0.213844,False
46,127,cf_1,,1.0,4.0,,,,32.111954,,,0.0,0.213844,0.106922,0.275298,False
47,127,cf_1,,,1.0,4.0,2.0,,32.629353,,0.0,0.0,0.213844,0.106922,0.067325,True
48,135,original,3.0,3.0,6.0,7.0,1.0,0.0,35.996327,2.0,0.0,,0.275623,0.137812,,
49,135,cf_1,,,,,,,35.996326,,,0.0,0.275623,0.137812,0.275623,False
50,135,cf_1,,,,,2.0,,36.111111,,,0.0,0.275623,0.137812,0.40041,False
51,135,cf_1,,,,5.0,,,36.011082,,1.0,0.0,0.275623,0.137812,0.095135,True
52,138,original,3.0,4.0,6.0,7.0,4.0,0.0,19.591837,1.0,0.0,,0.399530,0.199765,,
53,138,cf_1,2.0,1.0,,,,,20.429419,,,0.0,0.399530,0.199765,0.350409,False
54,138,cf_1,,1.0,,,1.0,,19.568235,,4.0,0.0,0.399530,0.199765,0.029225,True
55,138,cf_1,1.0,1.0,3.0,3.0,,,19.571682,,,0.0,0.399530,0.199765,0.28719,False
56,143,original,2.0,2.0,6.0,7.0,2.0,0.0,25.826446,1.0,0.0,,0.142929,0.071465,,
57,143,cf_1,3.0,1.0,,6.0,,,25.826447,,,0.0,0.142929,0.071465,0.122456,False
58,143,cf_1,,1.0,1.0,,1.0,,25.826447,,7.0,0.0,0.142929,0.071465,0.05784,True
59,143,cf_1,5.0,1.0,,,,,25.864513,,1.0,0.0,0.142929,0.071465,0.13851,False
60,146,original,4.0,3.0,4.0,2.0,2.0,0.0,30.991736,1.0,7.0,,0.085930,0.042965,,
61,146,cf_1,3.0,1.0,,,1.0,,31.245237,,,0.0,0.085930,0.042965,0.188995,False
62,146,cf_1,2.0,1.0,5.0,,,,31.588614,,,0.0,0.085930,0.042965,0.209778,False
63,146,cf_1,2.0,1.0,,6.0,3.0,,30.961729,,,0.0,0.085930,0.042965,0.238506,False
64,149,original,4.0,4.0,4.0,4.0,4.0,1.0,30.367347,1.0,2.0,,0.182266,0.091133,,
65,149,cf_1,1.0,1.0,,,,,30.387144,,0.0,0.0,0.182266,0.091133,0.335761,False
66,149,cf_1,1.0,1.0,,6.0,,,30.387144,,6.0,0.0,0.182266,0.091133,0.244274,False
67,149,cf_1,1.0,1.0,,,,0.0,30.387144,,0.0,0.0,0.182266,0.091133,0.404321,False
68,151,original,3.0,3.0,4.0,2.0,1.0,0.0,25.97868,1.0,3.0,,0.083354,0.041677,,
69,151,cf_1,,1.0,,,,,26.12245,,7.0,0.0,0.083354,0.041677,0.064424,False
70,151,cf_1,1.0,,,3.0,,,26.234568,,,0.0,0.083354,0.041677,0.092879,False
71,151,cf_1,1.0,1.0,,5.0,,,26.264944,,,0.0,0.083354,0.041677,0.085781,False
72,152,original,2.0,3.0,6.0,2.0,1.0,0.0,23.4375,1.0,5.0,,0.093804,0.046902,,
73,152,cf_1,1.0,,2.0,4.0,,,,,,0.0,0.093804,0.046902,0.023467,True
74,152,cf_1,1.0,,2.0,7.0,,,,,,0.0,0.093804,0.046902,0.04217,True
75,152,cf_1,,1.0,,6.0,,,23.423557,,,0.0,0.093804,0.046902,0.073635,False
76,153,original,3.0,3.0,5.0,7.0,1.0,0.0,27.767098,2.0,1.0,,0.095451,0.047726,,
77,153,cf_1,1.0,1.0,,,,,27.681662,,,0.0,0.095451,0.047726,0.087663,False
78,153,cf_1,5.0,1.0,,,2.0,,27.681662,,,0.0,0.095451,0.047726,0.182216,False
79,153,cf_1,6.0,1.0,2.0,,,,27.34375,,,0.0,0.095451,0.047726,0.099873,False

### balanced data, genetic model

In [20]:
balanced_genetic_df.replace({np.nan : ""})

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,gndr,dosprt,hltprhc,original_risk,target_risk,predicted_risk,meets_target_risk
0,8,original,3.0,2.0,4.0,6.0,2.0,0.0,30.062102,2.0,7.0,,0.632361,0.316180,,
1,8,cf_1,,,6.0,,1.0,,30.023243,,4.0,0.0,0.632361,0.316180,0.340836,False
2,8,cf_1,,3.0,6.0,7.0,1.0,,30.062101,,3.0,0.0,0.632361,0.316180,0.305119,True
3,8,cf_1,4.0,1.0,6.0,3.0,,,30.071169,,,0.0,0.632361,0.316180,0.46498,False
4,14,original,1.0,1.0,4.0,3.0,3.0,0.0,26.827421,2.0,7.0,,0.611948,0.305974,,
5,14,cf_1,,,,,2.0,,26.446281,,5.0,0.0,0.611948,0.305974,0.477897,False
6,14,cf_1,,,,,1.0,,26.297577,,5.0,0.0,0.611948,0.305974,0.292273,True
7,14,cf_1,,,3.0,,1.0,,27.47563,,,0.0,0.611948,0.305974,0.407908,False
8,18,original,3.0,3.0,6.0,6.0,2.0,1.0,31.229454,2.0,0.0,,0.673858,0.336929,,
9,18,cf_1,,,,,1.0,0.0,31.244993,,7.0,0.0,0.673858,0.336929,0.390567,False
10,18,cf_1,,,,7.0,1.0,,31.25,,2.0,0.0,0.673858,0.336929,0.411142,False
11,18,cf_1,,,1.0,4.0,1.0,,31.231409,,2.0,0.0,0.673858,0.336929,0.34973,False
12,38,original,3.0,3.0,6.0,2.0,1.0,0.0,33.470508,1.0,7.0,,0.365020,0.182510,,
13,38,cf_1,,,,,,,33.470509,,,0.0,0.365020,0.182510,0.36502,False
14,38,cf_1,,,,3.0,,,33.333332,,,0.0,0.365020,0.182510,0.354067,False
15,38,cf_1,,,,7.0,,,33.203125,,,0.0,0.365020,0.182510,0.437681,False
16,43,original,2.0,4.0,3.0,7.0,2.0,0.0,29.352355,2.0,2.0,,0.635827,0.317913,,
17,43,cf_1,3.0,3.0,6.0,,1.0,,29.352354,,,0.0,0.635827,0.317913,0.317615,True
18,43,cf_1,4.0,,2.0,,,,29.320988,,5.0,0.0,0.635827,0.317913,0.422603,False
19,43,cf_1,5.0,,1.0,2.0,1.0,,29.352354,,0.0,0.0,0.635827,0.317913,0.289974,True
20,52,original,3.0,3.0,6.0,7.0,1.0,0.0,19.814053,2.0,1.0,,0.340431,0.170216,,
21,52,cf_1,,1.0,,,,,19.568235,,4.0,0.0,0.340431,0.170216,0.186077,False
22,52,cf_1,5.0,1.0,,,,1.0,20.047445,,,0.0,0.340431,0.170216,0.371047,False
23,52,cf_1,7.0,6.0,,,,,19.53125,,6.0,0.0,0.340431,0.170216,0.184794,False
24,67,original,4.0,5.0,1.0,7.0,3.0,1.0,39.197531,1.0,0.0,,0.711530,0.355765,,
25,67,cf_1,5.0,,,6.0,1.0,0.0,39.0625,,,0.0,0.711530,0.355765,0.375399,False
26,67,cf_1,,4.0,,6.0,1.0,0.0,36.953053,,,0.0,0.711530,0.355765,0.370206,False
27,67,cf_1,,4.0,6.0,4.0,1.0,,38.89159,,5.0,0.0,0.711530,0.355765,0.396323,False
28,94,original,2.0,2.0,6.0,7.0,3.0,0.0,24.913495,1.0,0.0,,0.676812,0.338406,,
29,94,cf_1,,1.0,,,1.0,,24.913494,,3.0,0.0,0.676812,0.338406,0.238295,True
30,94,cf_1,6.0,,,,1.0,,25.249338,,1.0,0.0,0.676812,0.338406,0.354989,False
31,94,cf_1,,1.0,,,1.0,,25.280109,,1.0,0.0,0.676812,0.338406,0.337177,True
32,97,original,2.0,7.0,1.0,6.0,2.0,0.0,23.665244,1.0,0.0,,0.522425,0.261212,,
33,97,cf_1,1.0,1.0,,7.0,,,24.023809,,,0.0,0.522425,0.261212,0.472426,False
34,97,cf_1,,1.0,,2.0,3.0,,23.671253,,2.0,0.0,0.522425,0.261212,0.477842,False
35,97,cf_1,,1.0,6.0,3.0,,,23.875114,,7.0,0.0,0.522425,0.261212,0.297404,False
36,106,original,3.0,3.0,4.0,7.0,1.0,0.0,31.644286,2.0,0.0,,0.743708,0.371854,,
37,106,cf_1,,,6.0,6.0,,,31.644285,,2.0,0.0,0.743708,0.371854,0.498733,False
38,106,cf_1,,,6.0,,,,31.637396,,4.0,0.0,0.743708,0.371854,0.416932,False
39,106,cf_1,,,1.0,4.0,,,31.790123,,,0.0,0.743708,0.371854,0.30234,True
40,112,original,3.0,4.0,6.0,7.0,4.0,0.0,26.77551,2.0,0.0,,0.821600,0.410800,,
41,112,cf_1,,1.0,,6.0,1.0,,26.666666,,,0.0,0.821600,0.410800,0.488689,False
42,112,cf_1,1.0,1.0,,,1.0,,26.666666,,7.0,0.0,0.821600,0.410800,0.300884,True
43,112,cf_1,1.0,6.0,,,1.0,,26.446281,,2.0,0.0,0.821600,0.410800,0.283248,True
44,127,original,3.0,3.0,6.0,7.0,3.0,0.0,32.629352,2.0,7.0,,0.663411,0.331705,,
45,127,cf_1,,,,,1.0,,32.847301,,,0.0,0.663411,0.331705,0.393699,False
46,127,cf_1,,,,4.0,1.0,,32.686981,,,0.0,0.663411,0.331705,0.376231,False
47,127,cf_1,2.0,,,,1.0,,32.388355,,,0.0,0.663411,0.331705,0.421774,False
48,135,original,3.0,3.0,6.0,7.0,1.0,0.0,35.996327,2.0,0.0,,0.779000,0.389500,,
49,135,cf_1,,,,,,,34.696857,,7.0,0.0,0.779000,0.389500,0.424309,False
50,135,cf_1,,4.0,,,,,35.43084,,7.0,0.0,0.779000,0.389500,0.479106,False
51,135,cf_1,,,,4.0,,,35.321236,,7.0,0.0,0.779000,0.389500,0.429116,False
52,138,original,3.0,4.0,6.0,7.0,4.0,0.0,19.591837,1.0,0.0,,0.748888,0.374444,,
53,138,cf_1,,1.0,,,1.0,,19.568235,,4.0,0.0,0.748888,0.374444,0.208024,True
54,138,cf_1,1.0,,,3.0,,,19.467402,,7.0,0.0,0.748888,0.374444,0.491984,False
55,138,cf_1,1.0,,,4.0,,,20.233553,,2.0,0.0,0.748888,0.374444,0.446626,False
56,143,original,2.0,2.0,6.0,7.0,2.0,0.0,25.826446,1.0,0.0,,0.672496,0.336248,,
57,143,cf_1,,1.0,1.0,,1.0,,25.826447,,7.0,0.0,0.672496,0.336248,0.357888,False
58,143,cf_1,6.0,1.0,,,,,25.910685,,7.0,0.0,0.672496,0.336248,0.44125,False
59,143,cf_1,,1.0,,5.0,,,26.12245,,3.0,0.0,0.672496,0.336248,0.377407,False
60,146,original,4.0,3.0,4.0,2.0,2.0,0.0,30.991736,1.0,7.0,,0.535564,0.267782,,
61,146,cf_1,,,6.0,7.0,,,31.020409,,3.0,0.0,0.535564,0.267782,0.498984,False
62,146,cf_1,5.0,,6.0,,,,31.047695,,2.0,0.0,0.535564,0.267782,0.456375,False
63,146,cf_1,,,6.0,4.0,1.0,,30.864197,,,0.0,0.535564,0.267782,0.319942,False
64,149,original,4.0,4.0,4.0,4.0,4.0,1.0,30.367347,1.0,2.0,,0.680025,0.340013,,
65,149,cf_1,,,6.0,,1.0,0.0,30.273712,,5.0,0.0,0.680025,0.340013,0.322311,True
66,149,cf_1,,3.0,6.0,3.0,2.0,0.0,30.367348,,4.0,0.0,0.680025,0.340013,0.276313,True
67,149,cf_1,,2.0,,2.0,1.0,0.0,30.35033,,4.0,0.0,0.680025,0.340013,0.494144,False
68,151,original,3.0,3.0,4.0,2.0,1.0,0.0,25.97868,1.0,3.0,,0.402481,0.201240,,
69,151,cf_1,,1.0,,,,,26.12245,,7.0,0.0,0.402481,0.201240,0.306616,False
70,151,cf_1,2.0,,,6.0,,,25.864513,,5.0,0.0,0.402481,0.201240,0.445884,False
71,151,cf_1,,1.0,,6.0,,,26.12245,,7.0,0.0,0.402481,0.201240,0.29818,False
72,152,original,2.0,3.0,6.0,2.0,1.0,0.0,23.4375,1.0,5.0,,0.265580,0.132790,,
73,152,cf_1,1.0,1.0,,,,,,,6.0,0.0,0.265580,0.132790,0.44273,False
74,152,cf_1,,1.0,,6.0,,,23.423557,,,0.0,0.265580,0.132790,0.372792,False
75,152,cf_1,,1.0,,4.0,,,23.12406,,,0.0,0.265580,0.132790,0.247672,False
76,153,original,3.0,3.0,5.0,7.0,1.0,0.0,27.767098,2.0,1.0,,0.471948,0.235974,,
77,153,cf_1,,,,,,,27.767097,,,0.0,0.471948,0.235974,0.471948,False
78,153,cf_1,,,4.0,,,,27.76343,,3.0,0.0,0.471948,0.235974,0.379889,False
79,153,cf_1,,,2.0,5.0,,,27.774271,,,0.0,0.471948,0.235974,0.308534,False

# meets target rates

In [35]:
def cf_success_stats(df):
    cf_rows = df[df["cf_id"] != "original"]
    total = len(cf_rows)
    meets = cf_rows["meets_target_risk"].sum()
    og_risk = cf_rows["original_risk"].mean()
    return {
        "total_cf": total,
        "original_risk_mean": og_risk,
        "meets_target": meets,
        "rate": meets / total if total > 0 else 0
    }


def compare_datasets(dfs, names):
    stats = []
    for df, name in zip(dfs, names):
        s = cf_success_stats(df)
        s["dataset"] = name
        stats.append(s)
    return pd.DataFrame(stats)

In [36]:
result = compare_datasets(
    [
        balanced_random_df, unbalanced_random_df,
        balanced_genetic_df, unbalanced_genetic_df
    ],
    [
        "balanced_random_df", "unbalanced_random_df",
        "balanced_genetic_df", "unbalanced_genetic_df"
    ]
)

result

   total_cf  original_risk_mean  meets_target      rate                dataset
0        60            0.597746             5  0.083333     balanced_random_df
1        60            0.181432            14  0.233333   unbalanced_random_df
2        60            0.597746            12  0.200000    balanced_genetic_df
3        60            0.181432            11  0.183333  unbalanced_genetic_df