In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
batch_cfcheck_data = CF_OUTPUTS / "RandomForest_genetic_prange_lowthres_2026-04-21" / "genetic_annotated_hltprhc.csv"
batch_cfcheck_df = pd.read_csv(batch_cfcheck_data)

In [3]:
pd.set_option("display.max_rows", None)

In [4]:
batch_cfcheck_df = batch_cfcheck_df.drop(columns=["hltprhc", "target_risk"])

In [5]:

batch_cfcheck_df["cf_id"] = batch_cfcheck_df["cf_id"].replace({"original": "xin"})

batch_cfcheck_df = batch_cfcheck_df.rename(columns={
    "original_risk": "risk_before",
    "predicted_risk" : "predicted_risk_after",
    "meets_target_risk" : "valid",
})

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,0.063333,NaN,NaN,2.45
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,16.701280,NaN,0.063333,0.073333,False,NaN
2,0,cf_1,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,NaN,0.063333,0.070000,False,NaN
3,0,cf_1,NaN,NaN,NaN,NaN,1.0,NaN,18.938780,NaN,0.063333,0.046667,False,NaN

In [6]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

batch_cfcheck_df = fix_cf_id(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,0.063333,NaN,NaN,2.45
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,16.701280,NaN,0.063333,0.073333,False,NaN
2,0,cf_2,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,NaN,0.063333,0.070000,False,NaN
3,0,cf_3,NaN,NaN,NaN,NaN,1.0,NaN,18.938780,NaN,0.063333,0.046667,False,NaN
4,0,cf_4,NaN,NaN,NaN,NaN,NaN,NaN,18.929150,5.0,0.063333,0.036667,False,NaN
5,0,cf_5,3.0,NaN,NaN,NaN,NaN,NaN,18.928950,NaN,0.063333,0.080000,False,NaN
6,0,cf_6,3.0,NaN,NaN,NaN,NaN,NaN,18.792050,NaN,0.063333,0.076667,False,NaN
7,0,cf_7,NaN,NaN,6.0,NaN,NaN,NaN,18.548630,NaN,0.063333,0.033333,False,NaN
8,0,cf_8,NaN,NaN,NaN,NaN,NaN,NaN,18.529790,5.0,0.063333,0.050000,False,NaN
9,0,cf_9,NaN,NaN,6.0,NaN,NaN,NaN,17.551290,NaN,0.063333,0.040000,False,NaN
10,0,cf_10,NaN,NaN,NaN,NaN,NaN,NaN,17.344170,4.0,0.063333,0.080000,False,NaN
11,0,cf_11,NaN,NaN,6.0,7.0,NaN,NaN,18.974530,NaN,0.063333,0.093333,False,NaN
12,0,cf_12,NaN,NaN,NaN,7.0,NaN,NaN,18.974530,7.0,0.063333,0.030000,True,NaN
13,0,cf_13,NaN,NaN,5.0,NaN,NaN,NaN,18.961930,2.0,0.063333,0.026667,True,NaN
14,0,cf_14,1.0,NaN,NaN,NaN,NaN,NaN,18.961930,7.0,0.063333,0.073333,False,NaN
15,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.375680,0.0,0.146667,NaN,NaN,2.56
16,1,cf_1,2.0,NaN,NaN,NaN,1.0,NaN,22.375680,NaN,0.146667,0.010000,True,NaN
17,1,cf_2,NaN,2.0,5.0,NaN,NaN,NaN,22.375680,NaN,0.146667,0.080000,False,NaN
18,1,cf_3,NaN,NaN,NaN,NaN,1.0,NaN,22.375680,1.0,0.146667,0.050000,True,NaN
19,1,cf_4,NaN,NaN,NaN,NaN,2.0,NaN,22.375680,7.0,0.146667,0.090000,False,NaN
20,1,cf_5,NaN,NaN,NaN,7.0,NaN,NaN,22.375680,7.0,0.146667,0.076667,False,NaN
21,1,cf_6,NaN,NaN,2.0,NaN,1.0,NaN,22.375680,NaN,0.146667,0.023333,True,NaN
22,1,cf_7,NaN,NaN,NaN,3.0,1.0,NaN,22.375680,NaN,0.146667,0.000000,True,NaN
23,1,cf_8,1.0,NaN,2.0,NaN,NaN,NaN,22.375680,4.0,0.146667,0.063333,True,NaN
24,1,cf_9,1.0,NaN,2.0,NaN,1.0,NaN,22.375680,NaN,0.146667,0.063333,True,NaN
25,1,cf_10,NaN,NaN,2.0,NaN,2.0,NaN,22.375680,2.0,0.146667,0.050000,True,NaN
26,1,cf_11,2.0,NaN,NaN,NaN,2.0,NaN,22.375680,5.0,0.146667,0.050000,True,NaN
27,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.694019,7.0,0.156667,NaN,NaN,2.72
28,2,cf_1,3.0,NaN,NaN,NaN,2.0,NaN,22.679950,NaN,0.156667,0.013333,True,NaN
29,2,cf_2,NaN,NaN,NaN,6.0,1.0,NaN,22.675740,NaN,0.156667,0.063333,True,NaN

In [7]:
# round BMI to 2 decimal places, and set to NaN if equal to xin after rounding
def round_and_clear_bmi(df):
    df = df.copy()

    # Round BMI to 2 decimals for all rows
    df['bmi'] = df['bmi'].round(2)

    # For each query_index, get the xin BMI and compare
    for query_idx in df['query_index'].unique():
        query_mask = df['query_index'] == query_idx
        xin_mask = query_mask & (df['cf_id'] == 'xin')
        cf_mask = query_mask & (df['cf_id'] != 'xin')

        # Get the xin BMI value for this query
        xin_bmi = df.loc[xin_mask, 'bmi'].values[0]

        # Set cf BMI to NaN where it equals xin BMI
        equal_mask = cf_mask & (df['bmi'] == xin_bmi)
        df.loc[equal_mask, 'bmi'] = np.nan

    return df

batch_cfcheck_df = round_and_clear_bmi(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.99,0.0,0.063333,NaN,NaN,2.45
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,16.70,NaN,0.063333,0.073333,False,NaN
2,0,cf_2,NaN,NaN,NaN,7.0,NaN,NaN,18.97,NaN,0.063333,0.070000,False,NaN
3,0,cf_3,NaN,NaN,NaN,NaN,1.0,NaN,18.94,NaN,0.063333,0.046667,False,NaN
4,0,cf_4,NaN,NaN,NaN,NaN,NaN,NaN,18.93,5.0,0.063333,0.036667,False,NaN
5,0,cf_5,3.0,NaN,NaN,NaN,NaN,NaN,18.93,NaN,0.063333,0.080000,False,NaN
6,0,cf_6,3.0,NaN,NaN,NaN,NaN,NaN,18.79,NaN,0.063333,0.076667,False,NaN
7,0,cf_7,NaN,NaN,6.0,NaN,NaN,NaN,18.55,NaN,0.063333,0.033333,False,NaN
8,0,cf_8,NaN,NaN,NaN,NaN,NaN,NaN,18.53,5.0,0.063333,0.050000,False,NaN
9,0,cf_9,NaN,NaN,6.0,NaN,NaN,NaN,17.55,NaN,0.063333,0.040000,False,NaN
10,0,cf_10,NaN,NaN,NaN,NaN,NaN,NaN,17.34,4.0,0.063333,0.080000,False,NaN
11,0,cf_11,NaN,NaN,6.0,7.0,NaN,NaN,18.97,NaN,0.063333,0.093333,False,NaN
12,0,cf_12,NaN,NaN,NaN,7.0,NaN,NaN,18.97,7.0,0.063333,0.030000,True,NaN
13,0,cf_13,NaN,NaN,5.0,NaN,NaN,NaN,18.96,2.0,0.063333,0.026667,True,NaN
14,0,cf_14,1.0,NaN,NaN,NaN,NaN,NaN,18.96,7.0,0.063333,0.073333,False,NaN
15,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.38,0.0,0.146667,NaN,NaN,2.56
16,1,cf_1,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.146667,0.010000,True,NaN
17,1,cf_2,NaN,2.0,5.0,NaN,NaN,NaN,NaN,NaN,0.146667,0.080000,False,NaN
18,1,cf_3,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,0.146667,0.050000,True,NaN
19,1,cf_4,NaN,NaN,NaN,NaN,2.0,NaN,NaN,7.0,0.146667,0.090000,False,NaN
20,1,cf_5,NaN,NaN,NaN,7.0,NaN,NaN,NaN,7.0,0.146667,0.076667,False,NaN
21,1,cf_6,NaN,NaN,2.0,NaN,1.0,NaN,NaN,NaN,0.146667,0.023333,True,NaN
22,1,cf_7,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,0.146667,0.000000,True,NaN
23,1,cf_8,1.0,NaN,2.0,NaN,NaN,NaN,NaN,4.0,0.146667,0.063333,True,NaN
24,1,cf_9,1.0,NaN,2.0,NaN,1.0,NaN,NaN,NaN,0.146667,0.063333,True,NaN
25,1,cf_10,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,0.146667,0.050000,True,NaN
26,1,cf_11,2.0,NaN,NaN,NaN,2.0,NaN,NaN,5.0,0.146667,0.050000,True,NaN
27,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.69,7.0,0.156667,NaN,NaN,2.72
28,2,cf_1,3.0,NaN,NaN,NaN,2.0,NaN,22.68,NaN,0.156667,0.013333,True,NaN
29,2,cf_2,NaN,NaN,NaN,6.0,1.0,NaN,22.68,NaN,0.156667,0.063333,True,NaN

In [8]:
int_columns = [
    "etfruit",
    "eatveg",
    "cgtsmok",
    "alcfreq",
    "slprl",
    "paccnois",
    "dosprt",
]

float_columns = [
    "bmi",
    "risk_before",
    "predicted_risk_after",
]

In [9]:
batch_cfcheck_df[int_columns] = batch_cfcheck_df[int_columns].astype("Int64")

In [10]:
batch_cfcheck_df[float_columns] = batch_cfcheck_df[float_columns].round(2)

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,0.06,NaN,NaN,2.45
1,0,cf_1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,16.70,<NA>,0.06,0.07,False,NaN
2,0,cf_2,<NA>,<NA>,<NA>,7,<NA>,<NA>,18.97,<NA>,0.06,0.07,False,NaN
3,0,cf_3,<NA>,<NA>,<NA>,<NA>,1,<NA>,18.94,<NA>,0.06,0.05,False,NaN

In [11]:
batch_cfcheck_df[int_columns] = (
    batch_cfcheck_df[int_columns]
    .astype("string")
    .fillna("")
)

In [12]:
batch_cfcheck_df = batch_cfcheck_df.replace({np.nan : ""})
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,0.06,,,2.45
1,0,cf_1,,,,,,,16.7,,0.06,0.07,False,
2,0,cf_2,,,,7,,,18.97,,0.06,0.07,False,
3,0,cf_3,,,,,1,,18.94,,0.06,0.05,False,

In [13]:
mask = batch_cfcheck_df["cf_id"] == "xin"
batch_cfcheck_df.loc[mask, "risk_before"] = ""
batch_cfcheck_df.head(4)

/tmp/ipykernel_32810/1160248817.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_cfcheck_df.loc[mask, "risk_before"] = ""

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,,,,2.45
1,0,cf_1,,,,,,,16.7,,0.06,0.07,False,
2,0,cf_2,,,,7,,,18.97,,0.06,0.07,False,
3,0,cf_3,,,,,1,,18.94,,0.06,0.05,False,

In [14]:
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# 1. Beräkna Nchanged endast för CF-rader
mask_cf = batch_cfcheck_df["cf_id"] != "xin"

batch_cfcheck_df.loc[mask_cf, "Nchanged"] = (
    batch_cfcheck_df.loc[mask_cf, feature_cols] != ""
).sum(axis=1)

# 2. Konvertera kolumnen till ren string
batch_cfcheck_df["Nchanged"] = batch_cfcheck_df["Nchanged"].astype("string")

# 3. Baseline ska vara tom
batch_cfcheck_df.loc[batch_cfcheck_df["cf_id"] == "xin", "Nchanged"] = ""

In [15]:
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec,Nchanged
0,0,xin,4,3,3,4,2,0,18.99,0,,,,2.45,
1,0,cf_1,,,,,,,16.7,,0.06,0.07,False,,1
2,0,cf_2,,,,7,,,18.97,,0.06,0.07,False,,2
3,0,cf_3,,,,,1,,18.94,,0.06,0.05,False,,2

In [16]:
batch_cfcheck_df["Gower"] = ""
batch_cfcheck_df["Expected"] = ""

In [17]:
order = ["query_index", "cf_id"] + feature_cols + ["cf_gen_time_sec", "Gower", "Nchanged", "valid", "risk_before", "predicted_risk_after", "Expected"]

batch_cfcheck_df = batch_cfcheck_df[order]
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.45,,,,,,
1,0,cf_1,,,,,,,16.7,,,,1,False,0.06,0.07,
2,0,cf_2,,,,7,,,18.97,,,,2,False,0.06,0.07,
3,0,cf_3,,,,,1,,18.94,,,,2,False,0.06,0.05,
4,0,cf_4,,,,,,,18.93,5,,,2,False,0.06,0.04,
5,0,cf_5,3,,,,,,18.93,,,,2,False,0.06,0.08,
6,0,cf_6,3,,,,,,18.79,,,,2,False,0.06,0.08,
7,0,cf_7,,,6,,,,18.55,,,,2,False,0.06,0.03,
8,0,cf_8,,,,,,,18.53,5,,,2,False,0.06,0.05,
9,0,cf_9,,,6,,,,17.55,,,,2,False,0.06,0.04,
10,0,cf_10,,,,,,,17.34,4,,,2,False,0.06,0.08,
11,0,cf_11,,,6,7,,,18.97,,,,3,False,0.06,0.09,
12,0,cf_12,,,,7,,,18.97,7,,,3,True,0.06,0.03,
13,0,cf_13,,,5,,,,18.96,2,,,3,True,0.06,0.03,
14,0,cf_14,1,,,,,,18.96,7,,,3,False,0.06,0.07,
15,1,xin,3,4,1,2,3,0,22.38,0,2.56,,,,,,
16,1,cf_1,2,,,,1,,,,,,2,True,0.15,0.01,
17,1,cf_2,,2,5,,,,,,,,2,False,0.15,0.08,
18,1,cf_3,,,,,1,,,1,,,2,True,0.15,0.05,
19,1,cf_4,,,,,2,,,7,,,2,False,0.15,0.09,
20,1,cf_5,,,,7,,,,7,,,2,False,0.15,0.08,
21,1,cf_6,,,2,,1,,,,,,2,True,0.15,0.02,
22,1,cf_7,,,,3,1,,,,,,2,True,0.15,0.0,
23,1,cf_8,1,,2,,,,,4,,,3,True,0.15,0.06,
24,1,cf_9,1,,2,,1,,,,,,3,True,0.15,0.06,
25,1,cf_10,,,2,,2,,,2,,,3,True,0.15,0.05,
26,1,cf_11,2,,,,2,,,5,,,3,True,0.15,0.05,
27,2,xin,5,3,1,1,4,0,22.69,7,2.72,,,,,,
28,2,cf_1,3,,,,2,,22.68,,,,3,True,0.16,0.01,
29,2,cf_2,,,,6,1,,22.68,,,,3,True,0.16,0.06,
30,2,cf_3,,,,4,2,,22.68,,,,3,True,0.16,0.06,
31,2,cf_4,,,,3,2,,22.68,,,,3,False,0.16,0.09,
32,2,cf_5,,,4,,1,,21.0,,,,3,True,0.16,0.01,
33,2,cf_6,,,6,,1,,20.24,,,,3,True,0.16,0.02,
34,2,cf_7,,,2,6,1,,22.68,,,,4,True,0.16,0.01,
35,2,cf_8,,2,,3,2,,22.68,,,,4,True,0.16,0.04,
36,2,cf_9,,1,,2,2,,22.68,,,,4,True,0.16,0.07,
37,2,cf_10,4,,,4,2,,22.68,,,,4,True,0.16,0.01,
38,2,cf_11,,2,,5,1,,22.68,,,,4,True,0.16,0.03,
39,2,cf_12,1,,,3,2,,22.68,,,,4,True,0.16,0.07,
40,2,cf_13,1,,,5,2,,22.68,,,,4,True,0.16,0.02,
41,2,cf_14,1,,,6,3,,22.68,,,,4,True,0.16,0.05,
42,2,cf_15,1,,2,3,,,22.68,,,,4,False,0.16,0.09,
43,3,xin,3,3,6,6,2,0,24.34,1,2.91,,,,,,
44,3,cf_1,,,,,,,,,,,0,True,0.02,0.01,
45,3,cf_2,,,,,,,24.33,,,,1,True,0.02,0.0,
46,3,cf_3,,,,,,,24.3,,,,1,True,0.02,0.0,
47,3,cf_4,,,,,,,24.3,,,,1,True,0.02,0.0,
48,3,cf_5,,,,,,,24.14,,,,1,True,0.02,0.0,
49,3,cf_6,,,,7,,,,,,,1,False,0.02,0.03,
50,3,cf_7,,,,,,,,3,,,1,True,0.02,0.0,
51,3,cf_8,,,,,,,,4,,,1,False,0.02,0.02,
52,3,cf_9,,,,,,,24.33,2,,,2,True,0.02,0.0,
53,3,cf_10,,,,,,,24.31,2,,,2,True,0.02,0.0,
54,3,cf_11,,,,,,,24.31,4,,,2,False,0.02,0.03,
55,3,cf_12,,,,7,,,24.31,,,,2,False,0.02,0.01,
56,4,xin,5,4,2,7,1,0,21.26,3,3.12,,,,,,
57,4,cf_1,,,,,,,,,,,0,False,0.03,0.03,
58,4,cf_2,,,6,,,,,,,,1,True,0.03,0.0,
59,4,cf_3,3,,,,,,,,,,1,False,0.03,0.05,
60,4,cf_4,,2,,,,,,,,,1,True,0.03,0.01,
61,4,cf_5,4,,,,,,,,,,1,False,0.03,0.03,
62,4,cf_6,,,3,,,,,,,,1,True,0.03,0.01,
63,4,cf_7,,,5,,,,,,,,1,True,0.03,0.01,
64,4,cf_8,,3,,,,,,,,,1,True,0.03,0.01,
65,4,cf_9,,,,,,,21.22,,,,1,False,0.03,0.02,
66,4,cf_10,1,,,,,,,4,,,2,False,0.03,0.09,
67,4,cf_11,3,,6,,,,,,,,2,False,0.03,0.05,
68,4,cf_12,1,,4,,,,,,,,2,False,0.03,0.05,
69,4,cf_13,1,,5,,,,,,,,2,False,0.03,0.02,
70,4,cf_14,2,1,,,,,,,,,2,False,0.03,0.05,
71,4,cf_15,2,,5,,,,,,,,2,False,0.03,0.02,
72,4,cf_16,3,2,,,,,,,,,2,True,0.03,0.01,
73,5,xin,2,2,1,2,4,0,27.99,0,2.91,,,,,,
74,5,cf_1,,,,,1,,,,,,1,True,0.33,0.08,
75,5,cf_2,1,,,,,,,6,,,2,True,0.33,0.09,
76,5,cf_3,,,,,1,,,2,,,2,True,0.33,0.02,
77,5,cf_4,,,,,2,,,2,,,2,True,0.33,0.03,
78,5,cf_5,,,,,2,,,6,,,2,True,0.33,0.04,
79,5,cf_6,,,,,2,,,7,,,2,True,0.33,0.05,
80,5,cf_7,,,,5,1,,,,,,2,True,0.33,0.03,
81,5,cf_8,,,,4,1,,,,,,2,True,0.33,0.04,
82,5,cf_9,,,2,,,,,2,,,2,True,0.33,0.09,
83,5,cf_10,,,4,,1,,,,,,2,True,0.33,0.09,
84,6,xin,2,3,5,4,1,0,27.68,4,2.34,,,,,,
85,6,cf_1,,,,,,,26.23,,,,1,True,0.15,0.06,
86,6,cf_2,,,,,,,25.5,,,,1,True,0.15,0.07,
87,6,cf_3,,,,,,,25.44,,,,1,True,0.15,0.07,
88,6,cf_4,,,,,,,25.37,,,,1,True,0.15,0.07,
89,6,cf_5,,,,,,,24.36,,,,1,False,0.15,0.09,
90,6,cf_6,,,,,,,24.33,,,,1,True,0.15,0.04,
91,6,cf_7,,,,,,,24.25,,,,1,True,0.15,0.01,
92,6,cf_8,,,,,,,24.25,,,,1,True,0.15,0.01,
93,6,cf_9,,,,,,,26.93,7,,,2,True,0.15,0.04,
94,6,cf_10,,,,,,,26.69,5,,,2,True,0.15,0.05,
95,6,cf_11,,,,7,,,26.58,,,,2,False,0.15,0.08,
96,6,cf_12,,,,5,,,26.48,,,,2,True,0.15,0.05,
97,6,cf_13,1,,,,,,26.48,,,,2,True,0.15,0.06,
98,6,cf_14,,2,,,,,26.48,,,,2,True,0.15,0.02,
99,6,cf_15,,,6,,,,26.18,,,,2,True,0.15,0.06,
100,6,cf_16,,,,,,,23.03,,,,1,True,0.15,0.0,
101,7,xin,2,3,6,3,1,0,20.44,2,2.44,,,,,,
102,7,cf_1,,,,,,,20.43,,,,1,False,0.01,0.02,
103,7,cf_2,,,,,,,20.42,,,,1,False,0.01,0.02,
104,7,cf_3,,,,,,,20.4,,,,1,False,0.01,0.01,
105,7,cf_4,,,,,,,20.38,,,,1,False,0.01,0.01,
106,7,cf_5,,,,,,,20.38,,,,1,False,0.01,0.01,
107,7,cf_6,,,,,,,20.37,,,,1,False,0.01,0.01,
108,7,cf_7,,,,,,,19.77,,,,1,True,0.01,0.0,
109,7,cf_8,,,,,,,18.84,,,,1,True,0.01,0.0,
110,7,cf_9,,,,,,,18.56,,,,1,True,0.01,0.0,
111,7,cf_10,,,,,,,18.2,,,,1,False,0.01,0.02,
112,7,cf_11,,,,,,,17.95,,,,1,True,0.01,0.0,
113,7,cf_12,,,,7,,,20.43,,,,2,False,0.01,0.01,
114,7,cf_13,,,,6,,,20.43,,,,2,False,0.01,0.03,
115,7,cf_14,,,,,,,20.43,4,,,2,False,0.01,0.04,
116,7,cf_15,,,,,,,20.43,5,,,2,False,0.01,0.01,
117,7,cf_16,,,,4,,,20.43,,,,2,False,0.01,0.06,
118,7,cf_17,,,,6,,,20.42,,,,2,False,0.01,0.03,
119,7,cf_18,,,,,,,20.42,6,,,2,False,0.01,0.04,
120,7,cf_19,,,,,,,20.42,5,,,2,False,0.01,0.01,
121,7,cf_20,,,,4,,,20.42,,,,2,False,0.01,0.06,
122,8,xin,6,4,1,1,1,0,26.01,0,2.46,,,,,,
123,8,cf_1,3,,,5,,,26.0,,,,3,True,0.09,0.04,
124,8,cf_2,5,1,,,,,26.0,,,,3,True,0.09,0.02,
125,8,cf_3,4,,,6,,,25.5,,,,3,True,0.09,0.01,
126,8,cf_4,,,,7,,,21.72,,,,2,True,0.09,0.0,
127,8,cf_5,3,,,,,,24.54,7,,,3,False,0.09,0.05,
128,8,cf_6,,,,4,,,24.13,1,,,3,True,0.09,0.04,
129,8,cf_7,2,,,7,,,26.0,3,,,4,True,0.09,0.01,
130,8,cf_8,4,,,2,,,26.0,3,,,4,True,0.09,0.03,
131,8,cf_9,4,,4,4,,,25.92,,,,4,True,0.09,0.02,
132,8,cf_10,2,,,2,,,22.85,,,,3,True,0.09,0.01,
133,8,cf_11,,,6,4,,,25.77,2,,,4,True,0.09,0.01,
134,8,cf_12,2,,6,4,,,25.69,,,,4,False,0.09,0.05,
135,8,cf_13,2,,5,4,,,25.69,,,,4,True,0.09,0.01,
136,8,cf_14,,3,,3,,,25.6,3,,,4,True,0.09,0.01,
137,8,cf_15,,2,6,7,,,25.41,,,,4,False,0.09,0.09,

# picking correct CF

### expected

In [18]:
# Check directional constraints directly
# These features should only improve (increase) or stay the same
SHOULD_INCREASE = ["cgtsmok", "alcfreq", "dosprt"]

# These features should only improve (decrease) or stay the same
SHOULD_DECREASE = ["bmi", "etfruit", "eatveg", "slprl", "paccnois"]


print("Directional constraints:")
print(f"  Should increase (↑): {SHOULD_INCREASE}")
print(f"  Should decrease (↓): {SHOULD_DECREASE}")

Directional constraints:
  Should increase (↑): ['cgtsmok', 'alcfreq', 'dosprt']
  Should decrease (↓): ['bmi', 'etfruit', 'eatveg', 'slprl', 'paccnois']

In [19]:
# Check if CFs violate directional constraints
# First, ensure numeric columns are actually numeric for comparison
numeric_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# Create a working copy with numeric values
df_check = batch_cfcheck_df.copy()
for col in numeric_cols:
    df_check[col] = pd.to_numeric(df_check[col], errors="coerce")

# Extract baseline values per query_index
baseline_values = df_check[df_check["cf_id"] == "xin"].set_index("query_index")[numeric_cols]

# Check violations for each CF
def check_violations(row):
    if row["cf_id"] == "xin":
        return ""

    baseline = baseline_values.loc[row["query_index"]]
    violations = []

    # Check features that should increase
    for feat in SHOULD_INCREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] < baseline[feat]:
                violations.append(f"{feat}↓")

    # Check features that should decrease
    for feat in SHOULD_DECREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] > baseline[feat]:
                violations.append(f"{feat}↑")

    return "NO: " + ", ".join(violations) if violations else True

batch_cfcheck_df["Expected"] = df_check.apply(check_violations, axis=1)
batch_cfcheck_df.head(10)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.45,,,,,,
1,0,cf_1,,,,,,,16.7,,,,1,False,0.06,0.07,True
2,0,cf_2,,,,7,,,18.97,,,,2,False,0.06,0.07,True
3,0,cf_3,,,,,1,,18.94,,,,2,False,0.06,0.05,True
4,0,cf_4,,,,,,,18.93,5,,,2,False,0.06,0.04,True
5,0,cf_5,3,,,,,,18.93,,,,2,False,0.06,0.08,True
6,0,cf_6,3,,,,,,18.79,,,,2,False,0.06,0.08,True
7,0,cf_7,,,6,,,,18.55,,,,2,False,0.06,0.03,True
8,0,cf_8,,,,,,,18.53,5,,,2,False,0.06,0.05,True
9,0,cf_9,,,6,,,,17.55,,,,2,False,0.06,0.04,True

### is valid

In [20]:
# --- Select exactly one CF per query_index (random valid without violations) ---

# Split baseline and CF rows
df_xin = batch_cfcheck_df[batch_cfcheck_df["cf_id"] == "xin"]
df_cf  = batch_cfcheck_df[batch_cfcheck_df["cf_id"] != "xin"]

def select_random_cf(group):
    """Select one random CF that is valid and has no violations (Expected is empty)."""
    # First try: valid AND no violations
    good_cfs = group[(group["valid"] == True) & (group["Expected"] == "")]
    if len(good_cfs) > 0:
        return good_cfs.sample(n=1, random_state=42)

    # Fallback: any valid CF
    valid_cfs = group[group["valid"] == True]
    if len(valid_cfs) > 0:
        return valid_cfs.sample(n=1, random_state=42)

    # Last resort: first CF
    return group.iloc[[0]]

# Select one random CF per query_index
df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

# Combine baseline + selected CF
batch_cfcheck_df = pd.concat([df_xin, df_cf_selected], ignore_index=True)

# Ensure xin appears before CF for each query_index
batch_cfcheck_df["is_xin"] = (batch_cfcheck_df["cf_id"] == "xin").astype(int)
batch_cfcheck_df = (
    batch_cfcheck_df
    .sort_values(["query_index", "is_xin"], ascending=[True, False])
    .drop(columns="is_xin")
)
batch_cfcheck_df

/tmp/ipykernel_32810/2325069138.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,2.45,,,,,,
9,0,cf_13,,,5,,,,18.96,2,,,3,True,0.06,0.03,True
1,1,xin,3,4,1,2,3,0,22.38,0,2.56,,,,,,
10,1,cf_3,,,,,1,,,1,,,2,True,0.15,0.05,True
2,2,xin,5,3,1,1,4,0,22.69,7,2.72,,,,,,
11,2,cf_13,1,,,5,2,,22.68,,,,4,True,0.16,0.02,True
3,3,xin,3,3,6,6,2,0,24.34,1,2.91,,,,,,
12,3,cf_2,,,,,,,24.33,,,,1,True,0.02,0.0,True
4,4,xin,5,4,2,7,1,0,21.26,3,3.12,,,,,,
13,4,cf_2,,,6,,,,,,,,1,True,0.03,0.0,True
5,5,xin,2,2,1,2,4,0,27.99,0,2.91,,,,,,
14,5,cf_9,,,2,,,,,2,,,2,True,0.33,0.09,True
6,6,xin,2,3,5,4,1,0,27.68,4,2.34,,,,,,
15,6,cf_12,,,,5,,,26.48,,,,2,True,0.15,0.05,True
7,7,xin,2,3,6,3,1,0,20.44,2,2.44,,,,,,
16,7,cf_8,,,,,,,18.84,,,,1,True,0.01,0.0,True
8,8,xin,6,4,1,1,1,0,26.01,0,2.46,,,,,,
17,8,cf_13,2,,5,4,,,25.69,,,,4,True,0.09,0.01,True