### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "xgb_optimized" / "XGBoost_thres0.1_2026-05-07" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.16,,,,,
1,0,cf_1,,,,7,,,18.9745,,,0.876,2,False,0.0743,0.0972
2,0,cf_2,,,6,,,,17.4904,,,1.0,2,False,0.0743,0.044
3,0,cf_3,,,,7,,,18.9745,7,,0.876,3,True,0.0743,0.0051
4,0,cf_4,,,,,1,,18.9619,5,,0.8771,3,True,0.0743,0.0022
5,0,cf_5,,,5,,,,18.9619,2,,0.8771,3,True,0.0743,0.0145
6,1,xin,3,4,1,2,3,0,22.3757,0,1.17,,,,,
7,1,cf_1,,,,,,,22.3757,,,0.8796,1,False,0.0484,0.0484
8,1,cf_2,,,2,,1,,22.3757,,,0.8796,3,False,0.0484,0.0534
9,1,cf_3,,,,3,1,,22.3757,,,0.8796,3,False,0.0484,0.0256
10,1,cf_4,,,,,1,,22.3757,1,,0.8796,3,False,0.0484,0.0503
11,1,cf_5,,3,,,,,22.3757,6,,0.8796,3,False,0.0484,0.0552
12,1,cf_6,2,,,,1,,22.3757,,,0.8796,3,True,0.0484,0.0105
13,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
14,2,cf_1,,,,,,,18.0821,,,1.0,1,False,0.0647,0.0994
15,2,cf_2,3,,,,2,,22.68,,,0.8754,3,False,0.0647,0.0569
16,2,cf_3,,,,3,2,,22.6757,,,0.8755,3,True,0.0647,0.0185
17,2,cf_4,,,,6,1,,22.6757,,,0.8755,3,False,0.0647,0.0406
18,2,cf_5,1,1,,,2,,22.68,,,0.8754,4,True,0.0647,0.0047
19,2,cf_6,4,,,4,2,,22.68,,,0.8754,4,True,0.0647,0.0063
20,2,cf_7,1,,2,,3,,22.68,,,0.8754,4,True,0.0647,0.0044
21,2,cf_8,,,2,6,1,,22.68,,,0.8754,4,True,0.0647,0.0091
22,3,xin,3,3,6,6,2,0,24.3418,1,1.3,,,,,
23,3,cf_1,,,,,,,24.3375,,,0.8834,1,False,0.0048,0.0048
24,3,cf_2,,,,7,,,24.3375,,,0.8834,2,False,0.0048,0.0447
25,3,cf_3,,,,,1,,24.3375,,,0.8834,2,False,0.0048,0.0111
26,3,cf_4,2,,,,,,24.3375,,,0.8834,2,False,0.0048,0.0189
27,3,cf_5,,,,,,,24.3375,4,,0.8834,2,False,0.0048,0.0342
28,3,cf_6,,,,,,,24.3375,3,,0.8834,2,False,0.0048,0.0071
29,3,cf_7,,,,,,,24.2779,6,,1.0,2,False,0.0048,0.0656
30,4,xin,5,4,2,7,1,0,21.2585,3,1.39,,,,,
31,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0259,0.0295
32,4,cf_2,,,6,,,,21.2585,,,0.9868,2,False,0.0259,0.015
33,4,cf_3,,3,,,,,21.2585,,,0.9868,2,False,0.0259,0.0409
34,4,cf_4,,,3,,,,21.2585,,,0.9868,2,False,0.0259,0.0132
35,4,cf_5,4,,,,,,21.2585,,,0.9868,2,True,0.0259,0.007
36,4,cf_6,3,,,,,,21.2585,,,0.9868,2,True,0.0259,0.0118
37,4,cf_7,1,,6,,,,21.2585,,,0.9868,3,True,0.0259,0.009
38,4,cf_8,2,,5,,,,21.2585,,,0.9868,3,True,0.0259,0.0023
39,4,cf_9,3,3,,,,,21.2585,,,0.9868,3,True,0.0259,0.0093
40,4,cf_10,1,3,,,,,21.2585,,,0.9868,3,True,0.0259,0.0047
41,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,,
42,5,cf_1,,,,,,,27.9904,,,1.0857,1,False,0.0272,0.0272
43,5,cf_2,1,,,,,,27.9904,,,1.0857,2,False,0.0272,0.021
44,5,cf_3,,,,,1,,27.9904,,,1.0857,2,False,0.0272,0.019
45,5,cf_4,,,4,,,,27.9904,,,1.0857,2,False,0.0272,0.0506
46,5,cf_5,,,6,7,,,27.9904,,,1.0857,3,False,0.0272,0.0632
47,5,cf_6,,,,,2,,27.9904,2,,1.0857,3,True,0.0272,0.0009
48,5,cf_7,,,,5,2,,27.9904,,,1.0857,3,True,0.0272,0.0037
49,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
50,6,cf_1,,,,,,,24.5883,,,0.9626,1,False,0.0152,0.0673
51,6,cf_2,,,,6,,,27.5649,,,0.8783,2,True,0.0152,0.0015
52,6,cf_3,,,,,,,24.4251,,,0.9672,1,False,0.0152,0.0386
53,6,cf_4,,,,,,,24.253,,,0.9721,1,False,0.0152,0.0161
54,6,cf_5,,,,,,,24.1595,,,0.9747,1,False,0.0152,0.0164
55,6,cf_6,,,,,,,24.0198,,,0.9787,1,False,0.0152,0.021
56,6,cf_7,,,,,,,23.2676,,,1.0,1,False,0.0152,0.0383
57,6,cf_8,,,6,,,,26.2633,,,0.9152,2,False,0.0152,0.0432
58,7,xin,2,3,6,3,1,0,20.4382,2,1.07,,,,,
59,7,cf_1,,,,,,,19.5066,,,0.95,1,True,0.2012,0.0231
60,7,cf_2,,,,,,,19.3732,,,0.9607,1,True,0.2012,0.0221
61,7,cf_3,,,,,,,19.1053,,,0.9823,1,True,0.2012,0.0107
62,7,cf_4,,,,,,,18.8851,,,1.0,1,True,0.2012,0.0102
63,7,cf_5,,,,7,,,20.4294,,,0.8757,2,True,0.2012,0.0322
64,7,cf_6,,2,,,,,20.4294,,,0.8757,2,True,0.2012,0.0381
65,7,cf_7,,1,,,,,20.4294,,,0.8757,2,True,0.2012,0.0336
66,7,cf_8,,,,,,,20.4284,5,,0.8758,2,True,0.2012,0.0091
67,8,xin,6,4,1,1,1,0,26.0146,0,1.18,,,,,
68,8,cf_1,,,,,,,25.0903,,,0.9299,1,False,0.1068,0.0692
69,8,cf_2,,,3,4,,,26.0044,,,0.8756,3,True,0.1068,0.0043
70,8,cf_3,3,,,5,,,26.0044,,,0.8756,3,False,0.1068,0.0611
71,8,cf_4,,3,,7,,,25.7661,,,0.8898,3,True,0.1068,0.022
72,8,cf_5,4,,,6,,,25.5892,,,0.9003,3,False,0.1068,0.0992
73,8,cf_6,1,3,,,,,24.3291,,,0.9752,3,True,0.1068,0.002
74,8,cf_7,1,1,,,,,24.3291,,,0.9752,3,True,0.1068,0.0093
75,8,cf_8,,,,7,,,23.9119,4,,1.0,3,True,0.1068,0.0001
76,8,cf_9,1,2,,,,,26.0044,7,,0.8756,4,True,0.1068,0.003
77,8,cf_10,2,,,2,,,26.0044,3,,0.8756,4,True,0.1068,0.0483

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.16,,,,,
9,0,cf_3,,,,7,,,18.9745,7,,0.876,3,True,0.0743,0.0051
10,0,cf_4,,,,,1,,18.9619,5,,0.8771,3,True,0.0743,0.0022
11,0,cf_5,,,5,,,,18.9619,2,,0.8771,3,True,0.0743,0.0145
1,1,xin,3,4,1,2,3,0,22.3757,0,1.17,,,,,
12,1,cf_6,2,,,,1,,22.3757,,,0.8796,3,True,0.0484,0.0105
2,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
13,2,cf_3,,,,3,2,,22.6757,,,0.8755,3,True,0.0647,0.0185
14,2,cf_5,1,1,,,2,,22.68,,,0.8754,4,True,0.0647,0.0047
15,2,cf_6,4,,,4,2,,22.68,,,0.8754,4,True,0.0647,0.0063
16,2,cf_7,1,,2,,3,,22.68,,,0.8754,4,True,0.0647,0.0044
17,2,cf_8,,,2,6,1,,22.68,,,0.8754,4,True,0.0647,0.0091
3,3,xin,3,3,6,6,2,0,24.3418,1,1.3,,,,,
42,3,cf_1,,,,,,,24.3375,,,0.8834,1,False,0.0048,0.0048
4,4,xin,5,4,2,7,1,0,21.2585,3,1.39,,,,,
18,4,cf_5,4,,,,,,21.2585,,,0.9868,2,True,0.0259,0.007
19,4,cf_6,3,,,,,,21.2585,,,0.9868,2,True,0.0259,0.0118
20,4,cf_7,1,,6,,,,21.2585,,,0.9868,3,True,0.0259,0.009
21,4,cf_8,2,,5,,,,21.2585,,,0.9868,3,True,0.0259,0.0023
22,4,cf_9,3,3,,,,,21.2585,,,0.9868,3,True,0.0259,0.0093
23,4,cf_10,1,3,,,,,21.2585,,,0.9868,3,True,0.0259,0.0047
5,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,,
24,5,cf_6,,,,,2,,27.9904,2,,1.0857,3,True,0.0272,0.0009
25,5,cf_7,,,,5,2,,27.9904,,,1.0857,3,True,0.0272,0.0037
6,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
26,6,cf_2,,,,6,,,27.5649,,,0.8783,2,True,0.0152,0.0015
7,7,xin,2,3,6,3,1,0,20.4382,2,1.07,,,,,
27,7,cf_1,,,,,,,19.5066,,,0.95,1,True,0.2012,0.0231
28,7,cf_2,,,,,,,19.3732,,,0.9607,1,True,0.2012,0.0221
29,7,cf_3,,,,,,,19.1053,,,0.9823,1,True,0.2012,0.0107
30,7,cf_4,,,,,,,18.8851,,,1.0,1,True,0.2012,0.0102
31,7,cf_5,,,,7,,,20.4294,,,0.8757,2,True,0.2012,0.0322
32,7,cf_6,,2,,,,,20.4294,,,0.8757,2,True,0.2012,0.0381
33,7,cf_7,,1,,,,,20.4294,,,0.8757,2,True,0.2012,0.0336
34,7,cf_8,,,,,,,20.4284,5,,0.8758,2,True,0.2012,0.0091
8,8,xin,6,4,1,1,1,0,26.0146,0,1.18,,,,,
35,8,cf_2,,,3,4,,,26.0044,,,0.8756,3,True,0.1068,0.0043
36,8,cf_4,,3,,7,,,25.7661,,,0.8898,3,True,0.1068,0.022
37,8,cf_6,1,3,,,,,24.3291,,,0.9752,3,True,0.1068,0.002
38,8,cf_7,1,1,,,,,24.3291,,,0.9752,3,True,0.1068,0.0093
39,8,cf_8,,,,7,,,23.9119,4,,1.0,3,True,0.1068,0.0001
40,8,cf_9,1,2,,,,,26.0044,7,,0.8756,4,True,0.1068,0.003
41,8,cf_10,2,,,2,,,26.0044,3,,0.8756,4,True,0.1068,0.0483

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.16,,,,,
9,0,cf_3,,,,7,,,18.9745,7,,0.876,3,True,0.0743,0.0051
1,1,xin,3,4,1,2,3,0,22.3757,0,1.17,,,,,
10,1,cf_6,2,,,,1,,22.3757,,,0.8796,3,True,0.0484,0.0105
2,2,xin,5,3,1,1,4,0,22.694,7,1.25,,,,,
11,2,cf_5,1,1,,,2,,22.68,,,0.8754,4,True,0.0647,0.0047
3,3,xin,3,3,6,6,2,0,24.3418,1,1.3,,,,,
12,3,cf_1,,,,,,,24.3375,,,0.8834,1,False,0.0048,0.0048
4,4,xin,5,4,2,7,1,0,21.2585,3,1.39,,,,,
13,4,cf_5,4,,,,,,21.2585,,,0.9868,2,True,0.0259,0.007
5,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,,
14,5,cf_7,,,,5,2,,27.9904,,,1.0857,3,True,0.0272,0.0037
6,6,xin,2,3,5,4,1,0,27.6817,4,1.11,,,,,
15,6,cf_2,,,,6,,,27.5649,,,0.8783,2,True,0.0152,0.0015
7,7,xin,2,3,6,3,1,0,20.4382,2,1.07,,,,,
16,7,cf_2,,,,,,,19.3732,,,0.9607,1,True,0.2012,0.0221
8,8,xin,6,4,1,1,1,0,26.0146,0,1.18,,,,,
17,8,cf_2,,,3,4,,,26.0044,,,0.8756,3,True,0.1068,0.0043

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0051
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7

--- cf_4 ---
Predicted risk: 0.0022
Valid: True
Changes:
  slprl: 2 → 1
  bmi: 18.9866 → 18.9619
  dosprt: 0 → 5

--- cf_5 ---
Predicted risk: 0.0145
Valid: True
Changes:
  cgtsmok: 3 → 5
  bmi: 18.9866 → 18.9619
  dosprt: 0 → 2


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.0105
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0185
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.0047
Valid: True
Changes:
  etfruit: 5 → 1
  eatveg: 3 → 1
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_6 ---
Predicted risk: 0.0063
Valid: True
Changes:
  etfruit: 5 → 4
  alcfreq: 1 → 4
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_7 ---
Predicted risk: 0.0044
Valid: True
Changes:
  etfruit: 5 → 1
  cgtsmok: 1 → 2
  slprl: 4 → 3
  bmi: 22.694 → 22.68

--- cf_8 ---
Predicted risk: 0.0091
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0048
Valid: False
Changes:
  bmi: 24.3418 → 24.3375


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_5 ---
Predicted risk: 0.007
Valid: True
Changes:
  etfruit: 5 → 4

--- cf_6 ---
Predicted risk: 0.0118
Valid: True
Changes:
  etfruit: 5 → 3

--- cf_7 ---
Predicted risk: 0.009
Valid: True
Changes:
  etfruit: 5 → 1
  cgtsmok: 2 → 6

--- cf_8 ---
Predicted risk: 0.0023
Valid: True
Changes:
  etfruit: 5 → 2
  cgtsmok: 2 → 5

--- cf_9 ---
Predicted risk: 0.0093
Valid: True
Changes:
  etfruit: 5 → 3
  eatveg: 4 → 3

--- cf_10 ---
Predicted risk: 0.0047
Valid: True
Changes:
  etfruit: 5 → 1
  eatveg: 4 → 3


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.0009
Valid: True
Changes:
  slprl: 4 → 2
  dosprt: 0 → 2

--- cf_7 ---
Predicted risk: 0.0037
Valid: True
Changes:
  alcfreq: 2 → 5
  slprl: 4 → 2


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0015
Valid: True
Changes:
  alcfreq: 4 → 6
  bmi: 27.6817 → 27.5649


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0231
Valid: True
Changes:
  bmi: 20.4382 → 19.5066

--- cf_2 ---
Predicted risk: 0.0221
Valid: True
Changes:
  bmi: 20.4382 → 19.3732

--- cf_3 ---
Predicted risk: 0.0107
Valid: True
Changes:
  bmi: 20.4382 → 19.1053

--- cf_4 ---
Predicted risk: 0.0102
Valid: True
Changes:
  bmi: 20.4382 → 18.8851

--- cf_5 ---
Predicted risk: 0.0322
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294

--- cf_6 ---
Predicted risk: 0.0381
Valid: True
Changes:
  eatveg: 3 → 2
  bmi: 20.4382 → 20.4294

--- cf_7 ---
Predicted risk: 0.0336
Valid: True
Changes:
  eatveg: 3 → 1
  bmi: 20.4382 → 20.4294

--- cf_8 ---
Predicted risk: 0.0091
Valid: True
Changes:
  bmi: 20.4382 → 20.4284
  dosprt: 2 → 5


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0043
Valid: True
Changes:
  cgtsmok: 1 → 3
  alcfreq: 1 → 4
  bmi: 26.0146 → 26.0044

--- cf_4 ---
Predicted risk: 0.022
Valid: True
Changes:
  eatveg: 4 → 3
  alcfreq: 1 → 7
  bmi: 26.0146 → 25.7661

--- cf_6 ---
Predicted risk: 0.002
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 3
  bmi: 26.0146 → 24.3291

--- cf_7 ---
Predicted risk: 0.0093
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 24.3291

--- cf_8 ---
Predicted risk: 0.0001
Valid: True
Changes:
  alcfreq: 1 → 7
  bmi: 26.0146 → 23.9119
  dosprt: 0 → 4

--- cf_9 ---
Predicted risk: 0.003
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 7

--- cf_10 ---
Predicted risk: 0.0483
Valid: True
Changes:
  etfruit: 6 → 2
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3


=== Query index '9' ===
No recommendations available.