In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
batch_cfcheck_data = CF_OUTPUTS / "xgboost_genetic_2026-04-17" / "genetic_annotated_hltprhc.csv"
batch_cfcheck_df = pd.read_csv(batch_cfcheck_data)

In [ ]:
pd.set_option("display.max_rows", None)

In [ ]:
batch_cfcheck_df = batch_cfcheck_df.drop(columns=["hltprhc", "target_risk"])

In [ ]:

batch_cfcheck_df["cf_id"] = batch_cfcheck_df["cf_id"].replace({"original": "xin"})

batch_cfcheck_df = batch_cfcheck_df.rename(columns={
    "original_risk": "risk_before",
    "predicted_risk" : "predicted_risk_after",
    "meets_target_risk" : "valid",
})

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,0.025955,NaN,NaN,1.22
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.986590,NaN,0.025955,0.012272,True,NaN
2,0,cf_1,NaN,1.0,5.0,NaN,1.0,NaN,18.986590,NaN,0.025955,0.002570,True,NaN
3,0,cf_1,NaN,NaN,6.0,7.0,NaN,NaN,18.974530,NaN,0.025955,0.142825,False,NaN

In [ ]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

batch_cfcheck_df = fix_cf_id(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.986591,0.0,0.025955,NaN,NaN,1.22
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,18.986590,NaN,0.025955,0.012272,True,NaN
2,0,cf_2,NaN,1.0,5.0,NaN,1.0,NaN,18.986590,NaN,0.025955,0.002570,True,NaN
3,0,cf_3,NaN,NaN,6.0,7.0,NaN,NaN,18.974530,NaN,0.025955,0.142825,False,NaN
4,0,cf_4,NaN,NaN,5.0,NaN,NaN,NaN,19.031140,4.0,0.025955,0.008059,True,NaN
5,0,cf_5,2.0,4.0,6.0,1.0,NaN,NaN,18.986590,NaN,0.025955,0.048545,False,NaN
6,0,cf_6,2.0,1.0,5.0,NaN,1.0,NaN,18.986590,NaN,0.025955,0.003719,True,NaN
7,0,cf_7,6.0,1.0,5.0,7.0,NaN,NaN,18.986590,NaN,0.025955,0.001736,True,NaN
8,0,cf_8,2.0,NaN,6.0,5.0,NaN,NaN,18.986590,5.0,0.025955,0.079886,False,NaN
9,0,cf_9,1.0,1.0,4.0,NaN,1.0,NaN,18.986590,NaN,0.025955,0.017961,False,NaN
10,0,cf_10,1.0,1.0,4.0,NaN,NaN,1.0,18.986590,NaN,0.025955,0.018000,False,NaN
11,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.375680,0.0,0.249715,NaN,NaN,1.30
12,1,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,22.375680,NaN,0.249715,0.249715,False,NaN
13,1,cf_2,NaN,NaN,NaN,NaN,1.0,NaN,22.375680,NaN,0.249715,0.069968,True,NaN
14,1,cf_3,2.0,NaN,NaN,NaN,1.0,NaN,22.375680,NaN,0.249715,0.036140,True,NaN
15,1,cf_4,1.0,NaN,NaN,4.0,4.0,NaN,22.375680,NaN,0.249715,0.009956,True,NaN
16,1,cf_5,NaN,2.0,NaN,NaN,2.0,NaN,22.375680,2.0,0.249715,0.030194,True,NaN
17,1,cf_6,NaN,NaN,NaN,3.0,1.0,NaN,22.386310,NaN,0.249715,0.053435,True,NaN
18,1,cf_7,NaN,1.0,2.0,4.0,NaN,NaN,22.375680,7.0,0.249715,0.019251,True,NaN
19,1,cf_8,1.0,6.0,NaN,4.0,1.0,NaN,22.375680,NaN,0.249715,0.144666,False,NaN
20,1,cf_9,2.0,NaN,6.0,NaN,1.0,NaN,22.375680,5.0,0.249715,0.044818,True,NaN
21,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.694019,7.0,0.217967,NaN,NaN,1.08
22,2,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,22.694020,NaN,0.217967,0.217967,False,NaN
23,2,cf_2,3.0,NaN,NaN,NaN,2.0,NaN,22.679950,NaN,0.217967,0.139352,False,NaN
24,2,cf_3,1.0,NaN,NaN,NaN,2.0,NaN,22.675740,NaN,0.217967,0.066151,True,NaN
25,2,cf_4,3.0,NaN,5.0,4.0,2.0,NaN,22.694020,NaN,0.217967,0.034765,True,NaN
26,2,cf_5,3.0,NaN,6.0,2.0,1.0,NaN,22.694020,NaN,0.217967,0.030050,True,NaN
27,2,cf_6,4.0,NaN,6.0,7.0,2.0,NaN,22.694020,NaN,0.217967,0.045147,True,NaN
28,2,cf_7,NaN,NaN,2.0,2.0,1.0,NaN,22.679950,NaN,0.217967,0.012358,True,NaN
29,2,cf_8,3.0,1.0,NaN,NaN,1.0,NaN,22.675740,NaN,0.217967,0.022238,True,NaN

In [ ]:
# round BMI to 2 decimal places, and set to NaN if equal to xin after rounding
def round_and_clear_bmi(df):
    df = df.copy()

    # Round BMI to 2 decimals for all rows
    df['bmi'] = df['bmi'].round(2)

    # For each query_index, get the xin BMI and compare
    for query_idx in df['query_index'].unique():
        query_mask = df['query_index'] == query_idx
        xin_mask = query_mask & (df['cf_id'] == 'xin')
        cf_mask = query_mask & (df['cf_id'] != 'xin')

        # Get the xin BMI value for this query
        xin_bmi = df.loc[xin_mask, 'bmi'].values[0]

        # Set cf BMI to NaN where it equals xin BMI
        equal_mask = cf_mask & (df['bmi'] == xin_bmi)
        df.loc[equal_mask, 'bmi'] = np.nan

    return df

batch_cfcheck_df = round_and_clear_bmi(batch_cfcheck_df)
batch_cfcheck_df.head(30)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4.0,3.0,3.0,4.0,2.0,0.0,18.99,0.0,0.025955,NaN,NaN,1.22
1,0,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.025955,0.012272,True,NaN
2,0,cf_2,NaN,1.0,5.0,NaN,1.0,NaN,NaN,NaN,0.025955,0.002570,True,NaN
3,0,cf_3,NaN,NaN,6.0,7.0,NaN,NaN,18.97,NaN,0.025955,0.142825,False,NaN
4,0,cf_4,NaN,NaN,5.0,NaN,NaN,NaN,19.03,4.0,0.025955,0.008059,True,NaN
5,0,cf_5,2.0,4.0,6.0,1.0,NaN,NaN,NaN,NaN,0.025955,0.048545,False,NaN
6,0,cf_6,2.0,1.0,5.0,NaN,1.0,NaN,NaN,NaN,0.025955,0.003719,True,NaN
7,0,cf_7,6.0,1.0,5.0,7.0,NaN,NaN,NaN,NaN,0.025955,0.001736,True,NaN
8,0,cf_8,2.0,NaN,6.0,5.0,NaN,NaN,NaN,5.0,0.025955,0.079886,False,NaN
9,0,cf_9,1.0,1.0,4.0,NaN,1.0,NaN,NaN,NaN,0.025955,0.017961,False,NaN
10,0,cf_10,1.0,1.0,4.0,NaN,NaN,1.0,NaN,NaN,0.025955,0.018000,False,NaN
11,1,xin,3.0,4.0,1.0,2.0,3.0,0.0,22.38,0.0,0.249715,NaN,NaN,1.30
12,1,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.249715,0.249715,False,NaN
13,1,cf_2,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.249715,0.069968,True,NaN
14,1,cf_3,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.249715,0.036140,True,NaN
15,1,cf_4,1.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,0.249715,0.009956,True,NaN
16,1,cf_5,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2.0,0.249715,0.030194,True,NaN
17,1,cf_6,NaN,NaN,NaN,3.0,1.0,NaN,22.39,NaN,0.249715,0.053435,True,NaN
18,1,cf_7,NaN,1.0,2.0,4.0,NaN,NaN,NaN,7.0,0.249715,0.019251,True,NaN
19,1,cf_8,1.0,6.0,NaN,4.0,1.0,NaN,NaN,NaN,0.249715,0.144666,False,NaN
20,1,cf_9,2.0,NaN,6.0,NaN,1.0,NaN,NaN,5.0,0.249715,0.044818,True,NaN
21,2,xin,5.0,3.0,1.0,1.0,4.0,0.0,22.69,7.0,0.217967,NaN,NaN,1.08
22,2,cf_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.217967,0.217967,False,NaN
23,2,cf_2,3.0,NaN,NaN,NaN,2.0,NaN,22.68,NaN,0.217967,0.139352,False,NaN
24,2,cf_3,1.0,NaN,NaN,NaN,2.0,NaN,22.68,NaN,0.217967,0.066151,True,NaN
25,2,cf_4,3.0,NaN,5.0,4.0,2.0,NaN,NaN,NaN,0.217967,0.034765,True,NaN
26,2,cf_5,3.0,NaN,6.0,2.0,1.0,NaN,NaN,NaN,0.217967,0.030050,True,NaN
27,2,cf_6,4.0,NaN,6.0,7.0,2.0,NaN,NaN,NaN,0.217967,0.045147,True,NaN
28,2,cf_7,NaN,NaN,2.0,2.0,1.0,NaN,22.68,NaN,0.217967,0.012358,True,NaN
29,2,cf_8,3.0,1.0,NaN,NaN,1.0,NaN,22.68,NaN,0.217967,0.022238,True,NaN

In [ ]:
int_columns = [
    "etfruit",
    "eatveg",
    "cgtsmok",
    "alcfreq",
    "slprl",
    "paccnois",
    "dosprt",
]

float_columns = [
    "bmi",
    "risk_before",
    "predicted_risk_after",
]

In [ ]:
batch_cfcheck_df[int_columns] = batch_cfcheck_df[int_columns].astype("Int64")

In [ ]:
batch_cfcheck_df[float_columns] = batch_cfcheck_df[float_columns].round(2)

batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,0.03,NaN,NaN,1.22
1,0,cf_1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,0.03,0.01,True,NaN
2,0,cf_2,<NA>,1,5,<NA>,1,<NA>,NaN,<NA>,0.03,0.00,True,NaN
3,0,cf_3,<NA>,<NA>,6,7,<NA>,<NA>,18.97,<NA>,0.03,0.14,False,NaN

In [ ]:
batch_cfcheck_df[int_columns] = (
    batch_cfcheck_df[int_columns]
    .astype("string")
    .fillna("")
)

In [ ]:
batch_cfcheck_df = batch_cfcheck_df.replace({np.nan : ""})
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,0.03,,,1.22
1,0,cf_1,,,,,,,,,0.03,0.01,True,
2,0,cf_2,,1,5,,1,,,,0.03,0.0,True,
3,0,cf_3,,,6,7,,,18.97,,0.03,0.14,False,

In [ ]:
mask = batch_cfcheck_df["cf_id"] == "xin"
batch_cfcheck_df.loc[mask, "risk_before"] = ""
batch_cfcheck_df.head(4)

/tmp/ipykernel_39625/1160248817.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  batch_cfcheck_df.loc[mask, "risk_before"] = ""

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec
0,0,xin,4,3,3,4,2,0,18.99,0,,,,1.22
1,0,cf_1,,,,,,,,,0.03,0.01,True,
2,0,cf_2,,1,5,,1,,,,0.03,0.0,True,
3,0,cf_3,,,6,7,,,18.97,,0.03,0.14,False,

In [ ]:
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# 1. Beräkna Nchanged endast för CF-rader
mask_cf = batch_cfcheck_df["cf_id"] != "xin"

batch_cfcheck_df.loc[mask_cf, "Nchanged"] = (
    batch_cfcheck_df.loc[mask_cf, feature_cols] != ""
).sum(axis=1)

# 2. Konvertera kolumnen till ren string
batch_cfcheck_df["Nchanged"] = batch_cfcheck_df["Nchanged"].astype("string")

# 3. Baseline ska vara tom
batch_cfcheck_df.loc[batch_cfcheck_df["cf_id"] == "xin", "Nchanged"] = ""

In [ ]:
batch_cfcheck_df.head(4)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,risk_before,predicted_risk_after,valid,cf_gen_time_sec,Nchanged
0,0,xin,4,3,3,4,2,0,18.99,0,,,,1.22,
1,0,cf_1,,,,,,,,,0.03,0.01,True,,0
2,0,cf_2,,1,5,,1,,,,0.03,0.0,True,,3
3,0,cf_3,,,6,7,,,18.97,,0.03,0.14,False,,3

In [ ]:
batch_cfcheck_df["Gower"] = ""
batch_cfcheck_df["Expected"] = ""

In [ ]:
order = ["query_index", "cf_id"] + feature_cols + ["cf_gen_time_sec", "Gower", "Nchanged", "valid", "risk_before", "predicted_risk_after", "Expected"]

batch_cfcheck_df = batch_cfcheck_df[order]
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.22,,,,,,
1,0,cf_1,,,,,,,,,,,0,True,0.03,0.01,
2,0,cf_2,,1,5,,1,,,,,,3,True,0.03,0.0,
3,0,cf_3,,,6,7,,,18.97,,,,3,False,0.03,0.14,
4,0,cf_4,,,5,,,,19.03,4,,,3,True,0.03,0.01,
5,0,cf_5,2,4,6,1,,,,,,,4,False,0.03,0.05,
6,0,cf_6,2,1,5,,1,,,,,,4,True,0.03,0.0,
7,0,cf_7,6,1,5,7,,,,,,,4,True,0.03,0.0,
8,0,cf_8,2,,6,5,,,,5,,,4,False,0.03,0.08,
9,0,cf_9,1,1,4,,1,,,,,,4,False,0.03,0.02,
10,0,cf_10,1,1,4,,,1,,,,,4,False,0.03,0.02,
11,1,xin,3,4,1,2,3,0,22.38,0,1.3,,,,,,
12,1,cf_1,,,,,,,,,,,0,False,0.25,0.25,
13,1,cf_2,,,,,1,,,,,,1,True,0.25,0.07,
14,1,cf_3,2,,,,1,,,,,,2,True,0.25,0.04,
15,1,cf_4,1,,,4,4,,,,,,3,True,0.25,0.01,
16,1,cf_5,,2,,,2,,,2,,,3,True,0.25,0.03,
17,1,cf_6,,,,3,1,,22.39,,,,3,True,0.25,0.05,
18,1,cf_7,,1,2,4,,,,7,,,4,True,0.25,0.02,
19,1,cf_8,1,6,,4,1,,,,,,4,False,0.25,0.14,
20,1,cf_9,2,,6,,1,,,5,,,4,True,0.25,0.04,
21,2,xin,5,3,1,1,4,0,22.69,7,1.08,,,,,,
22,2,cf_1,,,,,,,,,,,0,False,0.22,0.22,
23,2,cf_2,3,,,,2,,22.68,,,,3,False,0.22,0.14,
24,2,cf_3,1,,,,2,,22.68,,,,3,True,0.22,0.07,
25,2,cf_4,3,,5,4,2,,,,,,4,True,0.22,0.03,
26,2,cf_5,3,,6,2,1,,,,,,4,True,0.22,0.03,
27,2,cf_6,4,,6,7,2,,,,,,4,True,0.22,0.05,
28,2,cf_7,,,2,2,1,,22.68,,,,4,True,0.22,0.01,
29,2,cf_8,3,1,,,1,,22.68,,,,4,True,0.22,0.02,
30,2,cf_9,2,,,,2,,22.68,3,,,4,True,0.22,0.05,
31,3,xin,3,3,6,6,2,0,24.34,1,1.18,,,,,,
32,3,cf_1,,,,,,,,,,,0,False,0.07,0.07,
33,3,cf_2,,,,,,,,2,,,1,False,0.07,0.06,
34,3,cf_3,1,,,3,,,,,,,2,False,0.07,0.1,
35,3,cf_4,2,,,,,,,2,,,2,False,0.07,0.05,
36,3,cf_5,,,,5,,,,4,,,2,False,0.07,0.07,
37,3,cf_6,4,4,,,,,,,,,2,False,0.07,0.12,
38,3,cf_7,,,,,,,,3,,,1,False,0.07,0.05,
39,3,cf_8,,,3,7,,,,3,,,3,False,0.07,0.05,
40,3,cf_9,2,,,1,,,,7,,,3,False,0.07,0.12,
41,3,cf_10,2,,,7,,,,4,,,3,False,0.07,0.05,
42,4,xin,5,4,2,7,1,0,21.26,3,1.31,,,,,,
43,4,cf_1,,,,,,,,,,,0,True,0.08,0.01,
44,4,cf_2,,2,5,,,,,,,,2,True,0.08,0.01,
45,4,cf_3,2,3,,,,,,,,,2,True,0.08,0.03,
46,4,cf_4,3,3,,,,,,,,,2,True,0.08,0.02,
47,4,cf_5,1,,4,4,,,,,,,3,True,0.08,0.02,
48,4,cf_6,1,,3,3,,,,,,,3,True,0.08,0.02,
49,4,cf_7,2,2,4,,,,,,,,3,True,0.08,0.03,
50,4,cf_8,4,,,2,2,,,,,,3,True,0.08,0.02,
51,5,xin,2,2,1,2,4,0,27.99,0,1.19,,,,,,
52,5,cf_1,,,,,,,,,,,0,False,0.05,0.05,
53,5,cf_2,,,,3,,,,6,,,2,True,0.05,0.02,
54,5,cf_3,,1,,3,,,,3,,,3,False,0.05,0.14,
55,5,cf_4,1,,,,,,28.01,7,,,3,True,0.05,0.01,
56,5,cf_5,,,,1,1,,28.01,,,,3,True,0.05,0.02,
57,5,cf_6,,3,3,7,2,,,,,,4,False,0.05,0.11,
58,5,cf_7,,3,4,,3,,,4,,,4,False,0.05,0.1,
59,5,cf_8,,3,4,7,,,,5,,,4,False,0.05,0.09,
60,5,cf_9,3,4,,7,1,,,,,,4,False,0.05,0.09,
61,5,cf_10,,3,4,6,1,,,,,,4,False,0.05,0.2,
62,6,xin,2,3,5,4,1,0,27.68,4,0.98,,,,,,
63,6,cf_1,,,,,,,,,,,0,False,0.05,0.12,
64,6,cf_2,3,,,,,,,6,,,2,False,0.05,0.09,
65,6,cf_3,,,6,,,,,5,,,2,False,0.05,0.1,
66,6,cf_4,,,1,,,,,1,,,2,False,0.05,0.07,
67,6,cf_5,,,,1,,,,0,,,2,False,0.05,0.18,
68,6,cf_6,,,,7,,,,7,,,2,False,0.05,0.15,
69,6,cf_7,,,,,4,,,2,,,2,False,0.05,0.06,
70,6,cf_8,,2,,,,,,3,,,2,False,0.05,0.04,
71,6,cf_9,,,4,,2,,,5,,,3,False,0.05,0.18,
72,6,cf_10,1,5,4,,,,,,,,3,False,0.05,0.03,
73,7,xin,2,3,6,3,1,0,20.44,2,1.16,,,,,,
74,7,cf_1,,,,,,,,,,,0,False,0.06,0.06,
75,7,cf_2,,,,2,,,,4,,,2,False,0.06,0.03,
76,7,cf_3,,,1,,2,,,,,,2,True,0.06,0.02,
77,7,cf_4,,,,4,,,20.45,,,,2,False,0.06,0.15,
78,7,cf_5,,,5,2,,,,5,,,3,True,0.06,0.01,
79,7,cf_6,1,1,,,,,,5,,,3,True,0.06,0.01,
80,7,cf_7,,,,5,2,,,7,,,3,False,0.06,0.07,
81,7,cf_8,,,,2,2,,,5,,,3,False,0.06,0.03,
82,7,cf_9,,1,,6,,,,3,,,3,False,0.06,0.07,
83,7,cf_10,,1,,6,,,,7,,,3,False,0.06,0.06,
84,8,xin,6,4,1,1,1,0,26.01,0,1.17,,,,,,
85,8,cf_1,,,,,,,,,,,0,False,0.12,0.12,
86,8,cf_2,1,,,3,,,,3,,,3,True,0.12,0.04,
87,8,cf_3,3,5,,,,,,7,,,3,False,0.12,0.13,
88,8,cf_4,3,6,,,,,,5,,,3,True,0.12,0.02,
89,8,cf_5,3,1,,3,,,,,,,3,True,0.12,0.01,
90,8,cf_6,4,,4,4,,,,,,,3,False,0.12,0.13,
91,8,cf_7,4,,,6,,,26.02,,,,3,False,0.12,0.09,
92,8,cf_8,1,3,6,5,,,,,,,4,True,0.12,0.06,
93,8,cf_9,3,3,2,5,,,,,,,4,True,0.12,0.05,
94,8,cf_10,5,1,5,,,,,4,,,4,False,0.12,0.07,

# picking correct CF

### expected

In [ ]:
# Check directional constraints directly
# These features should only improve (increase) or stay the same
SHOULD_INCREASE = ["cgtsmok", "alcfreq", "dosprt"]

# These features should only improve (decrease) or stay the same
SHOULD_DECREASE = ["bmi", "etfruit", "eatveg", "slprl", "paccnois"]


print("Directional constraints:")
print(f"  Should increase (↑): {SHOULD_INCREASE}")
print(f"  Should decrease (↓): {SHOULD_DECREASE}")

Directional constraints:
  Should increase (↑): ['cgtsmok', 'alcfreq', 'dosprt']
  Should decrease (↓): ['bmi', 'etfruit', 'eatveg', 'slprl', 'paccnois']

In [ ]:
# Check if CFs violate directional constraints
# First, ensure numeric columns are actually numeric for comparison
numeric_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# Create a working copy with numeric values
df_check = batch_cfcheck_df.copy()
for col in numeric_cols:
    df_check[col] = pd.to_numeric(df_check[col], errors="coerce")

# Extract baseline values per query_index
baseline_values = df_check[df_check["cf_id"] == "xin"].set_index("query_index")[numeric_cols]

# Check violations for each CF
def check_violations(row):
    if row["cf_id"] == "xin":
        return ""

    baseline = baseline_values.loc[row["query_index"]]
    violations = []

    # Check features that should increase
    for feat in SHOULD_INCREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] < baseline[feat]:
                violations.append(f"{feat}↓")

    # Check features that should decrease
    for feat in SHOULD_DECREASE:
        if pd.notna(row[feat]) and pd.notna(baseline[feat]):
            if row[feat] > baseline[feat]:
                violations.append(f"{feat}↑")

    return "NO: " + ", ".join(violations) if violations else ""

batch_cfcheck_df["Expected"] = df_check.apply(check_violations, axis=1)
batch_cfcheck_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.22,,,,,,
1,0,cf_1,,,,,,,,,,,0,True,0.03,0.01,
2,0,cf_2,,1,5,,1,,,,,,3,True,0.03,0.0,
3,0,cf_3,,,6,7,,,18.97,,,,3,False,0.03,0.14,
4,0,cf_4,,,5,,,,19.03,4,,,3,True,0.03,0.01,NO: bmi↑
5,0,cf_5,2,4,6,1,,,,,,,4,False,0.03,0.05,"NO: alcfreq↓, eatveg↑"
6,0,cf_6,2,1,5,,1,,,,,,4,True,0.03,0.0,
7,0,cf_7,6,1,5,7,,,,,,,4,True,0.03,0.0,NO: etfruit↑
8,0,cf_8,2,,6,5,,,,5,,,4,False,0.03,0.08,
9,0,cf_9,1,1,4,,1,,,,,,4,False,0.03,0.02,
10,0,cf_10,1,1,4,,,1,,,,,4,False,0.03,0.02,NO: paccnois↑
11,1,xin,3,4,1,2,3,0,22.38,0,1.3,,,,,,
12,1,cf_1,,,,,,,,,,,0,False,0.25,0.25,
13,1,cf_2,,,,,1,,,,,,1,True,0.25,0.07,
14,1,cf_3,2,,,,1,,,,,,2,True,0.25,0.04,
15,1,cf_4,1,,,4,4,,,,,,3,True,0.25,0.01,NO: slprl↑
16,1,cf_5,,2,,,2,,,2,,,3,True,0.25,0.03,
17,1,cf_6,,,,3,1,,22.39,,,,3,True,0.25,0.05,NO: bmi↑
18,1,cf_7,,1,2,4,,,,7,,,4,True,0.25,0.02,
19,1,cf_8,1,6,,4,1,,,,,,4,False,0.25,0.14,NO: eatveg↑
20,1,cf_9,2,,6,,1,,,5,,,4,True,0.25,0.04,
21,2,xin,5,3,1,1,4,0,22.69,7,1.08,,,,,,
22,2,cf_1,,,,,,,,,,,0,False,0.22,0.22,
23,2,cf_2,3,,,,2,,22.68,,,,3,False,0.22,0.14,
24,2,cf_3,1,,,,2,,22.68,,,,3,True,0.22,0.07,
25,2,cf_4,3,,5,4,2,,,,,,4,True,0.22,0.03,
26,2,cf_5,3,,6,2,1,,,,,,4,True,0.22,0.03,
27,2,cf_6,4,,6,7,2,,,,,,4,True,0.22,0.05,
28,2,cf_7,,,2,2,1,,22.68,,,,4,True,0.22,0.01,
29,2,cf_8,3,1,,,1,,22.68,,,,4,True,0.22,0.02,
30,2,cf_9,2,,,,2,,22.68,3,,,4,True,0.22,0.05,NO: dosprt↓
31,3,xin,3,3,6,6,2,0,24.34,1,1.18,,,,,,
32,3,cf_1,,,,,,,,,,,0,False,0.07,0.07,
33,3,cf_2,,,,,,,,2,,,1,False,0.07,0.06,
34,3,cf_3,1,,,3,,,,,,,2,False,0.07,0.1,NO: alcfreq↓
35,3,cf_4,2,,,,,,,2,,,2,False,0.07,0.05,
36,3,cf_5,,,,5,,,,4,,,2,False,0.07,0.07,NO: alcfreq↓
37,3,cf_6,4,4,,,,,,,,,2,False,0.07,0.12,"NO: etfruit↑, eatveg↑"
38,3,cf_7,,,,,,,,3,,,1,False,0.07,0.05,
39,3,cf_8,,,3,7,,,,3,,,3,False,0.07,0.05,NO: cgtsmok↓
40,3,cf_9,2,,,1,,,,7,,,3,False,0.07,0.12,NO: alcfreq↓
41,3,cf_10,2,,,7,,,,4,,,3,False,0.07,0.05,
42,4,xin,5,4,2,7,1,0,21.26,3,1.31,,,,,,
43,4,cf_1,,,,,,,,,,,0,True,0.08,0.01,
44,4,cf_2,,2,5,,,,,,,,2,True,0.08,0.01,
45,4,cf_3,2,3,,,,,,,,,2,True,0.08,0.03,
46,4,cf_4,3,3,,,,,,,,,2,True,0.08,0.02,
47,4,cf_5,1,,4,4,,,,,,,3,True,0.08,0.02,NO: alcfreq↓
48,4,cf_6,1,,3,3,,,,,,,3,True,0.08,0.02,NO: alcfreq↓
49,4,cf_7,2,2,4,,,,,,,,3,True,0.08,0.03,
50,4,cf_8,4,,,2,2,,,,,,3,True,0.08,0.02,"NO: alcfreq↓, slprl↑"
51,5,xin,2,2,1,2,4,0,27.99,0,1.19,,,,,,
52,5,cf_1,,,,,,,,,,,0,False,0.05,0.05,
53,5,cf_2,,,,3,,,,6,,,2,True,0.05,0.02,
54,5,cf_3,,1,,3,,,,3,,,3,False,0.05,0.14,
55,5,cf_4,1,,,,,,28.01,7,,,3,True,0.05,0.01,NO: bmi↑
56,5,cf_5,,,,1,1,,28.01,,,,3,True,0.05,0.02,"NO: alcfreq↓, bmi↑"
57,5,cf_6,,3,3,7,2,,,,,,4,False,0.05,0.11,NO: eatveg↑
58,5,cf_7,,3,4,,3,,,4,,,4,False,0.05,0.1,NO: eatveg↑
59,5,cf_8,,3,4,7,,,,5,,,4,False,0.05,0.09,NO: eatveg↑
60,5,cf_9,3,4,,7,1,,,,,,4,False,0.05,0.09,"NO: etfruit↑, eatveg↑"
61,5,cf_10,,3,4,6,1,,,,,,4,False,0.05,0.2,NO: eatveg↑
62,6,xin,2,3,5,4,1,0,27.68,4,0.98,,,,,,
63,6,cf_1,,,,,,,,,,,0,False,0.05,0.12,
64,6,cf_2,3,,,,,,,6,,,2,False,0.05,0.09,NO: etfruit↑
65,6,cf_3,,,6,,,,,5,,,2,False,0.05,0.1,
66,6,cf_4,,,1,,,,,1,,,2,False,0.05,0.07,"NO: cgtsmok↓, dosprt↓"
67,6,cf_5,,,,1,,,,0,,,2,False,0.05,0.18,"NO: alcfreq↓, dosprt↓"
68,6,cf_6,,,,7,,,,7,,,2,False,0.05,0.15,
69,6,cf_7,,,,,4,,,2,,,2,False,0.05,0.06,"NO: dosprt↓, slprl↑"
70,6,cf_8,,2,,,,,,3,,,2,False,0.05,0.04,NO: dosprt↓
71,6,cf_9,,,4,,2,,,5,,,3,False,0.05,0.18,"NO: cgtsmok↓, slprl↑"
72,6,cf_10,1,5,4,,,,,,,,3,False,0.05,0.03,"NO: cgtsmok↓, eatveg↑"
73,7,xin,2,3,6,3,1,0,20.44,2,1.16,,,,,,
74,7,cf_1,,,,,,,,,,,0,False,0.06,0.06,
75,7,cf_2,,,,2,,,,4,,,2,False,0.06,0.03,NO: alcfreq↓
76,7,cf_3,,,1,,2,,,,,,2,True,0.06,0.02,"NO: cgtsmok↓, slprl↑"
77,7,cf_4,,,,4,,,20.45,,,,2,False,0.06,0.15,NO: bmi↑
78,7,cf_5,,,5,2,,,,5,,,3,True,0.06,0.01,"NO: cgtsmok↓, alcfreq↓"
79,7,cf_6,1,1,,,,,,5,,,3,True,0.06,0.01,
80,7,cf_7,,,,5,2,,,7,,,3,False,0.06,0.07,NO: slprl↑
81,7,cf_8,,,,2,2,,,5,,,3,False,0.06,0.03,"NO: alcfreq↓, slprl↑"
82,7,cf_9,,1,,6,,,,3,,,3,False,0.06,0.07,
83,7,cf_10,,1,,6,,,,7,,,3,False,0.06,0.06,
84,8,xin,6,4,1,1,1,0,26.01,0,1.17,,,,,,
85,8,cf_1,,,,,,,,,,,0,False,0.12,0.12,
86,8,cf_2,1,,,3,,,,3,,,3,True,0.12,0.04,
87,8,cf_3,3,5,,,,,,7,,,3,False,0.12,0.13,NO: eatveg↑
88,8,cf_4,3,6,,,,,,5,,,3,True,0.12,0.02,NO: eatveg↑
89,8,cf_5,3,1,,3,,,,,,,3,True,0.12,0.01,
90,8,cf_6,4,,4,4,,,,,,,3,False,0.12,0.13,
91,8,cf_7,4,,,6,,,26.02,,,,3,False,0.12,0.09,NO: bmi↑
92,8,cf_8,1,3,6,5,,,,,,,4,True,0.12,0.06,
93,8,cf_9,3,3,2,5,,,,,,,4,True,0.12,0.05,
94,8,cf_10,5,1,5,,,,,4,,,4,False,0.12,0.07,

### is valid

In [ ]:
# --- Select exactly one CF per query_index (random valid without violations) ---

# Split baseline and CF rows
df_xin = batch_cfcheck_df[batch_cfcheck_df["cf_id"] == "xin"]
df_cf  = batch_cfcheck_df[batch_cfcheck_df["cf_id"] != "xin"]

def select_random_cf(group):
    """Select one random CF that is valid and has no violations (Expected is empty)."""
    # First try: valid AND no violations
    good_cfs = group[(group["valid"] == True) & (group["Expected"] == "")]
    if len(good_cfs) > 0:
        return good_cfs.sample(n=1, random_state=42)

    # Fallback: any valid CF
    valid_cfs = group[group["valid"] == True]
    if len(valid_cfs) > 0:
        return valid_cfs.sample(n=1, random_state=42)

    # Last resort: first CF
    return group.iloc[[0]]

# Select one random CF per query_index
df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

# Combine baseline + selected CF
batch_cfcheck_df = pd.concat([df_xin, df_cf_selected], ignore_index=True)

# Ensure xin appears before CF for each query_index
batch_cfcheck_df["is_xin"] = (batch_cfcheck_df["cf_id"] == "xin").astype(int)
batch_cfcheck_df = (
    batch_cfcheck_df
    .sort_values(["query_index", "is_xin"], ascending=[True, False])
    .drop(columns="is_xin")
)
batch_cfcheck_df

/tmp/ipykernel_39625/2325069138.py:23: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_cf_selected = df_cf.groupby("query_index", group_keys=False).apply(select_random_cf).reset_index(drop=True)

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,Gower,Nchanged,valid,risk_before,predicted_risk_after,Expected
0,0,xin,4,3,3,4,2,0,18.99,0,1.22,,,,,,
9,0,cf_1,,,,,,,,,,,0,True,0.03,0.01,
1,1,xin,3,4,1,2,3,0,22.38,0,1.3,,,,,,
10,1,cf_3,2,,,,1,,,,,,2,True,0.25,0.04,
2,2,xin,5,3,1,1,4,0,22.69,7,1.08,,,,,,
11,2,cf_3,1,,,,2,,22.68,,,,3,True,0.22,0.07,
3,3,xin,3,3,6,6,2,0,24.34,1,1.18,,,,,,
12,3,cf_1,,,,,,,,,,,0,False,0.07,0.07,
4,4,xin,5,4,2,7,1,0,21.26,3,1.31,,,,,,
13,4,cf_2,,2,5,,,,,,,,2,True,0.08,0.01,
5,5,xin,2,2,1,2,4,0,27.99,0,1.19,,,,,,
14,5,cf_2,,,,3,,,,6,,,2,True,0.05,0.02,
6,6,xin,2,3,5,4,1,0,27.68,4,0.98,,,,,,
15,6,cf_1,,,,,,,,,,,0,False,0.05,0.12,
7,7,xin,2,3,6,3,1,0,20.44,2,1.16,,,,,,
16,7,cf_6,1,1,,,,,,5,,,3,True,0.06,0.01,
8,8,xin,6,4,1,1,1,0,26.01,0,1.17,,,,,,
17,8,cf_5,3,1,,3,,,,,,,3,True,0.12,0.01,

In [ ]:
batch_cfcheck_df["valid"] = batch_cfcheck_df["valid"].replace(
    {
        False : "No",
        True : "Yes",
    }
)